/*
 * emit_byrd_asm.c — x64 ASM Byrd box emitter for sno2c
 *
 * x64 Linux ELF64, NASM syntax.
 *
 * Mirrors emit_byrd.c structure.  The -asm flag in main.c selects this
 * emitter instead of the C backend.
 *
 * Design (from TINY.md Sprint A0–A10):
 *   α/β/γ/ω are real ASM labels (not C labels in structs).
 *   All pattern variables live flat in .bss as QWORD slots — no calloc,
 *   no structs, no three-level scoping.
 *   Named patterns are plain labels with a 2-way jmp dispatch.
 *
 * Sprint A0: null program only.
 *   Input:  any .sno (ignored — null program has no statements)
 *   Output: NASM x64 ELF64 .s that:
 *             global _start
 *             section .text
 *             _start:  mov eax,60  ; sys_exit
 *                      xor edi,edi ; exit code 0
 *                      syscall
 *
 * Build (once emit_byrd_asm.c is compiled in):
 *   src/sno2c/sno2c -asm null.sno > null.s
 *   nasm -f elf64 null.s -o null.o
 *   ld null.o -o null
 *   ./null
 *   echo $?   # → 0
 *
 * M-ASM-HELLO fires when the above succeeds.
 */

#include "sno2c.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdarg.h>

/* -----------------------------------------------------------------------
 * Output helper
 * ----------------------------------------------------------------------- */

static FILE *asm_out;

static void A(const char *fmt, ...) {
    va_list ap;
    va_start(ap, fmt);
    vfprintf(asm_out, fmt, ap);
    va_end(ap);
}

/* -----------------------------------------------------------------------
 * asm_emit_null_program — Sprint A0
 *
 * Emit a minimal x64 Linux ELF64 null program that exits with code 0.
 * No SNOBOL4 runtime linked.  Just the raw syscall.
 * ----------------------------------------------------------------------- */
static void asm_emit_null_program(void) {
    A("; generated by sno2c -asm  (Sprint A0 — null program)\n");
    A("; assemble:  nasm -f elf64 null.s -o null.o\n");
    A("; link:      ld null.o -o null\n");
    A("; run:       ./null  &&  echo exit=$?\n");
    A("\n");
    A("    global _start\n");
    A("\n");
    A("section .text\n");
    A("\n");
    A("_start:\n");
    A("    mov     eax, 60        ; sys_exit\n");
    A("    xor     edi, edi       ; exit code 0\n");
    A("    syscall\n");
}

/* -----------------------------------------------------------------------
 * Public entry point
 *
 * Called from main.c when -asm flag is set.
 * prog: parsed program (Sprint A0 ignores it — null program always).
 * f:    output FILE* (stdout or -o file).
 * ----------------------------------------------------------------------- */
void asm_emit(Program *prog, FILE *f) {
    (void)prog;   /* Sprint A0: program content ignored */
    asm_out = f;
    asm_emit_null_program();
}
