; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_PAT_ret_γ             resq 1
P_PAT_ret_ω             resq 1
scan_start_2             resq 1
nref0_r12                resq 1
cap_WHEN_buf             resb 256
cap_WHEN_len             resq 1
cap_WHO_buf              resb 256
cap_WHO_len              resq 1
cap_WHAT_buf             resb 256
cap_WHAT_len             resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536

;  PAT =================================================================================================================

section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 8
                            call        comm_stno
                            mov         qword [rbp-32], 1
                            mov         qword [rbp-24], 0
                            FAIL_BR     Ln_0
                            SET_VAR     S_PAT
                            jmp         Ln_0

Ln_0:
;  LOOP ================================================================================================================
L_LOOP_0:                   mov         edi, 11
                            call        comm_stno
                            lea         rdi, [rel S_INPUT]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Lf_1
                            SET_VAR     S_LINE
                            jmp         Ln_1
Lf_1:                       GOTO_ALWAYS L_SNO_END     ; END

; ======================================================================================================================
Ln_1:                       mov         edi, 12
                            call        comm_stno
                            GET_VAR     S_LINE
                            SUBJ_FROM16
                            test        eax, eax
                            jnz         P_2_ω
                            mov         qword [scan_start_2], 0
scan_retry_2:
                            mov         rax, [scan_start_2]
                            mov         [cursor], rax
                            jmp         P_2_α


P_2_α: ; REF(PAT)
                            lea         rax, [rel nref0_γ]
                            mov         [P_PAT_ret_γ], rax
                            lea         rax, [rel nref0_ω]
                            mov         [P_PAT_ret_ω], rax
                            mov         [nref0_r12], r12
                            lea         r12, [rel box_PAT_data_template]
                            jmp         P_PAT_α
P_2_β:                      lea         rax, [rel nref0_γ] ; REF(%s)
                            mov         [P_PAT_ret_γ], rax
                            lea         rax, [rel nref0_ω]
                            mov         [P_PAT_ret_ω], rax
                            mov         [nref0_r12], r12
                            lea         r12, [rel box_PAT_data_template]
                            jmp         P_PAT_β

nref0_γ:
                            mov         r12, [nref0_r12]
                            jmp         P_2_γ
nref0_ω:                    mov         r12, [nref0_r12]
                            jmp         P_2_ω

P_2_γ:                      mov         rax, [cursor]
                            mov         [scan_start_2], rax
                            SET_CAPTURE S_WHEN, cap_WHEN_buf, cap_WHEN_len
                            SET_CAPTURE S_WHO, cap_WHO_buf, cap_WHO_len
                            SET_CAPTURE S_WHAT, cap_WHAT_buf, cap_WHAT_len
                            jmp         Ln_2
P_2_ω:                      cmp         qword [rel kw_anchor], 0
                            jne         L_LOOP_0
                            mov         rax, [scan_start_2]
                            inc         rax
                            cmp         rax, [subject_len_val]
                            jg          L_LOOP_0
                            mov         [scan_start_2], rax
                            jmp         scan_retry_2
                            jmp         L_LOOP_0

; ======================================================================================================================
Ln_2:                       mov         edi, 13
                            call        comm_stno
                            lea         rdi, [rel S_WHO]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        rdx
                            push        rax
                            LOAD_STR    S_SP_invented_SP_the_SP
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            push        rdx
                            push        rax
                            lea         rdi, [rel S_WHAT]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            push        rdx
                            push        rax
                            LOAD_STR    S_SP_in_SP
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            push        rdx
                            push        rax
                            lea         rdi, [rel S_WHEN]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Lf_3
                            SET_OUTPUT
                            jmp         L_LOOP_0
Lf_3:                       jmp         L_LOOP_0
Ln_3:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .data
lit_str_1            db 32, 58

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_PAT_α (α entry) [r12=DATA block]
;  PAT =================================================================================================================
P_PAT_α:                    mov         qword [r12+16], 0
                            mov         qword [r12+24], 0
                            mov         qword [r12+32], 0
                            mov         qword [r12+40], 0
                            mov         qword [r12+48], 0
                            mov         qword [r12+56], 0
                            mov         qword [r12+64], 0
                            mov         qword [r12+72], 0
                            mov         qword [r12+80], 0
                            mov         qword [r12+88], 0
pat_PAT_body:               jmp         seq_l1_α ; SEQ
P_PAT_β:                    jmp         seq_r1_β
seq_l1_α:                   POS_α       0, cursor, seq_r1_α, patdef_PAT_ω ; POS(%ld)
seq_l1_β:                   POS_β       cursor, patdef_PAT_ω
seq_r1_α:                   jmp         seq_l2_α ; SEQ
seq_r1_β:                   jmp         seq_r2_β

seq_l2_α: ; DOL(WHEN $  WHEN)
                            DOL_SAVE    r12+16, cursor, dol3_child_α ; DOL α — save entry cursor
seq_l2_β:                   jmp         dol3_child_β ; DOL β
dol3_child_α:               LEN_α       4, r12+24, cursor, subject_len_val, dol3_γ, dol3_ω ; LEN(%ld)
dol3_child_β:               LEN_β       r12+24, cursor, dol3_ω ; LEN β
dol3_γ:                     DOL_CAPTURE r12+16, cursor, cap_WHEN_buf, cap_WHEN_len, subject_data, seq_r2_α ; DOL γ — capture span
dol3_ω:                     jmp         seq_l1_β ; DOL ω — child failed
seq_r2_α:                   jmp         seq_l5_α ; SEQ
seq_r2_β:                   jmp         seq_r5_β
seq_l5_α:                   TAB_α       6, r12+32, cursor, seq_r5_α, seq_l2_β ; TAB(%ld)
seq_l5_β:                   TAB_β       r12+32, cursor, seq_l2_β ; TAB β
seq_r5_α:                   jmp         seq_l7_α ; SEQ
seq_r5_β:                   jmp         seq_r7_β

seq_l7_α: ; DOL(WHO $  WHO)
                            DOL_SAVE    r12+40, cursor, dol8_child_α ; DOL α — save entry cursor
seq_l7_β:                   jmp         dol8_child_β ; DOL β
dol8_child_α:               ARB_α       r12+48, r12+56, cursor, dol8_γ ; ARB α
dol8_child_β:               ARB_β       r12+48, r12+56, cursor, subject_len_val, dol8_γ, dol8_ω ; ARB β
dol8_γ:                     DOL_CAPTURE r12+40, cursor, cap_WHO_buf, cap_WHO_len, subject_data, seq_r7_α ; DOL γ — capture span
dol8_ω:                     jmp         seq_l5_β ; DOL ω — child failed
seq_r7_α:                   jmp         seq_l10_α ; SEQ
seq_r7_β:                   jmp         seq_r10_β
seq_l10_α:                  LIT_α       lit_str_1, 2, r12+64, cursor, subject_data, subject_len_val, seq_r10_α, seq_l7_β ; LIT α
seq_l10_β:                  LIT_β       r12+64, cursor, seq_l7_β ; LIT β
seq_r10_α:                  jmp         seq_l11_α ; SEQ
seq_r10_β:                  jmp         seq_r11_β
seq_l11_α:                  TAB_α       24, r12+72, cursor, seq_r11_α, seq_l10_β ; TAB(%ld)
seq_l11_β:                  TAB_β       r12+72, cursor, seq_l10_β ; TAB β

seq_r11_α: ; DOL(WHAT $  WHAT)
                            DOL_SAVE    r12+80, cursor, dol13_child_α ; DOL α — save entry cursor
seq_r11_β:                  jmp         dol13_child_β ; DOL β
dol13_child_α:              REM_α       r12+88, cursor, subject_len_val, dol13_γ ; REM
dol13_child_β:              REM_β       r12+88, cursor, dol13_ω ; REM β
dol13_γ:                    DOL_CAPTURE r12+80, cursor, cap_WHAT_buf, cap_WHAT_len, subject_data, patdef_PAT_γ ; DOL γ — capture span
dol13_ω:                    jmp         seq_l11_β ; DOL ω — child failed
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_PAT_γ:               NAMED_PAT_γ P_PAT_ret_γ ; named pat γ
patdef_PAT_ω:               NAMED_PAT_ω P_PAT_ret_ω ; named pat ω

section .text
;  STUB LABELS =========================================================================================================

section .rodata
global  box_PAT_reloc_count, box_PAT_reloc_table
; --- box PAT ---
box_PAT_reloc_count: dq 0
box_PAT_reloc_table:
; (entries added by M-T2-INVOKE)

;  BOX RELOCATION TABLES ===============================================================================================

global  box_PAT_data_template, box_PAT_data_size
section .data
;  BOX DATA TEMPLATES ==================================================================================================
                            align       8
box_PAT_data_size: dq 96
box_PAT_data_template:
dq 0  ; [r12+0] = P_PAT_ret_γ
dq 0  ; [r12+8] = P_PAT_ret_ω
dq 0  ; [r12+16] = dol_entry_WHEN
dq 0  ; [r12+24] = len4_saved
dq 0  ; [r12+32] = tab6_saved
dq 0  ; [r12+40] = dol_entry_WHO
dq 0  ; [r12+48] = arb9_start
dq 0  ; [r12+56] = arb9_step
dq 0  ; [r12+64] = seq_l10_α_saved
dq 0  ; [r12+72] = tab12_saved
dq 0  ; [r12+80] = dol_entry_WHAT
dq 0  ; [r12+88] = rem14_saved


section .data
S_PAT                db 80, 65, 84, 0  ; "PAT"
S_WHAT               db 87, 72, 65, 84, 0  ; "WHAT"
S_REM                db 82, 69, 77, 0  ; "REM"
S_TAB                db 84, 65, 66, 0  ; "TAB"
S_SP_CL              db 32, 58, 0  ; " :"
S_WHO                db 87, 72, 79, 0  ; "WHO"
S_ARB                db 65, 82, 66, 0  ; "ARB"
S_WHEN               db 87, 72, 69, 78, 0  ; "WHEN"
S_LEN                db 76, 69, 78, 0  ; "LEN"
S_POS                db 80, 79, 83, 0  ; "POS"
S_LOOP               db 76, 79, 79, 80, 0  ; "LOOP"
S_LINE               db 76, 73, 78, 69, 0  ; "LINE"
S_INPUT              db 73, 78, 80, 85, 84, 0  ; "INPUT"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_SP_in_SP           db 32, 105, 110, 32, 0  ; " in "
S_SP_invented_SP_the_SP db 32, 105, 110, 118, 101, 110, 116, 101, 100, 32, 116, 104, 101, 32, 0  ; " invented the "
S_END                db 69, 78, 68, 0  ; "END"
