; generated by sno2c -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o mock_engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_set_capture
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_s_ret_gamma            resq 1
P_s_ret_omega            resq 1
P_v_ret_gamma            resq 1
P_v_ret_omega            resq 1
P_r_ret_gamma            resq 1
P_r_ret_omega            resq 1
P_i_ret_gamma            resq 1
P_i_ret_omega            resq 1
P_n_ret_gamma            resq 1
P_n_ret_omega            resq 1
P_roman_ret_gamma        resq 1
P_roman_ret_omega        resq 1
P_OUTPUT_ret_gamma       resq 1
P_OUTPUT_ret_omega       resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
                            PROG_INIT


;  PROGRAM BODY ========================================================================================================

                            sub         rsp, 16
                            LOAD_STR    S_roman_LP_n_RP_s_CM_v_CM_r_CM_i
                            mov         [rbp-16], rax
                            mov         [rbp-8],  rdx
                            STORE_ARG32 0
                            APPLY_FN_N  S_DEFINE, 1
                            add         rsp, 16
                            STORE_RESULT

                            jmp         L_roman_end_0

; ======================================================================================================================

L_sn_0:
;  roman ===============================================================================================================
L_roman_1:                  GET_VAR     S_s
                            ASSIGN_STR  S_s, S_5, L_sn_1
                            jmp         L_sn_1

; ======================================================================================================================
L_sn_1:                     GET_VAR     S_v
                            CALL1_INT   S_ARRAY, 13
                            FAIL_BR     L_sn_2
                            SET_VAR     S_v
                            jmp         L_sn_2

; ======================================================================================================================
L_sn_2:                     LOAD_NULVCL


; ======================================================================================================================
L_sn_3:                     LOAD_NULVCL


; ======================================================================================================================
L_sn_4:                     LOAD_NULVCL


; ======================================================================================================================
L_sn_5:                     LOAD_NULVCL


; ======================================================================================================================
L_sn_6:                     LOAD_NULVCL


; ======================================================================================================================
L_sn_7:                     LOAD_NULVCL


; ======================================================================================================================
L_sn_8:                     LOAD_NULVCL


; ======================================================================================================================
L_sn_9:                     LOAD_NULVCL


; ======================================================================================================================
L_sn_10:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_11:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_12:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_13:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_14:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_15:                    GET_VAR     S_r
                            CALL1_INT   S_ARRAY, 13
                            FAIL_BR     L_sn_16
                            SET_VAR     S_r
                            jmp         L_sn_16

; ======================================================================================================================
L_sn_16:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_17:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_18:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_19:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_20:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_21:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_22:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_23:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_24:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_25:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_26:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_27:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_28:                    LOAD_NULVCL


; ======================================================================================================================
L_sn_29:                    GET_VAR     S_i
                            ASSIGN_INT  S_i, 1, L_sn_30
                            jmp         L_sn_30

L_sn_30:
;  RLOOP ===============================================================================================================
L_RLOOP_2:                  CONC2_VN16  S_GT, S_n
                            FAIL_BR16   L_sf_31
                            jmp         L_sn_31
L_sf_31:                    jmp         L_RDONE_3

; ======================================================================================================================
L_sn_31:                    sub         rsp, 32
                            GET_VAR     S_n
                            STORE_ARG32 0
                            LOAD_NULVCL

                            STORE_ARG32 16
                            APPLY_FN_N  S_GE, 2
                            add         rsp, 32
                            STORE_RESULT

                            FAIL_BR16   L_sf_32
                            jmp         L_sn_32
L_sf_32:                    jmp         L_RNEXT_4

; ======================================================================================================================
L_sn_32:                    GET_VAR     S_s
                            sub         rsp, 32
                            lea         rdi, [rel S_s]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            mov         qword [rbp-32], 1
                            mov         qword [rbp-24], 0
                            STORE_ARG32 16
                            APPLY_FN_N  S_CONCAT, 2
                            add         rsp, 32
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     L_sn_33
                            SET_VAR     S_s
                            jmp         L_sn_33

; ======================================================================================================================
L_sn_33:                    GET_VAR     S_n
                            mov         qword [rbp-32], 1
                            mov         qword [rbp-24], 0
                            FAIL_BR     L_sn_34
                            SET_VAR     S_n
                            jmp         L_RLOOP_2

L_sn_34:
;  RNEXT ===============================================================================================================
L_RNEXT_4:                  GET_VAR     S_i
                            mov         qword [rbp-32], 1
                            mov         qword [rbp-24], 0
                            FAIL_BR     L_sn_35
                            SET_VAR     S_i
                            jmp         L_RLOOP_2

L_sn_35:
;  RDONE ===============================================================================================================
L_RDONE_3:                  GET_VAR     S_roman
                            lea         rdi, [rel S_s]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     L_sn_36
                            SET_VAR     S_roman
                            GOTO_ALWAYS L_SNO_END     ; RETURN

L_sn_36:
L_roman_end_0:

;  roman_end ===========================================================================================================

; ======================================================================================================================
L_sn_37:                    GET_VAR     S_OUTPUT
                            CALL1_INT   S_roman, 1
                            FAIL_BR     L_sn_38
                            SET_OUTPUT

                            jmp         L_sn_38

; ======================================================================================================================
L_sn_38:                    GET_VAR     S_OUTPUT
                            CALL1_INT   S_roman, 4
                            FAIL_BR     L_sn_39
                            SET_OUTPUT

                            jmp         L_sn_39

; ======================================================================================================================
L_sn_39:                    GET_VAR     S_OUTPUT
                            CALL1_INT   S_roman, 9
                            FAIL_BR     L_sn_40
                            SET_OUTPUT

                            jmp         L_sn_40

; ======================================================================================================================
L_sn_40:                    GET_VAR     S_OUTPUT
                            CALL1_INT   S_roman, 42
                            FAIL_BR     L_sn_41
                            SET_OUTPUT

                            jmp         L_sn_41

; ======================================================================================================================
L_sn_41:                    GET_VAR     S_OUTPUT
                            CALL1_INT   S_roman, 1999
                            FAIL_BR     L_sn_42
                            SET_OUTPUT

                            jmp         L_sn_42

; ======================================================================================================================
L_sn_42:                    GET_VAR     S_OUTPUT
                            CALL1_INT   S_roman, 2024
                            FAIL_BR     L_sn_43
                            SET_OUTPUT

                            jmp         L_sn_43
L_sn_43:                    GOTO_ALWAYS L_SNO_END

L_SNO_END:
                            PROG_END

;  END =================================================================================================================

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_s_alpha (α entry)
P_s_alpha:                  jmp         seq_l0_alpha ; SEQ
P_s_beta:                   jmp         seq_r0_beta

seq_l0_alpha: ; REF(s)
                            lea         rax, [rel nref1_gamma]
                            mov         [P_s_ret_gamma], rax
                            lea         rax, [rel nref1_omega]
                            mov         [P_s_ret_omega], rax
                            jmp         P_s_alpha
seq_l0_beta:                lea         rax, [rel nref1_gamma] ; REF(%s)
                            mov         [P_s_ret_gamma], rax
                            lea         rax, [rel nref1_omega]
                            mov         [P_s_ret_omega], rax
                            jmp         P_s_beta

nref1_gamma:
                            jmp         seq_r0_alpha
;  s ===================================================================================================================
nref1_omega:                jmp         patdef_s_omega

; UNIMPLEMENTED node kind 20 → ω
seq_r0_alpha:
seq_r0_beta:                jmp         seq_l0_beta
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_s_gamma:
                            jmp         [P_s_ret_gamma]
patdef_s_omega:             jmp         [P_s_ret_omega]

; P_v_alpha (α entry)

; UNIMPLEMENTED: ARRAY() → ω
P_v_alpha:
P_v_beta:                   jmp         patdef_v_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_v_gamma:
                            jmp         [P_v_ret_gamma]
;  v ===================================================================================================================
patdef_v_omega:             jmp         [P_v_ret_omega]

; P_r_alpha (α entry)

; UNIMPLEMENTED: ARRAY() → ω
P_r_alpha:
P_r_beta:                   jmp         patdef_r_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_r_gamma:
                            jmp         [P_r_ret_gamma]
;  r ===================================================================================================================
patdef_r_omega:             jmp         [P_r_ret_omega]

; P_i_alpha (α entry)

; UNIMPLEMENTED node kind 8 → ω
P_i_alpha:
P_i_beta:                   jmp         patdef_i_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_i_gamma:
                            jmp         [P_i_ret_gamma]
;  i ===================================================================================================================
patdef_i_omega:             jmp         [P_i_ret_omega]

; P_n_alpha (α entry)

; UNIMPLEMENTED node kind 9 → ω
P_n_alpha:
P_n_beta:                   jmp         patdef_n_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_n_gamma:
                            jmp         [P_n_ret_gamma]
;  n ===================================================================================================================
patdef_n_omega:             jmp         [P_n_ret_omega]

; P_roman_alpha (α entry)

P_roman_alpha: ; REF(s)
                            lea         rax, [rel nref2_gamma]
                            mov         [P_s_ret_gamma], rax
                            lea         rax, [rel nref2_omega]
                            mov         [P_s_ret_omega], rax
                            jmp         P_s_alpha
P_roman_beta:               lea         rax, [rel nref2_gamma] ; REF(%s)
                            mov         [P_s_ret_gamma], rax
                            lea         rax, [rel nref2_omega]
                            mov         [P_s_ret_omega], rax
                            jmp         P_s_beta

nref2_gamma:
                            jmp         patdef_roman_gamma
;  roman ===============================================================================================================
nref2_omega:                jmp         patdef_roman_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_roman_gamma:
                            jmp         [P_roman_ret_gamma]
patdef_roman_omega:         jmp         [P_roman_ret_omega]

; P_OUTPUT_alpha (α entry)

; UNIMPLEMENTED: roman() → ω
P_OUTPUT_alpha:
P_OUTPUT_beta:              jmp         patdef_OUTPUT_omega
;  γ/ω ---------------------------------------------------------------------------------------------------------------
patdef_OUTPUT_gamma:
                            jmp         [P_OUTPUT_ret_gamma]
;  OUTPUT ==============================================================================================================
patdef_OUTPUT_omega:        jmp         [P_OUTPUT_ret_omega]

section .text
L_END_5:  ; STUB → _SNO_END (dangling or computed goto)
                            GOTO_ALWAYS L_SNO_END
L_RETURN_6:  ; STUB → _SNO_END (dangling or computed goto)
                            GOTO_ALWAYS L_SNO_END
;  STUB LABELS =========================================================================================================

section .data
S_DEFINE             db 68, 69, 70, 73, 78, 69, 0  ; "DEFINE"
S_roman_LP_n_RP_s_CM_v_CM_r_CM_i db 114, 111, 109, 97, 110, 40, 110, 41, 115, 44, 118, 44, 114, 44, 105, 0  ; "roman(n)s,v,r,i"
S_roman              db 114, 111, 109, 97, 110, 0  ; "roman"
S_s                  db 115, 0  ; "s"
S_5                  db 0  ; 
S_v                  db 118, 0  ; "v"
S_ARRAY              db 65, 82, 82, 65, 89, 0  ; "ARRAY"
S_r                  db 114, 0  ; "r"
S_M                  db 77, 0  ; "M"
S_CM                 db 67, 77, 0  ; "CM"
S_D                  db 68, 0  ; "D"
S_CD                 db 67, 68, 0  ; "CD"
S_C                  db 67, 0  ; "C"
S_XC                 db 88, 67, 0  ; "XC"
S_L                  db 76, 0  ; "L"
S_XL                 db 88, 76, 0  ; "XL"
S_X                  db 88, 0  ; "X"
S_IX                 db 73, 88, 0  ; "IX"
S_V                  db 86, 0  ; "V"
S_IV                 db 73, 86, 0  ; "IV"
S_I                  db 73, 0  ; "I"
S_i                  db 105, 0  ; "i"
S_RLOOP              db 82, 76, 79, 79, 80, 0  ; "RLOOP"
S_GT                 db 71, 84, 0  ; "GT"
S_n                  db 110, 0  ; "n"
S_GE                 db 71, 69, 0  ; "GE"
S_RNEXT              db 82, 78, 69, 88, 84, 0  ; "RNEXT"
S_RDONE              db 82, 68, 79, 78, 69, 0  ; "RDONE"
S_roman_end          db 114, 111, 109, 97, 110, 95, 101, 110, 100, 0  ; "roman_end"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_END                db 69, 78, 68, 0  ; "END"
S_CONCAT             db 67, 79, 78, 67, 65, 84, 0  ; "CONCAT"
