; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 4
                            call        comm_stno
                            sub         rsp, 32
                            CALL1_STR   S_datatype, S_hello
                            STORE_ARG32 0
                            LOAD_STR    S_string
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_0
                            jmp         Ln_0
Lf_0:                       jmp         L_e001_0

; ======================================================================================================================
Ln_0:                       mov         edi, 5
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_911_SL_001_CL_SP_string_SP_literal_SP_datatype
                            FAIL_BR     Lf_1
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_1:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_1:
;  e001 ================================================================================================================
L_e001_0:                   mov         edi, 6
                            call        comm_stno

; ======================================================================================================================
Ln_2:                       mov         edi, 8
                            call        comm_stno
                            sub         rsp, 32
                            CALL1_INT   S_datatype, 12
                            STORE_ARG32 0
                            LOAD_STR    S_integer
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_3
                            jmp         Ln_3
Lf_3:                       jmp         L_e002_1

; ======================================================================================================================
Ln_3:                       mov         edi, 9
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_911_SL_002_CL_SP_integer_SP_datatype
                            FAIL_BR     Lf_4
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_4:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_4:
;  e002 ================================================================================================================
L_e002_1:                   mov         edi, 10
                            call        comm_stno

; ======================================================================================================================
Ln_5:                       mov         edi, 12
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 16
                            LOAD_REAL   F_1
                            STORE_ARG32 0
                            APPLY_FN_N  S_datatype, 1
                            add         rsp, 16
                            STORE_RESULT
                            STORE_ARG32 0
                            LOAD_STR    S_real
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_6
                            jmp         Ln_6
Lf_6:                       jmp         L_e003_2

; ======================================================================================================================
Ln_6:                       mov         edi, 13
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_911_SL_003_CL_SP_real_SP_datatype
                            FAIL_BR     Lf_7
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_7:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_7:
;  e003 ================================================================================================================
L_e003_2:                   mov         edi, 14
                            call        comm_stno

; ======================================================================================================================
Ln_8:                       mov         edi, 17
                            call        comm_stno
                            sub         rsp, 32
                            CALL1_STR   S_datatype, S_14
                            STORE_ARG32 0
                            LOAD_STR    S_string
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_9
                            jmp         Ln_9
Lf_9:                       jmp         L_e004_3

; ======================================================================================================================
Ln_9:                       mov         edi, 18
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_911_SL_004_CL_SP_null_SP_is_SP_string
                            FAIL_BR     Lf_10
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_10:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_10:
;  e004 ================================================================================================================
L_e004_3:                   mov         edi, 19
                            call        comm_stno

; ======================================================================================================================
Ln_11:                      mov         edi, 21
                            call        comm_stno
                            LOAD_STR    S_PASS_SP_911_datatype_SP_LP_4_SL_4_RP
                            FAIL_BR     Ln_12
                            SET_OUTPUT
                            jmp         Ln_12
Ln_12:                      GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_differ             db 100, 105, 102, 102, 101, 114, 0  ; "differ"
S_string             db 115, 116, 114, 105, 110, 103, 0  ; "string"
S_datatype           db 100, 97, 116, 97, 116, 121, 112, 101, 0  ; "datatype"
S_hello              db 104, 101, 108, 108, 111, 0  ; "hello"
S_output             db 111, 117, 116, 112, 117, 116, 0  ; "output"
S_FAIL_SP_911_SL_001_CL_SP_string_SP_literal_SP_datatype db 70, 65, 73, 76, 32, 57, 49, 49, 47, 48, 48, 49, 58, 32, 115, 116, 114, 105, 110, 103, 32, 108, 105, 116, 101, 114, 97, 108, 32, 100, 97, 116, 97, 116, 121, 112, 101, 0  ; "FAIL 911/001: string literal datatype"
S_e001               db 101, 48, 48, 49, 0  ; "e001"
S_integer            db 105, 110, 116, 101, 103, 101, 114, 0  ; "integer"
S_FAIL_SP_911_SL_002_CL_SP_integer_SP_datatype db 70, 65, 73, 76, 32, 57, 49, 49, 47, 48, 48, 50, 58, 32, 105, 110, 116, 101, 103, 101, 114, 32, 100, 97, 116, 97, 116, 121, 112, 101, 0  ; "FAIL 911/002: integer datatype"
S_e002               db 101, 48, 48, 50, 0  ; "e002"
S_real               db 114, 101, 97, 108, 0  ; "real"
S_FAIL_SP_911_SL_003_CL_SP_real_SP_datatype db 70, 65, 73, 76, 32, 57, 49, 49, 47, 48, 48, 51, 58, 32, 114, 101, 97, 108, 32, 100, 97, 116, 97, 116, 121, 112, 101, 0  ; "FAIL 911/003: real datatype"
S_e003               db 101, 48, 48, 51, 0  ; "e003"
S_14                 db 0  ; 
S_FAIL_SP_911_SL_004_CL_SP_null_SP_is_SP_string db 70, 65, 73, 76, 32, 57, 49, 49, 47, 48, 48, 52, 58, 32, 110, 117, 108, 108, 32, 105, 115, 32, 115, 116, 114, 105, 110, 103, 0  ; "FAIL 911/004: null is string"
S_e004               db 101, 48, 48, 52, 0  ; "e004"
S_PASS_SP_911_datatype_SP_LP_4_SL_4_RP db 80, 65, 83, 83, 32, 57, 49, 49, 95, 100, 97, 116, 97, 116, 121, 112, 101, 32, 40, 52, 47, 52, 41, 0  ; "PASS 911_datatype (4/4)"
S_end                db 101, 110, 100, 0  ; "end"
F_1                  dq 0x3ff547ae147ae148  ; 1.33
