; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 5
                            call        comm_stno
                            CALL1_STR   S_integer, S_abc
                            FAIL_BR     Lf_0
                            jmp         Ln_0
Lf_0:                       jmp         L_e001_0

; ======================================================================================================================
Ln_0:                       mov         edi, 6
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_913_SL_001_CL_SP_integer_LP_string_RP_SP_should_SP_fail
                            FAIL_BR     Lf_1
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_1:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_1:
;  e001 ================================================================================================================
L_e001_0:                   mov         edi, 7
                            call        comm_stno

; ======================================================================================================================
Ln_2:                       mov         edi, 10
                            call        comm_stno
                            CALL1_INT   S_integer, 12
                            FAIL_BR     Ln_3
                            jmp         L_e002_1

; ======================================================================================================================
Ln_3:                       mov         edi, 11
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_913_SL_002_CL_SP_integer_LP_12_RP_SP_should_SP_succeed
                            FAIL_BR     Lf_4
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_4:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_4:
;  e002 ================================================================================================================
L_e002_1:                   mov         edi, 12
                            call        comm_stno

; ======================================================================================================================
Ln_5:                       mov         edi, 15
                            call        comm_stno
                            CALL1_STR   S_integer, S_12
                            FAIL_BR     Ln_6
                            jmp         L_e003_2

; ======================================================================================================================
Ln_6:                       mov         edi, 16
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_913_SL_003_CL_SP_integer_LP_numeric_MI_string_RP_SP_should_SP_succeed
                            FAIL_BR     Lf_7
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_7:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_7:
;  e003 ================================================================================================================
L_e003_2:                   mov         edi, 17
                            call        comm_stno

; ======================================================================================================================
Ln_8:                       mov         edi, 19
                            call        comm_stno
                            LOAD_STR    S_PASS_SP_913_integer_pred_SP_LP_3_SL_3_RP
                            FAIL_BR     Ln_9
                            SET_OUTPUT
                            jmp         Ln_9
Ln_9:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_integer            db 105, 110, 116, 101, 103, 101, 114, 0  ; "integer"
S_abc                db 97, 98, 99, 0  ; "abc"
S_output             db 111, 117, 116, 112, 117, 116, 0  ; "output"
S_FAIL_SP_913_SL_001_CL_SP_integer_LP_string_RP_SP_should_SP_fail db 70, 65, 73, 76, 32, 57, 49, 51, 47, 48, 48, 49, 58, 32, 105, 110, 116, 101, 103, 101, 114, 40, 115, 116, 114, 105, 110, 103, 41, 32, 115, 104, 111, 117, 108, 100, 32, 102, 97, 105, 108, 0  ; "FAIL 913/001: integer(string) should fail"
S_e001               db 101, 48, 48, 49, 0  ; "e001"
S_FAIL_SP_913_SL_002_CL_SP_integer_LP_12_RP_SP_should_SP_succeed db 70, 65, 73, 76, 32, 57, 49, 51, 47, 48, 48, 50, 58, 32, 105, 110, 116, 101, 103, 101, 114, 40, 49, 50, 41, 32, 115, 104, 111, 117, 108, 100, 32, 115, 117, 99, 99, 101, 101, 100, 0  ; "FAIL 913/002: integer(12) should succeed"
S_e002               db 101, 48, 48, 50, 0  ; "e002"
S_12                 db 49, 50, 0  ; "12"
S_FAIL_SP_913_SL_003_CL_SP_integer_LP_numeric_MI_string_RP_SP_should_SP_succeed db 70, 65, 73, 76, 32, 57, 49, 51, 47, 48, 48, 51, 58, 32, 105, 110, 116, 101, 103, 101, 114, 40, 110, 117, 109, 101, 114, 105, 99, 45, 115, 116, 114, 105, 110, 103, 41, 32, 115, 104, 111, 117, 108, 100, 32, 115, 117, 99, 99, 101, 101, 100, 0  ; "FAIL 913/003: integer(numeric-string) should succeed"
S_e003               db 101, 48, 48, 51, 0  ; "e003"
S_PASS_SP_913_integer_pred_SP_LP_3_SL_3_RP db 80, 65, 83, 83, 32, 57, 49, 51, 95, 105, 110, 116, 101, 103, 101, 114, 95, 112, 114, 101, 100, 32, 40, 51, 47, 51, 41, 0  ; "PASS 913_integer_pred (3/3)"
S_end                db 101, 110, 100, 0  ; "end"
