; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 4
                            call        comm_stno
                            CALL1_INT   S_array, 3
                            FAIL_BR     Ln_0
                            SET_VAR     S_a
                            jmp         Ln_0

; ======================================================================================================================
Ln_0:                       mov         edi, 7
                            call        comm_stno
                            sub         rsp, 16
                            lea         rdi, [rel S_a]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    1
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            APPLY_FN_N  S_differ, 1
                            add         rsp, 16
                            STORE_RESULT
                            FAIL_BR     Lf_1
                            jmp         Ln_1
Lf_1:                       jmp         L_e001_0

; ======================================================================================================================
Ln_1:                       mov         edi, 8
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1110_SL_001_CL_SP_array_SP_element_SP_init_SP_null
                            FAIL_BR     Lf_2
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_2:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_2:
;  e001 ================================================================================================================
L_e001_0:                   mov         edi, 9
                            call        comm_stno

; ======================================================================================================================
Ln_3:                       mov         edi, 12
                            call        comm_stno
                            GET_VAR     S_a
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_INT    2
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_REAL   F_1
                            FAIL_BR     Ln_4
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_4

; ======================================================================================================================
Ln_4:                       mov         edi, 13
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_a]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    2
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_REAL   F_1
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_5
                            jmp         Ln_5
Lf_5:                       jmp         L_e002_1

; ======================================================================================================================
Ln_5:                       mov         edi, 14
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1110_SL_002_CL_SP_array_SP_assign_SL_read
                            FAIL_BR     Lf_6
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_6:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_6:
;  e002 ================================================================================================================
L_e002_1:                   mov         edi, 15
                            call        comm_stno

; ======================================================================================================================
Ln_7:                       mov         edi, 18
                            call        comm_stno
                            lea         rdi, [rel S_a]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    4
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Lf_8
                            jmp         Ln_8
Lf_8:                       jmp         L_e003_2

; ======================================================================================================================
Ln_8:                       mov         edi, 19
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1110_SL_003_CL_SP_OOB_SP_high_SP_should_SP_fail
                            FAIL_BR     Lf_9
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_9:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_9:
;  e003 ================================================================================================================
L_e003_2:                   mov         edi, 20
                            call        comm_stno

; ======================================================================================================================
Ln_10:                      mov         edi, 23
                            call        comm_stno
                            lea         rdi, [rel S_a]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    0
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Lf_11
                            jmp         Ln_11
Lf_11:                      jmp         L_e004_3

; ======================================================================================================================
Ln_11:                      mov         edi, 24
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1110_SL_004_CL_SP_OOB_SP_zero_SP_should_SP_fail
                            FAIL_BR     Lf_12
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_12:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_12:
;  e004 ================================================================================================================
L_e004_3:                   mov         edi, 25
                            call        comm_stno

; ======================================================================================================================
Ln_13:                      mov         edi, 28
                            call        comm_stno
                            sub         rsp, 32
                            CALL1_VAR   S_prototype, S_a
                            STORE_ARG32 0
                            LOAD_STR    S_3
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_14
                            jmp         Ln_14
Lf_14:                      jmp         L_e005_4

; ======================================================================================================================
Ln_14:                      mov         edi, 29
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1110_SL_005_CL_SP_prototype_LP_array_LP_3_RP_RP_EQ_3
                            FAIL_BR     Lf_15
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_15:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_15:
;  e005 ================================================================================================================
L_e005_4:                   mov         edi, 30
                            call        comm_stno

; ======================================================================================================================
Ln_16:                      mov         edi, 33
                            call        comm_stno
                            CALL1_STR   S_array, S_3
                            FAIL_BR     Ln_17
                            SET_VAR     S_b
                            jmp         Ln_17

; ======================================================================================================================
Ln_17:                      mov         edi, 34
                            call        comm_stno
                            GET_VAR     S_b
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_INT    2
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_x
                            FAIL_BR     Ln_18
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_18

; ======================================================================================================================
Ln_18:                      mov         edi, 35
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_b]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    2
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_STR    S_x
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_19
                            jmp         Ln_19
Lf_19:                      jmp         L_e006_5

; ======================================================================================================================
Ln_19:                      mov         edi, 36
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1110_SL_006_CL_SP_array_SP_from_SP_string_SP_dim
                            FAIL_BR     Lf_20
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_20:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_20:
;  e006 ================================================================================================================
L_e006_5:                   mov         edi, 37
                            call        comm_stno

; ======================================================================================================================
Ln_21:                      mov         edi, 40
                            call        comm_stno
                            sub         rsp, 32
                            CALL1_VAR   S_prototype, S_b
                            STORE_ARG32 0
                            LOAD_STR    S_3
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_22
                            jmp         Ln_22
Lf_22:                      jmp         L_e007_6

; ======================================================================================================================
Ln_22:                      mov         edi, 41
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1110_SL_007_CL_SP_prototype_SP_string_MI_dim_SP_array
                            FAIL_BR     Lf_23
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_23:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_23:
;  e007 ================================================================================================================
L_e007_6:                   mov         edi, 42
                            call        comm_stno

; ======================================================================================================================
Ln_24:                      mov         edi, 45
                            call        comm_stno
                            GET_VAR     S_a
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_INT    1
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_REAL   F_2
                            FAIL_BR     Ln_25
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_25

; ======================================================================================================================
Ln_25:                      mov         edi, 46
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_a]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    1
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_REAL   F_2
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_26
                            jmp         Ln_26
Lf_26:                      jmp         L_e008_7

; ======================================================================================================================
Ln_26:                      mov         edi, 47
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1110_SL_008_CL_SP_array_SP_stores_SP_real
                            FAIL_BR     Lf_27
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_27:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_27:
;  e008 ================================================================================================================
L_e008_7:                   mov         edi, 48
                            call        comm_stno

; ======================================================================================================================
Ln_28:                      mov         edi, 51
                            call        comm_stno
                            GET_VAR     S_a
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_INT    3
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_z
                            FAIL_BR     Ln_29
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_29

; ======================================================================================================================
Ln_29:                      mov         edi, 52
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_a]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    3
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_STR    S_z
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_30
                            jmp         Ln_30
Lf_30:                      jmp         L_e009_8

; ======================================================================================================================
Ln_30:                      mov         edi, 53
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1110_SL_009_CL_SP_array_SP_stores_SP_string
                            FAIL_BR     Lf_31
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_31:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_31:
;  e009 ================================================================================================================
L_e009_8:                   mov         edi, 54
                            call        comm_stno

; ======================================================================================================================
Ln_32:                      mov         edi, 56
                            call        comm_stno
                            LOAD_STR    S_PASS_SP_1110_array_1d_SP_LP_9_SL_9_RP
                            FAIL_BR     Ln_33
                            SET_OUTPUT
                            jmp         Ln_33
Ln_33:                      GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_a                  db 97, 0  ; "a"
S_array              db 97, 114, 114, 97, 121, 0  ; "array"
S_differ             db 100, 105, 102, 102, 101, 114, 0  ; "differ"
S_output             db 111, 117, 116, 112, 117, 116, 0  ; "output"
S_FAIL_SP_1110_SL_001_CL_SP_array_SP_element_SP_init_SP_null db 70, 65, 73, 76, 32, 49, 49, 49, 48, 47, 48, 48, 49, 58, 32, 97, 114, 114, 97, 121, 32, 101, 108, 101, 109, 101, 110, 116, 32, 105, 110, 105, 116, 32, 110, 117, 108, 108, 0  ; "FAIL 1110/001: array element init null"
S_e001               db 101, 48, 48, 49, 0  ; "e001"
S_FAIL_SP_1110_SL_002_CL_SP_array_SP_assign_SL_read db 70, 65, 73, 76, 32, 49, 49, 49, 48, 47, 48, 48, 50, 58, 32, 97, 114, 114, 97, 121, 32, 97, 115, 115, 105, 103, 110, 47, 114, 101, 97, 100, 0  ; "FAIL 1110/002: array assign/read"
S_e002               db 101, 48, 48, 50, 0  ; "e002"
S_FAIL_SP_1110_SL_003_CL_SP_OOB_SP_high_SP_should_SP_fail db 70, 65, 73, 76, 32, 49, 49, 49, 48, 47, 48, 48, 51, 58, 32, 79, 79, 66, 32, 104, 105, 103, 104, 32, 115, 104, 111, 117, 108, 100, 32, 102, 97, 105, 108, 0  ; "FAIL 1110/003: OOB high should fail"
S_e003               db 101, 48, 48, 51, 0  ; "e003"
S_FAIL_SP_1110_SL_004_CL_SP_OOB_SP_zero_SP_should_SP_fail db 70, 65, 73, 76, 32, 49, 49, 49, 48, 47, 48, 48, 52, 58, 32, 79, 79, 66, 32, 122, 101, 114, 111, 32, 115, 104, 111, 117, 108, 100, 32, 102, 97, 105, 108, 0  ; "FAIL 1110/004: OOB zero should fail"
S_e004               db 101, 48, 48, 52, 0  ; "e004"
S_3                  db 51, 0  ; "3"
S_prototype          db 112, 114, 111, 116, 111, 116, 121, 112, 101, 0  ; "prototype"
S_FAIL_SP_1110_SL_005_CL_SP_prototype_LP_array_LP_3_RP_RP_EQ_3 db 70, 65, 73, 76, 32, 49, 49, 49, 48, 47, 48, 48, 53, 58, 32, 112, 114, 111, 116, 111, 116, 121, 112, 101, 40, 97, 114, 114, 97, 121, 40, 51, 41, 41, 61, 51, 0  ; "FAIL 1110/005: prototype(array(3))=3"
S_e005               db 101, 48, 48, 53, 0  ; "e005"
S_b                  db 98, 0  ; "b"
S_x                  db 120, 0  ; "x"
S_FAIL_SP_1110_SL_006_CL_SP_array_SP_from_SP_string_SP_dim db 70, 65, 73, 76, 32, 49, 49, 49, 48, 47, 48, 48, 54, 58, 32, 97, 114, 114, 97, 121, 32, 102, 114, 111, 109, 32, 115, 116, 114, 105, 110, 103, 32, 100, 105, 109, 0  ; "FAIL 1110/006: array from string dim"
S_e006               db 101, 48, 48, 54, 0  ; "e006"
S_FAIL_SP_1110_SL_007_CL_SP_prototype_SP_string_MI_dim_SP_array db 70, 65, 73, 76, 32, 49, 49, 49, 48, 47, 48, 48, 55, 58, 32, 112, 114, 111, 116, 111, 116, 121, 112, 101, 32, 115, 116, 114, 105, 110, 103, 45, 100, 105, 109, 32, 97, 114, 114, 97, 121, 0  ; "FAIL 1110/007: prototype string-dim array"
S_e007               db 101, 48, 48, 55, 0  ; "e007"
S_FAIL_SP_1110_SL_008_CL_SP_array_SP_stores_SP_real db 70, 65, 73, 76, 32, 49, 49, 49, 48, 47, 48, 48, 56, 58, 32, 97, 114, 114, 97, 121, 32, 115, 116, 111, 114, 101, 115, 32, 114, 101, 97, 108, 0  ; "FAIL 1110/008: array stores real"
S_e008               db 101, 48, 48, 56, 0  ; "e008"
S_z                  db 122, 0  ; "z"
S_FAIL_SP_1110_SL_009_CL_SP_array_SP_stores_SP_string db 70, 65, 73, 76, 32, 49, 49, 49, 48, 47, 48, 48, 57, 58, 32, 97, 114, 114, 97, 121, 32, 115, 116, 111, 114, 101, 115, 32, 115, 116, 114, 105, 110, 103, 0  ; "FAIL 1110/009: array stores string"
S_e009               db 101, 48, 48, 57, 0  ; "e009"
S_PASS_SP_1110_array_1d_SP_LP_9_SL_9_RP db 80, 65, 83, 83, 32, 49, 49, 49, 48, 95, 97, 114, 114, 97, 121, 95, 49, 100, 32, 40, 57, 47, 57, 41, 0  ; "PASS 1110_array_1d (9/9)"
S_end                db 101, 110, 100, 0  ; "end"
F_1                  dq 0x4012000000000000  ; 4.5
F_2                  dq 0x40091eb851eb851f  ; 3.14
