; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 4
                            call        comm_stno
                            CALL1_INT   S_table, 10
                            FAIL_BR     Ln_0
                            SET_VAR     S_t
                            jmp         Ln_0

; ======================================================================================================================
Ln_0:                       mov         edi, 7
                            call        comm_stno
                            sub         rsp, 16
                            lea         rdi, [rel S_t]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_cat
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            APPLY_FN_N  S_differ, 1
                            add         rsp, 16
                            STORE_RESULT
                            FAIL_BR     Lf_1
                            jmp         Ln_1
Lf_1:                       jmp         L_e001_0

; ======================================================================================================================
Ln_1:                       mov         edi, 8
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1113_SL_001_CL_SP_absent_SP_key_SP_is_SP_null
                            FAIL_BR     Lf_2
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_2:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_2:
;  e001 ================================================================================================================
L_e001_0:                   mov         edi, 9
                            call        comm_stno

; ======================================================================================================================
Ln_3:                       mov         edi, 12
                            call        comm_stno
                            GET_VAR     S_t
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_STR    S_cat
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_dog
                            FAIL_BR     Ln_4
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_4

; ======================================================================================================================
Ln_4:                       mov         edi, 13
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_t]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_cat
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_STR    S_dog
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_5
                            jmp         Ln_5
Lf_5:                       jmp         L_e002_1

; ======================================================================================================================
Ln_5:                       mov         edi, 14
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1113_SL_002_CL_SP_string_SP_key_SP_assign_SL_read
                            FAIL_BR     Lf_6
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_6:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_6:
;  e002 ================================================================================================================
L_e002_1:                   mov         edi, 15
                            call        comm_stno

; ======================================================================================================================
Ln_7:                       mov         edi, 18
                            call        comm_stno
                            GET_VAR     S_t
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_INT    7
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    45
                            FAIL_BR     Ln_8
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_8

; ======================================================================================================================
Ln_8:                       mov         edi, 19
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_t]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    7
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_INT    45
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_9
                            jmp         Ln_9
Lf_9:                       jmp         L_e003_2

; ======================================================================================================================
Ln_9:                       mov         edi, 20
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1113_SL_003_CL_SP_integer_SP_key_SP_assign_SL_read
                            FAIL_BR     Lf_10
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_10:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_10:
;  e003 ================================================================================================================
L_e003_2:                   mov         edi, 21
                            call        comm_stno

; ======================================================================================================================
Ln_11:                      mov         edi, 24
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_t]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_cat
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_STR    S_dog
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_12
                            jmp         Ln_12
Lf_12:                      jmp         L_e004_3

; ======================================================================================================================
Ln_12:                      mov         edi, 25
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1113_SL_004_CL_SP_string_SP_key_SP_survives_SP_int_SP_key_SP_add
                            FAIL_BR     Lf_13
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_13:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_13:
;  e004 ================================================================================================================
L_e004_3:                   mov         edi, 26
                            call        comm_stno

; ======================================================================================================================
Ln_14:                      mov         edi, 29
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_t]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_STR    S_array
                            STORE_ARG32 16
                            APPLY_FN_N  S_convert, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Ln_15
                            SET_VAR     S_ta
                            jmp         Ln_15

; ======================================================================================================================
Ln_15:                      mov         edi, 30
                            call        comm_stno
                            sub         rsp, 32
                            CALL1_VAR   S_prototype, S_ta
                            STORE_ARG32 0
                            LOAD_STR    S_2_CM_2
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_16
                            jmp         Ln_16
Lf_16:                      jmp         L_e005_4

; ======================================================================================================================
Ln_16:                      mov         edi, 31
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1113_SL_005_CL_SP_table_MI_GT_array_SP_prototype_SP_2_CM_2
                            FAIL_BR     Lf_17
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_17:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_17:
;  e005 ================================================================================================================
L_e005_4:                   mov         edi, 32
                            call        comm_stno

; ======================================================================================================================
Ln_18:                      mov         edi, 35
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_ta]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_STR    S_table
                            STORE_ARG32 16
                            APPLY_FN_N  S_convert, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Ln_19
                            SET_VAR     S_ata
                            jmp         Ln_19

; ======================================================================================================================
Ln_19:                      mov         edi, 36
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_ata]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    7
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_INT    45
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_20
                            jmp         Ln_20
Lf_20:                      jmp         L_e006_5

; ======================================================================================================================
Ln_20:                      mov         edi, 37
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1113_SL_006_CL_SP_array_MI_GT_table_SP_int_SP_key_SP_roundtrip
                            FAIL_BR     Lf_21
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_21:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_21:
;  e006 ================================================================================================================
L_e006_5:                   mov         edi, 38
                            call        comm_stno

; ======================================================================================================================
Ln_22:                      mov         edi, 41
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_ata]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_cat
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_STR    S_dog
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_23
                            jmp         Ln_23
Lf_23:                      jmp         L_e007_6

; ======================================================================================================================
Ln_23:                      mov         edi, 42
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1113_SL_007_CL_SP_array_MI_GT_table_SP_string_SP_key_SP_roundtrip
                            FAIL_BR     Lf_24
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_24:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_24:
;  e007 ================================================================================================================
L_e007_6:                   mov         edi, 43
                            call        comm_stno

; ======================================================================================================================
Ln_25:                      mov         edi, 46
                            call        comm_stno
                            GET_VAR     S_t
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_STR    S_cat
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_fish
                            FAIL_BR     Ln_26
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_26

; ======================================================================================================================
Ln_26:                      mov         edi, 47
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_t]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_cat
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_STR    S_fish
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_27
                            jmp         Ln_27
Lf_27:                      jmp         L_e008_7

; ======================================================================================================================
Ln_27:                      mov         edi, 48
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1113_SL_008_CL_SP_LB_RB_SP_and_SP_LT_GT_SP_syntax_SP_equivalent
                            FAIL_BR     Lf_28
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_28:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_28:
;  e008 ================================================================================================================
L_e008_7:                   mov         edi, 49
                            call        comm_stno

; ======================================================================================================================
Ln_29:                      mov         edi, 51
                            call        comm_stno
                            LOAD_STR    S_PASS_SP_1113_table_SP_LP_8_SL_8_RP
                            FAIL_BR     Ln_30
                            SET_OUTPUT
                            jmp         Ln_30
Ln_30:                      GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_t                  db 116, 0  ; "t"
S_table              db 116, 97, 98, 108, 101, 0  ; "table"
S_differ             db 100, 105, 102, 102, 101, 114, 0  ; "differ"
S_cat                db 99, 97, 116, 0  ; "cat"
S_output             db 111, 117, 116, 112, 117, 116, 0  ; "output"
S_FAIL_SP_1113_SL_001_CL_SP_absent_SP_key_SP_is_SP_null db 70, 65, 73, 76, 32, 49, 49, 49, 51, 47, 48, 48, 49, 58, 32, 97, 98, 115, 101, 110, 116, 32, 107, 101, 121, 32, 105, 115, 32, 110, 117, 108, 108, 0  ; "FAIL 1113/001: absent key is null"
S_e001               db 101, 48, 48, 49, 0  ; "e001"
S_dog                db 100, 111, 103, 0  ; "dog"
S_FAIL_SP_1113_SL_002_CL_SP_string_SP_key_SP_assign_SL_read db 70, 65, 73, 76, 32, 49, 49, 49, 51, 47, 48, 48, 50, 58, 32, 115, 116, 114, 105, 110, 103, 32, 107, 101, 121, 32, 97, 115, 115, 105, 103, 110, 47, 114, 101, 97, 100, 0  ; "FAIL 1113/002: string key assign/read"
S_e002               db 101, 48, 48, 50, 0  ; "e002"
S_FAIL_SP_1113_SL_003_CL_SP_integer_SP_key_SP_assign_SL_read db 70, 65, 73, 76, 32, 49, 49, 49, 51, 47, 48, 48, 51, 58, 32, 105, 110, 116, 101, 103, 101, 114, 32, 107, 101, 121, 32, 97, 115, 115, 105, 103, 110, 47, 114, 101, 97, 100, 0  ; "FAIL 1113/003: integer key assign/read"
S_e003               db 101, 48, 48, 51, 0  ; "e003"
S_FAIL_SP_1113_SL_004_CL_SP_string_SP_key_SP_survives_SP_int_SP_key_SP_add db 70, 65, 73, 76, 32, 49, 49, 49, 51, 47, 48, 48, 52, 58, 32, 115, 116, 114, 105, 110, 103, 32, 107, 101, 121, 32, 115, 117, 114, 118, 105, 118, 101, 115, 32, 105, 110, 116, 32, 107, 101, 121, 32, 97, 100, 100, 0  ; "FAIL 1113/004: string key survives int key add"
S_e004               db 101, 48, 48, 52, 0  ; "e004"
S_ta                 db 116, 97, 0  ; "ta"
S_convert            db 99, 111, 110, 118, 101, 114, 116, 0  ; "convert"
S_array              db 97, 114, 114, 97, 121, 0  ; "array"
S_2_CM_2             db 50, 44, 50, 0  ; "2,2"
S_prototype          db 112, 114, 111, 116, 111, 116, 121, 112, 101, 0  ; "prototype"
S_FAIL_SP_1113_SL_005_CL_SP_table_MI_GT_array_SP_prototype_SP_2_CM_2 db 70, 65, 73, 76, 32, 49, 49, 49, 51, 47, 48, 48, 53, 58, 32, 116, 97, 98, 108, 101, 45, 62, 97, 114, 114, 97, 121, 32, 112, 114, 111, 116, 111, 116, 121, 112, 101, 32, 50, 44, 50, 0  ; "FAIL 1113/005: table->array prototype 2,2"
S_e005               db 101, 48, 48, 53, 0  ; "e005"
S_ata                db 97, 116, 97, 0  ; "ata"
S_FAIL_SP_1113_SL_006_CL_SP_array_MI_GT_table_SP_int_SP_key_SP_roundtrip db 70, 65, 73, 76, 32, 49, 49, 49, 51, 47, 48, 48, 54, 58, 32, 97, 114, 114, 97, 121, 45, 62, 116, 97, 98, 108, 101, 32, 105, 110, 116, 32, 107, 101, 121, 32, 114, 111, 117, 110, 100, 116, 114, 105, 112, 0  ; "FAIL 1113/006: array->table int key roundtrip"
S_e006               db 101, 48, 48, 54, 0  ; "e006"
S_FAIL_SP_1113_SL_007_CL_SP_array_MI_GT_table_SP_string_SP_key_SP_roundtrip db 70, 65, 73, 76, 32, 49, 49, 49, 51, 47, 48, 48, 55, 58, 32, 97, 114, 114, 97, 121, 45, 62, 116, 97, 98, 108, 101, 32, 115, 116, 114, 105, 110, 103, 32, 107, 101, 121, 32, 114, 111, 117, 110, 100, 116, 114, 105, 112, 0  ; "FAIL 1113/007: array->table string key roundtrip"
S_e007               db 101, 48, 48, 55, 0  ; "e007"
S_fish               db 102, 105, 115, 104, 0  ; "fish"
S_FAIL_SP_1113_SL_008_CL_SP_LB_RB_SP_and_SP_LT_GT_SP_syntax_SP_equivalent db 70, 65, 73, 76, 32, 49, 49, 49, 51, 47, 48, 48, 56, 58, 32, 91, 93, 32, 97, 110, 100, 32, 60, 62, 32, 115, 121, 110, 116, 97, 120, 32, 101, 113, 117, 105, 118, 97, 108, 101, 110, 116, 0  ; "FAIL 1113/008: [] and <> syntax equivalent"
S_e008               db 101, 48, 48, 56, 0  ; "e008"
S_PASS_SP_1113_table_SP_LP_8_SL_8_RP db 80, 65, 83, 83, 32, 49, 49, 49, 51, 95, 116, 97, 98, 108, 101, 32, 40, 56, 47, 56, 41, 0  ; "PASS 1113_table (8/8)"
S_end                db 101, 110, 100, 0  ; "end"
