; Generated by scrip-cc -jvm
; Assemble: java -jar jasmin.jar <file>.j -d .
; Run:      java <classname>

.class public _113_table
.super java/lang/Object

; Runtime fields
.field static sno_stdout Ljava/io/PrintStream;
.field static sno_input_br Ljava/io/BufferedReader;
.field static sno_kw_TRIM I
.field static sno_kw_ANCHOR I
.field static sno_kw_STNO I
.field static sno_kw_STLIMIT I
.field static sno_kw_STCOUNT I
.field static sno_vars Ljava/util/HashMap;
.field static sno_arrays Ljava/util/HashMap;
.field static sno_data_types Ljava/util/HashMap;
.field static sno_mon_fd Ljava/io/OutputStream;
.field static sno_mon_go_fd Ljava/io/InputStream;
.field static sno_var_t Ljava/lang/String;
.field static sno_var_ta Ljava/lang/String;
.field static sno_var_ata Ljava/lang/String;

.method static <clinit>()V
    .limit stack 13
    .limit locals 0
    getstatic       java/lang/System/out Ljava/io/PrintStream;
    putstatic       _113_table/sno_stdout Ljava/io/PrintStream;
    iconst_0
    putstatic       _113_table/sno_kw_TRIM I
    iconst_0
    putstatic       _113_table/sno_kw_ANCHOR I
    iconst_0
    putstatic       _113_table/sno_kw_STNO I
    iconst_m1
    putstatic       _113_table/sno_kw_STLIMIT I
    iconst_0
    putstatic       _113_table/sno_kw_STCOUNT I
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    putstatic       _113_table/sno_vars Ljava/util/HashMap;
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    putstatic       _113_table/sno_arrays Ljava/util/HashMap;
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    putstatic       _113_table/sno_data_types Ljava/util/HashMap;
    ldc             ""
    putstatic       _113_table/sno_var_t Ljava/lang/String;
    getstatic       _113_table/sno_vars Ljava/util/HashMap;
    ldc             "t"
    ldc             ""
    invokevirtual   java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    ldc             ""
    putstatic       _113_table/sno_var_ta Ljava/lang/String;
    getstatic       _113_table/sno_vars Ljava/util/HashMap;
    ldc             "ta"
    ldc             ""
    invokevirtual   java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    ldc             ""
    putstatic       _113_table/sno_var_ata Ljava/lang/String;
    getstatic       _113_table/sno_vars Ljava/util/HashMap;
    ldc             "ata"
    ldc             ""
    invokevirtual   java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    return
.end method

.method static sno_mon_init()V
    .limit stack 6
    .limit locals 2
    ldc "MONITOR_READY_PIPE"
    invokestatic java/lang/System/getenv(Ljava/lang/String;)Ljava/lang/String;
    astore_0
    aload_0
    ifnull Lsmi_done
    aload_0
    invokevirtual java/lang/String/isEmpty()Z
    ifne Lsmi_done
    new java/io/FileOutputStream
    dup
    aload_0
    iconst_1
    invokespecial java/io/FileOutputStream/<init>(Ljava/lang/String;Z)V
    putstatic _113_table/sno_mon_fd Ljava/io/OutputStream;
    ldc "MONITOR_GO_PIPE"
    invokestatic java/lang/System/getenv(Ljava/lang/String;)Ljava/lang/String;
    astore_1
    aload_1
    ifnull Lsmi_done
    aload_1
    invokevirtual java/lang/String/isEmpty()Z
    ifne Lsmi_done
    new java/io/FileInputStream
    dup
    aload_1
    invokespecial java/io/FileInputStream/<init>(Ljava/lang/String;)V
    putstatic _113_table/sno_mon_go_fd Ljava/io/InputStream;
Lsmi_done:
    return
.end method

.method public static main([Ljava/lang/String;)V
    .limit stack 16
    .limit locals 32

    invokestatic _113_table/sno_mon_init()V
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    invokestatic _113_table/sno_table_new()Ljava/lang/String;
    dup
    ifnonnull Lvar_ok_0
    pop
    goto Lvar_fail_0
Lvar_ok_0:
    ldc "t"
    swap
    invokestatic _113_table/sno_var_put(Ljava/lang/String;Ljava/lang/String;)V
Lvar_fail_0:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "t"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "cat"
    invokestatic _113_table/sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Ldiff_n0_0
    pop
    ldc ""
Ldiff_n0_0:
    ldc ""
    invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
    ifne Ldiff_f_0
    ldc ""
    goto Ldiff_d_0
Ldiff_f_0:
    aconst_null
Ldiff_d_0:
    dup
    ifnonnull Lef_nn_0
    pop
    goto L_e001
Lef_nn_0:
    pop
Lef_dn_0:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "FAIL 1113/001: absent key is null"
    dup
    ifnonnull Lout_ok_0
    pop
    goto Lout_fail_0
Lout_ok_0:
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    goto L_END
Lout_fail_0:
    goto L_END
; === e001 ============================================================
L_e001:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "t"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "cat"
    ldc "dog"
    invokestatic _113_table/sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
; unhandled stmt form
    nop
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "t"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "cat"
    invokestatic _113_table/sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Ldiff_n0_1
    pop
    ldc ""
Ldiff_n0_1:
    ldc "dog"
    dup
    ifnonnull Ldiff_n1_1
    pop
    ldc ""
Ldiff_n1_1:
    invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
    ifne Ldiff_f_1
    ldc ""
    goto Ldiff_d_1
Ldiff_f_1:
    aconst_null
Ldiff_d_1:
    dup
    ifnonnull Lef_nn_1
    pop
    goto L_e002
Lef_nn_1:
    pop
Lef_dn_1:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "FAIL 1113/002: string key assign/read"
    dup
    ifnonnull Lout_ok_1
    pop
    goto Lout_fail_1
Lout_ok_1:
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    goto L_END
Lout_fail_1:
    goto L_END
; === e002 ============================================================
L_e002:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "t"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "7"
    ldc "45"
    invokestatic _113_table/sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
; unhandled stmt form
    nop
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "t"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "7"
    invokestatic _113_table/sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Ldiff_n0_2
    pop
    ldc ""
Ldiff_n0_2:
    ldc "45"
    dup
    ifnonnull Ldiff_n1_2
    pop
    ldc ""
Ldiff_n1_2:
    invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
    ifne Ldiff_f_2
    ldc ""
    goto Ldiff_d_2
Ldiff_f_2:
    aconst_null
Ldiff_d_2:
    dup
    ifnonnull Lef_nn_2
    pop
    goto L_e003
Lef_nn_2:
    pop
Lef_dn_2:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "FAIL 1113/003: integer key assign/read"
    dup
    ifnonnull Lout_ok_2
    pop
    goto Lout_fail_2
Lout_ok_2:
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    goto L_END
Lout_fail_2:
    goto L_END
; === e003 ============================================================
L_e003:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "t"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "cat"
    invokestatic _113_table/sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Ldiff_n0_3
    pop
    ldc ""
Ldiff_n0_3:
    ldc "dog"
    dup
    ifnonnull Ldiff_n1_3
    pop
    ldc ""
Ldiff_n1_3:
    invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
    ifne Ldiff_f_3
    ldc ""
    goto Ldiff_d_3
Ldiff_f_3:
    aconst_null
Ldiff_d_3:
    dup
    ifnonnull Lef_nn_3
    pop
    goto L_e004
Lef_nn_3:
    pop
Lef_dn_3:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "FAIL 1113/004: string key survives int key add"
    dup
    ifnonnull Lout_ok_3
    pop
    goto Lout_fail_3
Lout_ok_3:
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    goto L_END
Lout_fail_3:
    goto L_END
; === e004 ============================================================
L_e004:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "t"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    invokestatic _113_table/sno_convert_table(Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Lvar_ok_1
    pop
    goto Lvar_fail_1
Lvar_ok_1:
    ldc "ta"
    swap
    invokestatic _113_table/sno_var_put(Ljava/lang/String;Ljava/lang/String;)V
Lvar_fail_1:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "ta"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    invokestatic _113_table/sno_prototype(Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Ldiff_n0_4
    pop
    ldc ""
Ldiff_n0_4:
    ldc "2,2"
    dup
    ifnonnull Ldiff_n1_4
    pop
    ldc ""
Ldiff_n1_4:
    invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
    ifne Ldiff_f_4
    ldc ""
    goto Ldiff_d_4
Ldiff_f_4:
    aconst_null
Ldiff_d_4:
    dup
    ifnonnull Lef_nn_4
    pop
    goto L_e005
Lef_nn_4:
    pop
Lef_dn_4:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "FAIL 1113/005: table->array prototype 2,2"
    dup
    ifnonnull Lout_ok_4
    pop
    goto Lout_fail_4
Lout_ok_4:
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    goto L_END
Lout_fail_4:
    goto L_END
; === e005 ============================================================
L_e005:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "ta"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    invokestatic _113_table/sno_convert_table(Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Lvar_ok_2
    pop
    goto Lvar_fail_2
Lvar_ok_2:
    ldc "ata"
    swap
    invokestatic _113_table/sno_var_put(Ljava/lang/String;Ljava/lang/String;)V
Lvar_fail_2:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "ata"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "7"
    invokestatic _113_table/sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Ldiff_n0_5
    pop
    ldc ""
Ldiff_n0_5:
    ldc "45"
    dup
    ifnonnull Ldiff_n1_5
    pop
    ldc ""
Ldiff_n1_5:
    invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
    ifne Ldiff_f_5
    ldc ""
    goto Ldiff_d_5
Ldiff_f_5:
    aconst_null
Ldiff_d_5:
    dup
    ifnonnull Lef_nn_5
    pop
    goto L_e006
Lef_nn_5:
    pop
Lef_dn_5:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "FAIL 1113/006: array->table int key roundtrip"
    dup
    ifnonnull Lout_ok_5
    pop
    goto Lout_fail_5
Lout_ok_5:
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    goto L_END
Lout_fail_5:
    goto L_END
; === e006 ============================================================
L_e006:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "ata"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "cat"
    invokestatic _113_table/sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Ldiff_n0_6
    pop
    ldc ""
Ldiff_n0_6:
    ldc "dog"
    dup
    ifnonnull Ldiff_n1_6
    pop
    ldc ""
Ldiff_n1_6:
    invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
    ifne Ldiff_f_6
    ldc ""
    goto Ldiff_d_6
Ldiff_f_6:
    aconst_null
Ldiff_d_6:
    dup
    ifnonnull Lef_nn_6
    pop
    goto L_e007
Lef_nn_6:
    pop
Lef_dn_6:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "FAIL 1113/007: array->table string key roundtrip"
    dup
    ifnonnull Lout_ok_6
    pop
    goto Lout_fail_6
Lout_ok_6:
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    goto L_END
Lout_fail_6:
    goto L_END
; === e007 ============================================================
L_e007:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "t"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "cat"
    ldc "fish"
    invokestatic _113_table/sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
; unhandled stmt form
    nop
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "t"
    invokestatic _113_table/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "cat"
    invokestatic _113_table/sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Ldiff_n0_7
    pop
    ldc ""
Ldiff_n0_7:
    ldc "fish"
    dup
    ifnonnull Ldiff_n1_7
    pop
    ldc ""
Ldiff_n1_7:
    invokevirtual java/lang/String/equals(Ljava/lang/Object;)Z
    ifne Ldiff_f_7
    ldc ""
    goto Ldiff_d_7
Ldiff_f_7:
    aconst_null
Ldiff_d_7:
    dup
    ifnonnull Lef_nn_7
    pop
    goto L_e008
Lef_nn_7:
    pop
Lef_dn_7:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "FAIL 1113/008: [] and <> syntax equivalent"
    dup
    ifnonnull Lout_ok_7
    pop
    goto Lout_fail_7
Lout_ok_7:
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    goto L_END
Lout_fail_7:
    goto L_END
; === e008 ============================================================
L_e008:
    getstatic _113_table/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STNO I
    invokestatic _113_table/sno_stcount_tick()V
    ldc "PASS 1113_table (8/8)"
    dup
    ifnonnull Lout_ok_8
    pop
    goto Lout_fail_8
Lout_ok_8:
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
Lout_fail_8:
; === END =============================================================
L_END:
    nop
; program end
    return
.end method
.method static sno_str_eq(Ljava/lang/String;Ljava/lang/String;)Z
    .limit stack 4
    .limit locals 2
    aload_0
    ifnull Lstreq_false
    aload_1
    ifnull Lstreq_false
    aload_0
    aload_1
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ireturn
Lstreq_false:
    iconst_0
    ireturn
.end method

.method static sno_kw_get(Ljava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 3
    aload_0
    ldc "ALPHABET"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_alphabet
    new java/lang/StringBuilder
    dup
    invokespecial java/lang/StringBuilder/<init>()V
    astore_1
    iconst_0
    istore_2
Lkwg_alpha_loop:
    iload_2
    sipush 256
    if_icmpge Lkwg_alpha_done
    aload_1
    iload_2
    i2c
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    pop
    iinc 2 1
    goto Lkwg_alpha_loop
Lkwg_alpha_done:
    aload_1
    invokevirtual java/lang/StringBuilder/toString()Ljava/lang/String;
    areturn
Lkwg_not_alphabet:
    aload_0
    ldc "UCASE"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_ucase
    ldc "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    areturn
Lkwg_not_ucase:
    aload_0
    ldc "LCASE"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_lcase
    ldc "abcdefghijklmnopqrstuvwxyz"
    areturn
Lkwg_not_lcase:
    aload_0
    ldc "STNO"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_stno
    getstatic _113_table/sno_kw_STNO I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_stno:
    aload_0
    ldc "TRIM"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_trim
    getstatic _113_table/sno_kw_TRIM I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_trim:
    aload_0
    ldc "ANCHOR"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_anchor
    getstatic _113_table/sno_kw_ANCHOR I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_anchor:
    aload_0
    ldc "STLIMIT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_stlimit
    getstatic _113_table/sno_kw_STLIMIT I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_stlimit:
    aload_0
    ldc "STCOUNT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_stcount
    getstatic _113_table/sno_kw_STCOUNT I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_stcount:
    ldc ""
    areturn
.end method

.method static sno_kw_set(Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 4
    .limit locals 2
    aload_0
    ldc "TRIM"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_trim
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _113_table/sno_kw_TRIM I
    return
Lkws_not_trim:
    aload_0
    ldc "ANCHOR"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_anchor
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _113_table/sno_kw_ANCHOR I
    return
Lkws_not_anchor:
    aload_0
    ldc "STNO"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_stno
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _113_table/sno_kw_STNO I
    return
Lkws_not_stno:
    aload_0
    ldc "STLIMIT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_stlimit
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _113_table/sno_kw_STLIMIT I
    return
Lkws_not_stlimit:
    aload_0
    ldc "STCOUNT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_stcount
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _113_table/sno_kw_STCOUNT I
    return
Lkws_not_stcount:
    return
.end method

.method static sno_var_put(Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 4
    .limit locals 2
    aload_0
    ldc "OUTPUT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lsvp_not_output
    getstatic _113_table/sno_stdout Ljava/io/PrintStream;
    aload_1
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    return
Lsvp_not_output:
    getstatic _113_table/sno_vars Ljava/util/HashMap;
    aload_0
    aload_1
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    aload_0
    aload_1
    invokestatic _113_table/sno_mon_var(Ljava/lang/String;Ljava/lang/String;)V
    return
.end method

.method static sno_mon_var(Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 6
    .limit locals 3
    getstatic _113_table/sno_mon_fd Ljava/io/OutputStream;
    ifnull Lsmv_done
    new java/lang/StringBuilder
    dup
    invokespecial java/lang/StringBuilder/<init>()V
    ldc "VALUE"
    invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
    bipush 30
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    aload_0
    invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
    bipush 31
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    aload_1
    invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
    bipush 30
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    invokevirtual java/lang/StringBuilder/toString()Ljava/lang/String;
    ldc "UTF-8"
    invokevirtual java/lang/String/getBytes(Ljava/lang/String;)[B
    astore_2
    getstatic _113_table/sno_mon_fd Ljava/io/OutputStream;
    aload_2
    invokevirtual java/io/OutputStream/write([B)V
    getstatic _113_table/sno_mon_go_fd Ljava/io/InputStream;
    ifnull Lsmv_done
    getstatic _113_table/sno_mon_go_fd Ljava/io/InputStream;
    invokevirtual java/io/InputStream/read()I
    istore_2
    iload_2
    bipush 71
    if_icmpeq Lsmv_done
    iconst_0
    invokestatic SnoRuntime/sno_exit(I)V
Lsmv_done:
    return
.end method

.method static sno_stcount_tick()V
    .limit stack 4
    .limit locals 0
    getstatic _113_table/sno_kw_STCOUNT I
    iconst_1
    iadd
    putstatic _113_table/sno_kw_STCOUNT I
    getstatic _113_table/sno_kw_STLIMIT I
    iflt Lstick_ok
    getstatic _113_table/sno_kw_STCOUNT I
    getstatic _113_table/sno_kw_STLIMIT I
    if_icmple Lstick_ok
    getstatic java/lang/System/err Ljava/io/PrintStream;
    ldc "Termination: statement limit"
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    iconst_1
    invokestatic SnoRuntime/sno_exit(I)V
Lstick_ok:
    return
.end method

.method static sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 1
    getstatic _113_table/sno_vars Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/lang/String
    dup
    ifnonnull Lsig_done_indr
    pop
    ldc ""
Lsig_done_indr:
    areturn
.end method

.method static sno_indr_set(Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 4
    .limit locals 2
    getstatic _113_table/sno_vars Ljava/util/HashMap;
    aload_0
    aload_1
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    return
.end method

.method static sno_array_new(Ljava/lang/String;)Ljava/lang/String;
    .limit stack 6
    .limit locals 2
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    astore_1
    aload_1
    invokestatic java/lang/System/identityHashCode(Ljava/lang/Object;)I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    dup
    getstatic _113_table/sno_arrays Ljava/util/HashMap;
    swap
    aload_1
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    areturn
.end method

.method static sno_array_new2(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    .limit stack 8
    .limit locals 6
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    astore_2
    aload_2
    invokestatic java/lang/System/identityHashCode(Ljava/lang/Object;)I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    astore_3
    getstatic _113_table/sno_arrays Ljava/util/HashMap;
    aload_3
    aload_2
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    aload_0
    invokestatic java/lang/Double/parseDouble(Ljava/lang/String;)D
    d2i
    istore 4
    aload_1
    invokevirtual java/lang/String/isEmpty()Z
    ifne La2_done
    iconst_1
    istore 5
La2_loop:
    iload 5
    iload 4
    if_icmpgt La2_done
    aload_2
    iload 5
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    aload_1
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    iinc 5 1
    goto La2_loop
La2_done:
    aload_3
    areturn
.end method

.method static sno_table_new()Ljava/lang/String;
    .limit stack 6
    .limit locals 2
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    astore_0
    aload_0
    invokestatic java/lang/System/identityHashCode(Ljava/lang/Object;)I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    dup
    getstatic _113_table/sno_arrays Ljava/util/HashMap;
    swap
    aload_0
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    areturn
.end method

.method static sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 3
    getstatic _113_table/sno_arrays Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/util/HashMap
    astore_2
    aload_2
    ifnull Lag_null
    aload_2
    aload_1
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/lang/String
    areturn
Lag_null:
    aconst_null
    areturn
.end method

.method static sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 4
    .limit locals 4
    getstatic _113_table/sno_arrays Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/util/HashMap
    astore_3
    aload_3
    ifnull Lap_done
    aload_3
    aload_1
    aload_2
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
Lap_done:
    return
.end method

.method static sno_convert_table(Ljava/lang/String;)Ljava/lang/String;
    .limit stack 8
    .limit locals 8
    getstatic _113_table/sno_arrays Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/util/HashMap
    astore_1
    aload_1
    ifnonnull Lct_have_table
    ldc ""
    areturn
Lct_have_table:
    aload_1
    invokevirtual java/util/HashMap/size()I
    istore 4
    iload 4
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    ldc "2"
    invokestatic _113_table/sno_array_new2(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    astore 5
    aload_1
    invokevirtual java/util/HashMap/entrySet()Ljava/util/Set;
    invokeinterface java/util/Set/iterator()Ljava/util/Iterator; 1
    astore_3
    iconst_0
    istore 4
Lct_loop:
    aload_3
    invokeinterface java/util/Iterator/hasNext()Z 1
    ifeq Lct_done
    iinc 4 1
    aload_3
    invokeinterface java/util/Iterator/next()Ljava/lang/Object; 1
    checkcast java/util/Map$Entry
    astore 6
    aload 5
    iload 4
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    ldc ",1"
    invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;
    aload 6
    invokeinterface java/util/Map$Entry/getKey()Ljava/lang/Object; 1
    checkcast java/lang/String
    invokestatic _113_table/sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    aload 5
    iload 4
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    ldc ",2"
    invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;
    aload 6
    invokeinterface java/util/Map$Entry/getValue()Ljava/lang/Object; 1
    checkcast java/lang/String
    invokestatic _113_table/sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    goto Lct_loop
Lct_done:
    aload 5
    ldc "__nrows__"
    iload 4
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    invokestatic _113_table/sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    aload 5
    areturn
.end method

.method static sno_prototype(Ljava/lang/String;)Ljava/lang/String;
    .limit stack 6
    .limit locals 3
    aload_0
    ldc "__nrows__"
    invokestatic _113_table/sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    astore_1
    aload_1
    ifnull Lpt_1d
    aload_1
    ldc ",2"
    invokevirtual java/lang/String/concat(Ljava/lang/String;)Ljava/lang/String;
    areturn
Lpt_1d:
    getstatic _113_table/sno_arrays Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/util/HashMap
    astore_1
    aload_1
    ifnull Lpt_empty
    aload_1
    invokevirtual java/util/HashMap/size()I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lpt_empty:
    ldc "0"
    areturn
.end method

