; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 6
                            call        comm_stno
                            CALL1_STR   S_data, S_node_LP_val_CM_lson_CM_rson_RP

; ======================================================================================================================
Ln_0:                       mov         edi, 7
                            call        comm_stno
                            CALL1_STR   S_data, S_clunk_LP_value_CM_lson_RP

; ======================================================================================================================
Ln_1:                       mov         edi, 10
                            call        comm_stno
                            sub         rsp, 48
                            LOAD_STR    S_x
                            STORE_ARG32 0
                            LOAD_STR    S_y
                            STORE_ARG32 16
                            LOAD_STR    S_z
                            STORE_ARG32 32
                            APPLY_FN_N  S_node, 3
                            add         rsp, 48
                            STORE_RESULT
                            FAIL_BR     Ln_2
                            SET_VAR     S_a
                            jmp         Ln_2

; ======================================================================================================================
Ln_2:                       mov         edi, 11
                            call        comm_stno
                            APPLY_FN_0  S_node
                            STORE_RESULT
                            FAIL_BR     Ln_3
                            SET_VAR     S_b
                            jmp         Ln_3

; ======================================================================================================================
Ln_3:                       mov         edi, 12
                            call        comm_stno
                            GET_VAR     S_b
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            lea         rdi, [rel S_a]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_4
                            mov         rcx, [rbp-32]
                            mov         r8,  [rbp-24]
                            lea         rdx, [rel S_lson]
                            mov         rdi, [rsp]
                            mov         rsi, [rsp+8]
                            add         rsp, 16
                            call        stmt_field_set
                            jmp         Ln_4

; ======================================================================================================================
Ln_4:                       mov         edi, 13
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 16
                            CALL1_VAR   S_lson, S_b
                            STORE_ARG32 0
                            APPLY_FN_N  S_rson, 1
                            add         rsp, 16
                            STORE_RESULT
                            STORE_ARG32 0
                            LOAD_STR    S_z
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_5
                            jmp         Ln_5
Lf_5:                       jmp         L_e001_0

; ======================================================================================================================
Ln_5:                       mov         edi, 14
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1116_SL_001_CL_SP_node_DT_rson_SP_after_SP_clunk_SP_data_SP_def
                            FAIL_BR     Lf_6
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_6:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_6:
;  e001 ================================================================================================================
L_e001_0:                   mov         edi, 15
                            call        comm_stno

; ======================================================================================================================
Ln_7:                       mov         edi, 18
                            call        comm_stno
                            sub         rsp, 32
                            CALL1_STR   S_value, S_b
                            STORE_ARG32 0
                            lea         rdi, [rel S_b]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_8
                            jmp         Ln_8
Lf_8:                       jmp         L_e002_1

; ======================================================================================================================
Ln_8:                       mov         edi, 19
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1116_SL_002_CL_SP_value_LP_RP_SP_still_SP_works_SP_after_SP_clunk
                            FAIL_BR     Lf_9
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_9:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_9:
;  e002 ================================================================================================================
L_e002_1:                   mov         edi, 20
                            call        comm_stno

; ======================================================================================================================
Ln_10:                      mov         edi, 23
                            call        comm_stno
                            sub         rsp, 32
                            LOAD_STR    S_alpha
                            STORE_ARG32 0
                            LOAD_STR    S_beta
                            STORE_ARG32 16
                            APPLY_FN_N  S_clunk, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Ln_11
                            SET_VAR     S_c
                            jmp         Ln_11

; ======================================================================================================================
Ln_11:                      mov         edi, 24
                            call        comm_stno
                            sub         rsp, 32
                            CALL1_VAR   S_lson, S_c
                            STORE_ARG32 0
                            LOAD_STR    S_beta
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_12
                            jmp         Ln_12
Lf_12:                      jmp         L_e003_2

; ======================================================================================================================
Ln_12:                      mov         edi, 25
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1116_SL_003_CL_SP_clunk_DT_lson_SP_accessor
                            FAIL_BR     Lf_13
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_13:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_13:
;  e003 ================================================================================================================
L_e003_2:                   mov         edi, 26
                            call        comm_stno

; ======================================================================================================================
Ln_14:                      mov         edi, 28
                            call        comm_stno
                            LOAD_STR    S_PASS_SP_1116_data_overlap_SP_LP_3_SL_3_RP
                            FAIL_BR     Ln_15
                            SET_OUTPUT
                            jmp         Ln_15
Ln_15:                      GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_data               db 100, 97, 116, 97, 0  ; "data"
S_node_LP_val_CM_lson_CM_rson_RP db 110, 111, 100, 101, 40, 118, 97, 108, 44, 108, 115, 111, 110, 44, 114, 115, 111, 110, 41, 0  ; "node(val,lson,rson)"
S_clunk_LP_value_CM_lson_RP db 99, 108, 117, 110, 107, 40, 118, 97, 108, 117, 101, 44, 108, 115, 111, 110, 41, 0  ; "clunk(value,lson)"
S_a                  db 97, 0  ; "a"
S_node               db 110, 111, 100, 101, 0  ; "node"
S_z                  db 122, 0  ; "z"
S_y                  db 121, 0  ; "y"
S_x                  db 120, 0  ; "x"
S_b                  db 98, 0  ; "b"
S_lson               db 108, 115, 111, 110, 0  ; "lson"
S_differ             db 100, 105, 102, 102, 101, 114, 0  ; "differ"
S_rson               db 114, 115, 111, 110, 0  ; "rson"
S_output             db 111, 117, 116, 112, 117, 116, 0  ; "output"
S_FAIL_SP_1116_SL_001_CL_SP_node_DT_rson_SP_after_SP_clunk_SP_data_SP_def db 70, 65, 73, 76, 32, 49, 49, 49, 54, 47, 48, 48, 49, 58, 32, 110, 111, 100, 101, 46, 114, 115, 111, 110, 32, 97, 102, 116, 101, 114, 32, 99, 108, 117, 110, 107, 32, 100, 97, 116, 97, 32, 100, 101, 102, 0  ; "FAIL 1116/001: node.rson after clunk data def"
S_e001               db 101, 48, 48, 49, 0  ; "e001"
S_value              db 118, 97, 108, 117, 101, 0  ; "value"
S_FAIL_SP_1116_SL_002_CL_SP_value_LP_RP_SP_still_SP_works_SP_after_SP_clunk db 70, 65, 73, 76, 32, 49, 49, 49, 54, 47, 48, 48, 50, 58, 32, 118, 97, 108, 117, 101, 40, 41, 32, 115, 116, 105, 108, 108, 32, 119, 111, 114, 107, 115, 32, 97, 102, 116, 101, 114, 32, 99, 108, 117, 110, 107, 0  ; "FAIL 1116/002: value() still works after clunk"
S_e002               db 101, 48, 48, 50, 0  ; "e002"
S_c                  db 99, 0  ; "c"
S_clunk              db 99, 108, 117, 110, 107, 0  ; "clunk"
S_beta               db 98, 101, 116, 97, 0  ; "beta"
S_alpha              db 97, 108, 112, 104, 97, 0  ; "alpha"
S_FAIL_SP_1116_SL_003_CL_SP_clunk_DT_lson_SP_accessor db 70, 65, 73, 76, 32, 49, 49, 49, 54, 47, 48, 48, 51, 58, 32, 99, 108, 117, 110, 107, 46, 108, 115, 111, 110, 32, 97, 99, 99, 101, 115, 115, 111, 114, 0  ; "FAIL 1116/003: clunk.lson accessor"
S_e003               db 101, 48, 48, 51, 0  ; "e003"
S_PASS_SP_1116_data_overlap_SP_LP_3_SL_3_RP db 80, 65, 83, 83, 32, 49, 49, 49, 54, 95, 100, 97, 116, 97, 95, 111, 118, 101, 114, 108, 97, 112, 32, 40, 51, 47, 51, 41, 0  ; "PASS 1116_data_overlap (3/3)"
S_end                db 101, 110, 100, 0  ; "end"
