#include "sm_template_common.h"
#include "emit_sm.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_fence0(const SM_Instr * instr, FILE * out){ if (IS_X86_TEXT) { emit_sm_pat_fence0_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_noarg_push(out, "fence0()Lrt/SnoPat;"); if (IS_JS) fprintf(out, "rt.pat_fence(); ");  if (IS_WASM) fprintf(out, "          (call $sno_pat_fence)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_fence1(const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_fence1_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_pat_push(out, "fence1(Lrt/SnoPat;)Lrt/SnoPat;");  if (IS_WASM) fprintf(out, "          (call $sno_pat_fence)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_abort(const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_abort_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_noarg_push(out, "abort_()Lrt/SnoPat;"); if (IS_JS) fprintf(out, "rt.pat_abort(); ");  if (IS_WASM) fprintf(out, "          (call $sno_pat_abort)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_fail (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_fail_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_noarg_push(out, "fail_()Lrt/SnoPat;");  if (IS_JS) fprintf(out, "rt.pat_fail(); ");  if (IS_WASM) fprintf(out, "          (call $sno_pat_fail)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_succeed(const SM_Instr * instr, FILE * out){if (IS_X86_TEXT) { emit_sm_pat_succeed_dispatch(out, 0); return; }(void)instr; if (IS_JVM) jvm_pat_noarg_push(out, "succeed_()Lrt/SnoPat;");if (IS_JS) fprintf(out, "rt.pat_succeed(); ");if (IS_WASM) fprintf(out, "          (call $sno_pat_succeed)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_arbno (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_arbno_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_pat_push(out, "arbno(Lrt/SnoPat;)Lrt/SnoPat;");  if (IS_JS) fprintf(out, "rt.pat_arbno(); "); if (IS_WASM) fprintf(out, "          (call $sno_pat_arbno)\n"); }
