#include "sm_template_common.h"
#include "emit_sm.h"
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_len  (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_len_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_long_push(out, "len(J)Lrt/SnoPat;");   if (IS_JS) fprintf(out, "rt.pat_len(); ");   if (IS_WASM) fprintf(out, "          (call $sno_pat_len)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_pos  (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_pos_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_long_push(out, "pos(J)Lrt/SnoPat;");   if (IS_JS) fprintf(out, "rt.pat_pos(); ");   if (IS_WASM) fprintf(out, "          (call $sno_pat_pos)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_rpos (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_rpos_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_long_push(out, "rpos(J)Lrt/SnoPat;");  if (IS_JS) fprintf(out, "rt.pat_rpos(); ");  if (IS_WASM) fprintf(out, "          (call $sno_pat_rpos)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_tab  (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_tab_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_long_push(out, "tab(J)Lrt/SnoPat;");   if (IS_JS) fprintf(out, "rt.pat_tab(); ");   if (IS_WASM) fprintf(out, "          (call $sno_pat_tab)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_rtab (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_rtab_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_long_push(out, "rtab(J)Lrt/SnoPat;");  if (IS_JS) fprintf(out, "rt.pat_rtab(); ");  if (IS_WASM) fprintf(out, "          (call $sno_pat_rtab)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_rem  (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_rem_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_noarg_push(out, "rem()Lrt/SnoPat;");    if (IS_JS) fprintf(out, "rt.pat_rem(); ");   if (IS_WASM) fprintf(out, "          (call $sno_pat_rem)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_bal  (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_bal_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_noarg_push(out, "bal()Lrt/SnoPat;");    if (IS_JS) fprintf(out, "rt.pat_bal(); ");   if (IS_WASM) fprintf(out, "          (call $sno_pat_bal)\n"); }
/*----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------*/
void sm_pat_eps  (const SM_Instr * instr, FILE * out) { if (IS_X86_TEXT) { emit_sm_pat_eps_dispatch(out, 0); return; } (void)instr; if (IS_JVM) jvm_pat_noarg_push(out, "eps()Lrt/SnoPat;");    if (IS_JS) fprintf(out, "rt.pat_eps(); ");   if (IS_WASM) fprintf(out, "          (call $sno_pat_eps)\n"); }
