; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 2
                            call        comm_stno
                            sub         rsp, 32
                            LOAD_STR    S_abc
                            STORE_ARG32 0
                            LOAD_STR    S_xyz
                            STORE_ARG32 16
                            APPLY_FN_N  S_DIFFER, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_0
                            jmp         L_YES_0
Lf_0:                       jmp         L_NO_1

Ln_0:
;  YES =================================================================================================================
L_YES_0:                    mov         edi, 3
                            call        comm_stno
                            LOAD_STR    S_different
                            FAIL_BR     Ln_1
                            SET_OUTPUT
                            jmp         Ln_1

; ======================================================================================================================
Ln_1:                       mov         edi, 4
                            call        comm_stno
                            GOTO_ALWAYS L_SNO_END     ; END

Ln_2:
;  NO ==================================================================================================================
L_NO_1:                     mov         edi, 5
                            call        comm_stno
                            LOAD_STR    S_same
                            FAIL_BR     Ln_3
                            SET_OUTPUT
                            jmp         Ln_3
Ln_3:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_DIFFER             db 68, 73, 70, 70, 69, 82, 0  ; "DIFFER"
S_xyz                db 120, 121, 122, 0  ; "xyz"
S_abc                db 97, 98, 99, 0  ; "abc"
S_YES                db 89, 69, 83, 0  ; "YES"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_different          db 100, 105, 102, 102, 101, 114, 101, 110, 116, 0  ; "different"
S_NO                 db 78, 79, 0  ; "NO"
S_same               db 115, 97, 109, 101, 0  ; "same"
S_END                db 69, 78, 68, 0  ; "END"
