;; sno_runtime.wat — SNOBOL4 WASM scalar stack-machine runtime
;; Implements SM-level operations called from emitted $main functions.
;; Memory layout (32 pages = 2MB total):
;;   [0x000000..0x00FFFF]  value stack       (16-byte slots, STACK_BASE=0, 4096 slots)
;;   [0x010000..0x013FFF]  variable table    (512 slots × 32 bytes = 16KB, VAR_BASE=0x10000)
;;   [0x031000..0x031FFF]  runtime keywords  (INPUT @ 0x31000, OUTPUT @ 0x31010)
;;   [0x040000..0x04FFFF]  output buffer     (OUTPUT_BUF=0x40000, unused so far)
;;   [0x050000..0x05FFFF]  BB arena          (32-byte box slots, BOX_ARENA_BASE=0x50000)
;;   [0x080000..0x0FFFFF]  dynamic str heap  (bump alloc from STR_HEAP_BASE=0x80000, 512KB)
;;   [0x100000..0x1FFFFF]  emitter literals  (STR_DATA_BASE=0x100000 in emit_wasm.c, 1MB)
;; Stack slot layout (16 bytes): +0=tag(i32) +4=ival(i32) +8=len(i32) +12=pad(i32)
;; Type tags: 0=integer 1=string 2=real 3=null 4=fail
;; Authors: Claude Sonnet 4.6 (SN4-WASM-1), Claude Opus 4.7 (SN4-WASM-5 prep)

(module
  ;; imports MUST come before memory/globals in WASM
  (import "host" "write_line" (func $host_write_line (param i32 i32)))
  (import "host" "read_line"  (func $host_read_line  (param i32) (result i32)))

  (memory (export "memory") 32)

  ;; constants
  (global $TAG_INT   i32 (i32.const 0))
  (global $TAG_STR   i32 (i32.const 1))
  (global $TAG_REAL  i32 (i32.const 2))
  (global $TAG_NULL  i32 (i32.const 3))
  (global $TAG_FAIL  i32 (i32.const 4))
  (global $SLOT      i32 (i32.const 16))
  (global $VAR_SLOTS i32 (i32.const 512))
  (global $VAR_SZ    i32 (i32.const 32))

  ;; mutable globals
  (global $sp       (mut i32) (i32.const 0))        ;; stack pointer (byte offset, STACK_BASE=0)
  (global $str_ptr  (mut i32) (i32.const 0x80000))  ;; dynamic string heap bump ptr (above arena at 0x50000..0x5FFFF)
  (global $last_ok  (mut i32) (i32.const 1))        ;; last match result
  (global $stno     (mut i32) (i32.const 0))        ;; statement number
  (global $pop_tag  (mut i32) (i32.const 0))        ;; pop result staging
  (global $pop_ival (mut i32) (i32.const 0))
  (global $pop_len  (mut i32) (i32.const 0))

  ;; static keyword strings at known addresses
  (data (i32.const 0x31000) "INPUT")
  (data (i32.const 0x31010) "OUTPUT")
  ;; built-in names for $sno_call dispatch (each entry's address is the i32.const used in sno_call)
  (data (i32.const 0x31100) "LT")
  (data (i32.const 0x31103) "GT")
  (data (i32.const 0x31106) "EQ")
  (data (i32.const 0x31109) "NE")
  (data (i32.const 0x3110c) "GE")
  (data (i32.const 0x3110f) "LE")
  (data (i32.const 0x31112) "IDENT")
  (data (i32.const 0x31118) "DIFFER")

  ;; ── memory helpers ───────────────────────────────────────────────────────
  (func $memcpy (param $dst i32) (param $src i32) (param $len i32)
    (local $i i32)
    (local.set $i (i32.const 0))
    (block $B (loop $L
      (br_if $B (i32.ge_u (local.get $i) (local.get $len)))
      (i32.store8
        (i32.add (local.get $dst) (local.get $i))
        (i32.load8_u (i32.add (local.get $src) (local.get $i))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $L)
    ))
  )

  (func $str_eq (param $p1 i32) (param $l1 i32) (param $p2 i32) (param $l2 i32) (result i32)
    (local $i i32)
    (if (i32.ne (local.get $l1) (local.get $l2)) (then (return (i32.const 0))))
    (local.set $i (i32.const 0))
    (block $B (loop $L
      (br_if $B (i32.ge_u (local.get $i) (local.get $l1)))
      (if (i32.ne
            (i32.load8_u (i32.add (local.get $p1) (local.get $i)))
            (i32.load8_u (i32.add (local.get $p2) (local.get $i))))
        (then (return (i32.const 0))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $L)
    ))
    (i32.const 1)
  )

  (func $alloc_str (param $len i32) (result i32)
    (local $ptr i32)
    (local.set $ptr (global.get $str_ptr))
    (global.set $str_ptr (i32.add (local.get $ptr) (i32.add (local.get $len) (i32.const 1))))
    (local.get $ptr)
  )

  ;; int_to_str: write decimal of val (i32) into heap; return ptr,len
  (func $int_to_str (param $val i32) (result i32 i32)
    (local $ptr i32) (local $start i32) (local $end i32)
    (local $tmp i32) (local $neg i32) (local $v i32) (local $digit i32) (local $len i32)
    (local.set $ptr (global.get $str_ptr))
    (local.set $start (local.get $ptr))
    (local.set $neg (i32.const 0))
    (local.set $v (local.get $val))
    (if (i32.lt_s (local.get $v) (i32.const 0))
      (then
        (local.set $neg (i32.const 1))
        (local.set $v (i32.sub (i32.const 0) (local.get $v)))))
    (if (i32.eqz (local.get $v))
      (then
        (i32.store8 (local.get $ptr) (i32.const 48))
        (local.set $ptr (i32.add (local.get $ptr) (i32.const 1))))
      (else
        (block $B (loop $L
          (br_if $B (i32.eqz (local.get $v)))
          (local.set $digit (i32.rem_u (local.get $v) (i32.const 10)))
          (i32.store8 (local.get $ptr) (i32.add (local.get $digit) (i32.const 48)))
          (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))
          (local.set $v (i32.div_u (local.get $v) (i32.const 10)))
          (br $L)
        ))
        (if (local.get $neg)
          (then
            (i32.store8 (local.get $ptr) (i32.const 45))
            (local.set $ptr (i32.add (local.get $ptr) (i32.const 1)))))
        ;; reverse
        (local.set $end (i32.sub (local.get $ptr) (i32.const 1)))
        (local.set $tmp (local.get $start))
        (block $RB (loop $RL
          (br_if $RB (i32.ge_u (local.get $tmp) (local.get $end)))
          (local.set $digit (i32.load8_u (local.get $tmp)))
          (i32.store8 (local.get $tmp) (i32.load8_u (local.get $end)))
          (i32.store8 (local.get $end) (local.get $digit))
          (local.set $tmp (i32.add (local.get $tmp) (i32.const 1)))
          (local.set $end (i32.sub (local.get $end) (i32.const 1)))
          (br $RL)
        ))
      )
    )
    (local.set $len (i32.sub (local.get $ptr) (local.get $start)))
    (global.set $str_ptr (i32.add (local.get $ptr) (i32.const 1)))
    (local.get $start)
    (local.get $len)
  )

  ;; ── stack helpers ────────────────────────────────────────────────────────
  (func $push3 (param $tag i32) (param $ival i32) (param $len i32)
    (local $addr i32)
    (local.set $addr (global.get $sp))
    (i32.store                            (local.get $addr) (local.get $tag))
    (i32.store (i32.add (local.get $addr) (i32.const 4)) (local.get $ival))
    (i32.store (i32.add (local.get $addr) (i32.const 8)) (local.get $len))
    (i32.store (i32.add (local.get $addr) (i32.const 12)) (i32.const 0))
    (global.set $sp (i32.add (global.get $sp) (i32.const 16)))
  )

  (func $peek_tag  (result i32) (i32.load (i32.sub (global.get $sp) (i32.const 16))))
  (func $peek_ival (result i32) (i32.load (i32.add (i32.sub (global.get $sp) (i32.const 16)) (i32.const 4))))
  (func $peek_len  (result i32) (i32.load (i32.add (i32.sub (global.get $sp) (i32.const 16)) (i32.const 8))))

  (func $pop_slot
    (local $addr i32)
    (global.set $sp (i32.sub (global.get $sp) (i32.const 16)))
    (local.set $addr (global.get $sp))
    (global.set $pop_tag  (i32.load (local.get $addr)))
    (global.set $pop_ival (i32.load (i32.add (local.get $addr) (i32.const 4))))
    (global.set $pop_len  (i32.load (i32.add (local.get $addr) (i32.const 8))))
  )

  ;; coerce top-of-stack to string (ptr,len); does NOT pop
  (func $tos_to_str (result i32 i32)
    (local $tag i32) (local $ival i32) (local $len i32)
    (local.set $tag  (call $peek_tag))
    (local.set $ival (call $peek_ival))
    (local.set $len  (call $peek_len))
    (if (i32.eq (local.get $tag) (global.get $TAG_STR))
      (then (return (local.get $ival) (local.get $len))))
    (if (i32.eq (local.get $tag) (global.get $TAG_NULL))
      (then (return (i32.const 0) (i32.const 0))))
    (if (i32.eq (local.get $tag) (global.get $TAG_INT))
      (then (return (call $int_to_str (local.get $ival)))))
    (return (i32.const 0) (i32.const 0))
  )

  ;; ── variable table (open-address hash, 256 slots × 32 bytes) ─────────────
  ;; Slot layout: +0=name_ptr(4) +4=name_len(4) +8=tag(4) +12=ival(4) +16=len(4) +20=pad(12)
  (func $var_hash (param $ptr i32) (param $len i32) (result i32)
    (local $h i32) (local $i i32)
    (local.set $h (i32.const 5381))
    (local.set $i (i32.const 0))
    (block $B (loop $L
      (br_if $B (i32.ge_u (local.get $i) (local.get $len)))
      (local.set $h (i32.add
        (i32.add (i32.shl (local.get $h) (i32.const 5)) (local.get $h))
        (i32.load8_u (i32.add (local.get $ptr) (local.get $i)))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $L)
    ))
    (i32.rem_u (i32.and (local.get $h) (i32.const 0x7fffffff)) (i32.const 512))
  )

  (func $var_slot_addr (param $name_ptr i32) (param $name_len i32) (result i32)
    (local $h i32) (local $idx i32) (local $saddr i32) (local $snl i32) (local $snp i32)
    (local.set $h (call $var_hash (local.get $name_ptr) (local.get $name_len)))
    (local.set $idx (local.get $h))
    (block $found (loop $probe
      (local.set $saddr (i32.add (i32.const 0x10000) (i32.mul (local.get $idx) (i32.const 32))))
      (local.set $snl (i32.load (i32.add (local.get $saddr) (i32.const 4))))
      (br_if $found (i32.eqz (local.get $snl)))
      (local.set $snp (i32.load (local.get $saddr)))
      (br_if $found (call $str_eq
        (local.get $name_ptr) (local.get $name_len) (local.get $snp) (local.get $snl)))
      (local.set $idx (i32.rem_u (i32.add (local.get $idx) (i32.const 1)) (i32.const 512)))
      (br_if $probe (i32.ne (local.get $idx) (local.get $h)))
    ))
    (i32.add (i32.const 0x10000) (i32.mul (local.get $idx) (i32.const 32)))
  )

  ;; ── exported runtime functions ────────────────────────────────────────────
  (func $sno_init (export "sno_init")
    (local $i i32)
    (global.set $sp (i32.const 0))
    (global.set $str_ptr (i32.const 0x80000))
    (global.set $last_ok (i32.const 1))
    (global.set $stno (i32.const 0))
    (local.set $i (i32.const 0))
    (block $B (loop $L
      (br_if $B (i32.ge_u (local.get $i) (i32.const 0x4000)))
      (i32.store (i32.add (i32.const 0x10000) (local.get $i)) (i32.const 0))
      (local.set $i (i32.add (local.get $i) (i32.const 4)))
      (br $L)
    ))
  )

  (func $sno_finalize (export "sno_finalize"))

  (func $sno_push_int (export "sno_push_int") (param $v i32)
    (call $push3 (global.get $TAG_INT) (local.get $v) (i32.const 0))
  )

  (func $sno_push_str (export "sno_push_str") (param $ptr i32) (param $len i32)
    (call $push3 (global.get $TAG_STR) (local.get $ptr) (local.get $len))
  )

  (func $sno_push_real (export "sno_push_real") (param $v f64)
    (local $bits i64)
    (local.set $bits (i64.reinterpret_f64 (local.get $v)))
    (call $push3
      (global.get $TAG_REAL)
      (i32.wrap_i64 (local.get $bits))
      (i32.wrap_i64 (i64.shr_u (local.get $bits) (i64.const 32))))
  )

  (func $sno_push_null (export "sno_push_null")
    (call $push3 (global.get $TAG_NULL) (i32.const 0) (i32.const 0))
  )

  (func $sno_push_var (export "sno_push_var") (param $name_ptr i32) (param $name_len i32)
    (local $saddr i32) (local $snl i32) (local $tag i32) (local $ival i32) (local $len i32)
    (local.set $saddr (call $var_slot_addr (local.get $name_ptr) (local.get $name_len)))
    (local.set $snl (i32.load (i32.add (local.get $saddr) (i32.const 4))))
    (if (i32.eqz (local.get $snl))
      (then
        (call $push3 (global.get $TAG_STR) (i32.const 0) (i32.const 0))
        (return)))
    (local.set $tag  (i32.load (i32.add (local.get $saddr) (i32.const 8))))
    (local.set $ival (i32.load (i32.add (local.get $saddr) (i32.const 12))))
    (local.set $len  (i32.load (i32.add (local.get $saddr) (i32.const 16))))
    (call $push3 (local.get $tag) (local.get $ival) (local.get $len))
  )

  (func $sno_store_var (export "sno_store_var") (param $name_ptr i32) (param $name_len i32)
    (local $saddr i32) (local $tag i32) (local $ival i32) (local $len i32)
    (local $p i32) (local $l i32)
    (call $pop_slot)
    (local.set $tag  (global.get $pop_tag))
    (local.set $ival (global.get $pop_ival))
    (local.set $len  (global.get $pop_len))
    ;; check for OUTPUT (6 chars)
    (if (call $str_eq (local.get $name_ptr) (local.get $name_len) (i32.const 0x31010) (i32.const 6))
      (then
        (call $push3 (local.get $tag) (local.get $ival) (local.get $len))
        (call $tos_to_str)
        (local.set $l)
        (local.set $p)
        (global.set $sp (i32.sub (global.get $sp) (i32.const 16)))
        (call $host_write_line (local.get $p) (local.get $l))
        (return)))
    (local.set $saddr (call $var_slot_addr (local.get $name_ptr) (local.get $name_len)))
    (i32.store (local.get $saddr) (local.get $name_ptr))
    (i32.store (i32.add (local.get $saddr) (i32.const 4)) (local.get $name_len))
    (i32.store (i32.add (local.get $saddr) (i32.const 8)) (local.get $tag))
    (i32.store (i32.add (local.get $saddr) (i32.const 12)) (local.get $ival))
    (i32.store (i32.add (local.get $saddr) (i32.const 16)) (local.get $len))
  )

  (func $sno_pop_void (export "sno_pop_void")
    (global.set $sp (i32.sub (global.get $sp) (i32.const 16)))
  )

  (func $sno_concat (export "sno_concat")
    (local $tag1 i32) (local $ival1 i32) (local $len1 i32)
    (local $tag2 i32) (local $ival2 i32) (local $len2 i32)
    (local $p1 i32) (local $l1 i32) (local $p2 i32) (local $l2 i32)
    (local $dst i32) (local $total i32)
    (call $pop_slot)
    (local.set $tag2  (global.get $pop_tag))
    (local.set $ival2 (global.get $pop_ival))
    (local.set $len2  (global.get $pop_len))
    (call $pop_slot)
    (local.set $tag1  (global.get $pop_tag))
    (local.set $ival1 (global.get $pop_ival))
    (local.set $len1  (global.get $pop_len))
    (call $push3 (local.get $tag1) (local.get $ival1) (local.get $len1))
    (call $tos_to_str)
    (local.set $l1)
    (local.set $p1)
    (global.set $sp (i32.sub (global.get $sp) (i32.const 16)))
    (call $push3 (local.get $tag2) (local.get $ival2) (local.get $len2))
    (call $tos_to_str)
    (local.set $l2)
    (local.set $p2)
    (global.set $sp (i32.sub (global.get $sp) (i32.const 16)))
    (local.set $total (i32.add (local.get $l1) (local.get $l2)))
    (local.set $dst (call $alloc_str (local.get $total)))
    (call $memcpy (local.get $dst) (local.get $p1) (local.get $l1))
    (call $memcpy (i32.add (local.get $dst) (local.get $l1)) (local.get $p2) (local.get $l2))
    (call $push3 (global.get $TAG_STR) (local.get $dst) (local.get $total))
  )

  (func $sno_neg (export "sno_neg")
    (call $pop_slot)
    (if (i32.eq (global.get $pop_tag) (global.get $TAG_INT))
      (then
        (call $push3 (global.get $TAG_INT) (i32.sub (i32.const 0) (global.get $pop_ival)) (i32.const 0))
        (return)))
    (call $push3 (global.get $pop_tag) (global.get $pop_ival) (global.get $pop_len))
  )

  (func $sno_exp_op (export "sno_exp_op")
    (call $pop_slot) (call $pop_slot)
    (call $push3 (global.get $TAG_INT) (i32.const 0) (i32.const 0))
  )

  (func $sno_coerce_num (export "sno_coerce_num")
    (local $tag i32) (local $p i32) (local $l i32)
    (local $n i32) (local $neg i32) (local $i i32) (local $ch i32)
    (local.set $tag (call $peek_tag))
    (if (i32.eq (local.get $tag) (global.get $TAG_INT))  (then (return)))
    (if (i32.eq (local.get $tag) (global.get $TAG_REAL)) (then (return)))
    (local.set $p (call $peek_ival))
    (local.set $l (call $peek_len))
    (local.set $n (i32.const 0))
    (local.set $neg (i32.const 0))
    (local.set $i (i32.const 0))
    (if (i32.and (i32.gt_u (local.get $l) (i32.const 0))
                 (i32.eq (i32.load8_u (local.get $p)) (i32.const 45)))
      (then (local.set $neg (i32.const 1)) (local.set $i (i32.const 1))))
    (block $B (loop $L
      (br_if $B (i32.ge_u (local.get $i) (local.get $l)))
      (local.set $ch (i32.load8_u (i32.add (local.get $p) (local.get $i))))
      (br_if $B (i32.lt_u (local.get $ch) (i32.const 48)))
      (br_if $B (i32.gt_u (local.get $ch) (i32.const 57)))
      (local.set $n (i32.add (i32.mul (local.get $n) (i32.const 10)) (i32.sub (local.get $ch) (i32.const 48))))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $L)
    ))
    (if (i32.eq (local.get $i) (local.get $l))
      (then
        (if (local.get $neg) (then (local.set $n (i32.sub (i32.const 0) (local.get $n)))))
        (global.set $sp (i32.sub (global.get $sp) (i32.const 16)))
        (call $push3 (global.get $TAG_INT) (local.get $n) (i32.const 0))))
  )

  ;; arith: op 0=add 1=sub 2=mul 3=div 4=mod
  (func $sno_arith (export "sno_arith") (param $op i32)
    (local $v1 i32) (local $v2 i32) (local $r i32)
    (call $pop_slot) (local.set $v2 (global.get $pop_ival))
    (call $pop_slot) (local.set $v1 (global.get $pop_ival))
    (local.set $r (i32.const 0))
    (if (i32.eq (local.get $op) (i32.const 0))
      (then (local.set $r (i32.add (local.get $v1) (local.get $v2))))
    (else (if (i32.eq (local.get $op) (i32.const 1))
      (then (local.set $r (i32.sub (local.get $v1) (local.get $v2))))
    (else (if (i32.eq (local.get $op) (i32.const 2))
      (then (local.set $r (i32.mul (local.get $v1) (local.get $v2))))
    (else (if (i32.eq (local.get $op) (i32.const 3))
      (then
        (if (i32.eqz (local.get $v2))
          (then (local.set $r (i32.const 0)))
          (else (local.set $r (i32.div_s (local.get $v1) (local.get $v2))))))
    (else
      (if (i32.eqz (local.get $v2))
        (then (local.set $r (i32.const 0)))
        (else (local.set $r (i32.rem_s (local.get $v1) (local.get $v2)))))))))))))
    (call $push3 (global.get $TAG_INT) (local.get $r) (i32.const 0))
  )

  ;; acomp: op 0=eq 1=ne 2=lt 3=le 4=gt 5=ge
  (func $sno_acomp (export "sno_acomp") (param $op i32)
    (local $v1 i32) (local $v2 i32) (local $ok i32)
    (call $pop_slot) (local.set $v2 (global.get $pop_ival))
    (call $pop_slot) (local.set $v1 (global.get $pop_ival))
    (local.set $ok (i32.const 0))
    (if (i32.eq (local.get $op) (i32.const 0)) (then (local.set $ok (i32.eq  (local.get $v1) (local.get $v2))))
    (else (if (i32.eq (local.get $op) (i32.const 1)) (then (local.set $ok (i32.ne  (local.get $v1) (local.get $v2))))
    (else (if (i32.eq (local.get $op) (i32.const 2)) (then (local.set $ok (i32.lt_s (local.get $v1) (local.get $v2))))
    (else (if (i32.eq (local.get $op) (i32.const 3)) (then (local.set $ok (i32.le_s (local.get $v1) (local.get $v2))))
    (else (if (i32.eq (local.get $op) (i32.const 4)) (then (local.set $ok (i32.gt_s (local.get $v1) (local.get $v2))))
    (else (local.set $ok (i32.ge_s (local.get $v1) (local.get $v2)))))))))))))
    (global.set $last_ok (local.get $ok))
    (if (local.get $ok)
      (then (call $push3 (global.get $TAG_INT) (local.get $v1) (i32.const 0)))
      (else (call $push3 (global.get $TAG_FAIL) (i32.const 0) (i32.const 0))))
  )

  ;; lcomp: lexicographic string comparison; op same as acomp
  (func $sno_lcomp (export "sno_lcomp") (param $op i32)
    (local $p1 i32) (local $l1 i32) (local $p2 i32) (local $l2 i32)
    (local $i i32) (local $c1 i32) (local $c2 i32) (local $cmp i32) (local $ok i32)
    (call $pop_slot)
    (local.set $p2 (global.get $pop_ival)) (local.set $l2 (global.get $pop_len))
    (call $pop_slot)
    (local.set $p1 (global.get $pop_ival)) (local.set $l1 (global.get $pop_len))
    (local.set $i (i32.const 0)) (local.set $cmp (i32.const 0))
    (block $done (loop $lp
      (if (i32.ge_u (local.get $i) (local.get $l1))
        (then
          (if (i32.lt_u (local.get $i) (local.get $l2)) (then (local.set $cmp (i32.const -1))))
          (br $done)))
      (if (i32.ge_u (local.get $i) (local.get $l2))
        (then (local.set $cmp (i32.const 1)) (br $done)))
      (local.set $c1 (i32.load8_u (i32.add (local.get $p1) (local.get $i))))
      (local.set $c2 (i32.load8_u (i32.add (local.get $p2) (local.get $i))))
      (if (i32.ne (local.get $c1) (local.get $c2))
        (then
          (if (i32.lt_u (local.get $c1) (local.get $c2))
            (then (local.set $cmp (i32.const -1)))
            (else (local.set $cmp (i32.const 1))))
          (br $done)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $lp)
    ))
    (local.set $ok (i32.const 0))
    (if (i32.eq (local.get $op) (i32.const 0))
      (then (local.set $ok (i32.eqz (local.get $cmp))))
      (else (if (i32.eq (local.get $op) (i32.const 1))
        (then (local.set $ok (i32.ne (local.get $cmp) (i32.const 0))))
        (else (if (i32.eq (local.get $op) (i32.const 2))
          (then (local.set $ok (i32.lt_s (local.get $cmp) (i32.const 0))))
          (else (if (i32.eq (local.get $op) (i32.const 3))
            (then (local.set $ok (i32.le_s (local.get $cmp) (i32.const 0))))
            (else (if (i32.eq (local.get $op) (i32.const 4))
              (then (local.set $ok (i32.gt_s (local.get $cmp) (i32.const 0))))
              (else (local.set $ok (i32.ge_s (local.get $cmp) (i32.const 0))))
            ))
          ))
        ))
      ))
    )
    (global.set $last_ok (local.get $ok))
    (if (local.get $ok)
      (then (call $push3 (global.get $TAG_STR) (local.get $p1) (local.get $l1)))
      (else (call $push3 (global.get $TAG_FAIL) (i32.const 0) (i32.const 0))))
  )

    (func $sno_last_ok     (export "sno_last_ok") (result i32) (global.get $last_ok))
  (func $sno_set_last_ok (export "sno_set_last_ok") (param $v i32) (global.set $last_ok (local.get $v)))
  (func $sno_set_stno    (export "sno_set_stno") (param $v i32) (global.set $stno (local.get $v)))

  (func $sno_halt_tos (export "sno_halt_tos")
    (local $tag i32) (local $p i32) (local $l i32)
    (if (i32.le_s (global.get $sp) (i32.const 0)) (then (return)))
    (local.set $tag (call $peek_tag))
    (if (i32.eq (local.get $tag) (global.get $TAG_FAIL)) (then (return)))
    (if (i32.eq (local.get $tag) (global.get $TAG_NULL)) (then (return)))
    (call $tos_to_str)
    (local.set $l)
    (local.set $p)
    (call $host_write_line (local.get $p) (local.get $l))
    (global.set $sp (i32.sub (global.get $sp) (i32.const 16)))
  )

  ;; sno_call: dispatch by builtin name; for now handle the numeric comparators
  ;; LT/GT/EQ/NE/GE/LE (each takes 2 numeric args) and IDENT/DIFFER (2 args, any type).
  ;; Success → push "" (TAG_STR len=0) and set last_ok=1; Failure → push null and set last_ok=0.
  ;; Unknown builtin → pops nargs, pushes null (legacy stub behavior, last_ok unchanged).
  (func $sno_call (export "sno_call") (param $name_ptr i32) (param $name_len i32) (param $nargs i32)
    (local $i i32)
    (local $a_tag i32) (local $a_ival i32) (local $a_len i32) (local $a_off i32)
    (local $b_tag i32) (local $b_ival i32) (local $b_len i32) (local $b_off i32)
    (local $cmp i32) (local $ok i32) (local $matched i32)
    (local.set $matched (i32.const 0))
    ;; If exactly 2 args, peek both. b is TOS, a is TOS-1.
    (if (i32.eq (local.get $nargs) (i32.const 2))
      (then
        (local.set $b_off (i32.sub (global.get $sp) (i32.const 16)))
        (local.set $a_off (i32.sub (global.get $sp) (i32.const 32)))
        (local.set $b_tag  (i32.load (local.get $b_off)))
        (local.set $b_ival (i32.load (i32.add (local.get $b_off) (i32.const 4))))
        (local.set $b_len  (i32.load (i32.add (local.get $b_off) (i32.const 8))))
        (local.set $a_tag  (i32.load (local.get $a_off)))
        (local.set $a_ival (i32.load (i32.add (local.get $a_off) (i32.const 4))))
        (local.set $a_len  (i32.load (i32.add (local.get $a_off) (i32.const 8))))
        ;; LT(a,b) ─ succeed iff a<b
        (if (call $str_eq (local.get $name_ptr) (local.get $name_len) (i32.const 0x31100) (i32.const 2))
          (then (local.set $matched (i32.const 1))
                (local.set $ok (i32.lt_s (local.get $a_ival) (local.get $b_ival)))))
        (if (call $str_eq (local.get $name_ptr) (local.get $name_len) (i32.const 0x31103) (i32.const 2))
          (then (local.set $matched (i32.const 1))
                (local.set $ok (i32.gt_s (local.get $a_ival) (local.get $b_ival)))))
        (if (call $str_eq (local.get $name_ptr) (local.get $name_len) (i32.const 0x31106) (i32.const 2))
          (then (local.set $matched (i32.const 1))
                (local.set $ok (i32.eq (local.get $a_ival) (local.get $b_ival)))))
        (if (call $str_eq (local.get $name_ptr) (local.get $name_len) (i32.const 0x31109) (i32.const 2))
          (then (local.set $matched (i32.const 1))
                (local.set $ok (i32.ne (local.get $a_ival) (local.get $b_ival)))))
        (if (call $str_eq (local.get $name_ptr) (local.get $name_len) (i32.const 0x3110c) (i32.const 2))
          (then (local.set $matched (i32.const 1))
                (local.set $ok (i32.ge_s (local.get $a_ival) (local.get $b_ival)))))
        (if (call $str_eq (local.get $name_ptr) (local.get $name_len) (i32.const 0x3110f) (i32.const 2))
          (then (local.set $matched (i32.const 1))
                (local.set $ok (i32.le_s (local.get $a_ival) (local.get $b_ival)))))
        ;; IDENT(a,b) ─ succeed iff a===b (same type and value).  For ints/reals use ival; for strings use byte-eq.
        (if (call $str_eq (local.get $name_ptr) (local.get $name_len) (i32.const 0x31112) (i32.const 5))
          (then
            (local.set $matched (i32.const 1))
            (local.set $ok (i32.const 0))
            (if (i32.eq (local.get $a_tag) (local.get $b_tag))
              (then
                (if (i32.eq (local.get $a_tag) (global.get $TAG_STR))
                  (then (local.set $ok
                         (call $str_eq (local.get $a_ival) (local.get $a_len)
                                       (local.get $b_ival) (local.get $b_len))))
                  (else (local.set $ok (i32.eq (local.get $a_ival) (local.get $b_ival)))))))))
        ;; DIFFER(a,b) ─ succeed iff !IDENT(a,b)
        (if (call $str_eq (local.get $name_ptr) (local.get $name_len) (i32.const 0x31118) (i32.const 6))
          (then
            (local.set $matched (i32.const 1))
            (local.set $ok (i32.const 1))
            (if (i32.eq (local.get $a_tag) (local.get $b_tag))
              (then
                (if (i32.eq (local.get $a_tag) (global.get $TAG_STR))
                  (then (local.set $ok
                         (i32.eqz (call $str_eq (local.get $a_ival) (local.get $a_len)
                                                (local.get $b_ival) (local.get $b_len)))))
                  (else (local.set $ok (i32.ne (local.get $a_ival) (local.get $b_ival)))))))))
        (if (local.get $matched)
          (then
            ;; pop both args, push result, set last_ok
            (global.set $sp (i32.sub (global.get $sp) (i32.const 32)))
            (if (local.get $ok)
              (then
                (call $push3 (global.get $TAG_STR) (i32.const 0) (i32.const 0))
                (global.set $last_ok (i32.const 1)))
              (else
                (call $push3 (global.get $TAG_NULL) (i32.const 0) (i32.const 0))
                (global.set $last_ok (i32.const 0))))
            (return)))))
    ;; Fallback stub: pop nargs, push null, leave last_ok unchanged.
    (local.set $i (i32.const 0))
    (block $B (loop $L
      (br_if $B (i32.ge_u (local.get $i) (local.get $nargs)))
      (global.set $sp (i32.sub (global.get $sp) (i32.const 16)))
      (local.set $i (i32.add (local.get $i) (i32.const 1)))
      (br $L)
    ))
    (call $push3 (global.get $TAG_NULL) (i32.const 0) (i32.const 0))
  )

  (func $sno_do_return (export "sno_do_return") (param $kind i32) (param $cond i32))
)
