; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 4
                            call        comm_stno
                            ASSIGN_STR  S_bal, S_the_SP_real_SP_bal, Ln_0
                            jmp         Ln_0

; ======================================================================================================================
Ln_0:                       mov         edi, 7
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 16
                            LOAD_STR    S_bal
                            mov         rdi, [rbp-32]
                            mov         rsi, [rbp-24]
                            call        stmt_get_indirect
                            add         rsp, 16
                            STORE_RESULT
                            STORE_ARG32 0
                            lea         rdi, [rel S_bal]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_1
                            jmp         Ln_1
Lf_1:                       jmp         L_e001_0

; ======================================================================================================================
Ln_1:                       mov         edi, 8
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_210_SL_001_CL_SP_DL_string_SP_lookup
                            FAIL_BR     Lf_2
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_2:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_2:
;  e001 ================================================================================================================
L_e001_0:                   mov         edi, 9
                            call        comm_stno

; ======================================================================================================================
Ln_3:                       mov         edi, 12
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 16
                            mov         qword [rbp-32], 9
                            lea         rax, [rel S_bal]
                            mov         [rbp-24], rax
                            mov         rdi, [rbp-32]
                            mov         rsi, [rbp-24]
                            call        stmt_get_indirect
                            add         rsp, 16
                            STORE_RESULT
                            STORE_ARG32 0
                            lea         rdi, [rel S_bal]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_4
                            jmp         Ln_4
Lf_4:                       jmp         L_e002_1

; ======================================================================================================================
Ln_4:                       mov         edi, 13
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_210_SL_002_CL_SP_DL_DT_var_SP_lookup
                            FAIL_BR     Lf_5
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_5:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_5:
;  e002 ================================================================================================================
L_e002_1:                   mov         edi, 14
                            call        comm_stno

; ======================================================================================================================
Ln_6:                       mov         edi, 16
                            call        comm_stno
                            LOAD_STR    S_PASS_SP_210_indirect_ref_SP_LP_2_SL_2_RP
                            FAIL_BR     Ln_7
                            SET_OUTPUT
                            jmp         Ln_7
Ln_7:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_bal                db 98, 97, 108, 0  ; "bal"
S_the_SP_real_SP_bal db 116, 104, 101, 32, 114, 101, 97, 108, 32, 98, 97, 108, 0  ; "the real bal"
S_differ             db 100, 105, 102, 102, 101, 114, 0  ; "differ"
S_output             db 111, 117, 116, 112, 117, 116, 0  ; "output"
S_FAIL_SP_210_SL_001_CL_SP_DL_string_SP_lookup db 70, 65, 73, 76, 32, 50, 49, 48, 47, 48, 48, 49, 58, 32, 36, 115, 116, 114, 105, 110, 103, 32, 108, 111, 111, 107, 117, 112, 0  ; "FAIL 210/001: $string lookup"
S_e001               db 101, 48, 48, 49, 0  ; "e001"
S_FAIL_SP_210_SL_002_CL_SP_DL_DT_var_SP_lookup db 70, 65, 73, 76, 32, 50, 49, 48, 47, 48, 48, 50, 58, 32, 36, 46, 118, 97, 114, 32, 108, 111, 111, 107, 117, 112, 0  ; "FAIL 210/002: $.var lookup"
S_e002               db 101, 48, 48, 50, 0  ; "e002"
S_PASS_SP_210_indirect_ref_SP_LP_2_SL_2_RP db 80, 65, 83, 83, 32, 50, 49, 48, 95, 105, 110, 100, 105, 114, 101, 99, 116, 95, 114, 101, 102, 32, 40, 50, 47, 50, 41, 0  ; "PASS 210_indirect_ref (2/2)"
S_end                db 101, 110, 100, 0  ; "end"
