; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 2
                            call        comm_stno
                            CALL1_INT   S_ARRAY, 5
                            FAIL_BR     Ln_0
                            SET_VAR     S_A
                            jmp         Ln_0

; ======================================================================================================================
Ln_0:                       mov         edi, 3
                            call        comm_stno
                            GET_VAR     S_A
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_INT    1
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_first
                            FAIL_BR     Ln_1
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_1

; ======================================================================================================================
Ln_1:                       mov         edi, 4
                            call        comm_stno
                            GET_VAR     S_A
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_INT    3
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_third
                            FAIL_BR     Ln_2
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_2

; ======================================================================================================================
Ln_2:                       mov         edi, 5
                            call        comm_stno
                            GET_VAR     S_A
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            LOAD_INT    5
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_STR    S_fifth
                            FAIL_BR     Ln_3
                            mov         r8,  [rbp-32]
                            mov         r9,  [rbp-24]
                            mov         rdx, [rsp]
                            mov         rcx, [rsp+8]
                            mov         rdi, [rsp+16]
                            mov         rsi, [rsp+24]
                            add         rsp, 32
                            call        stmt_aset
                            jmp         Ln_3

; ======================================================================================================================
Ln_3:                       mov         edi, 6
                            call        comm_stno
                            lea         rdi, [rel S_A]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    1
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_4
                            SET_OUTPUT
                            jmp         Ln_4

; ======================================================================================================================
Ln_4:                       mov         edi, 7
                            call        comm_stno
                            lea         rdi, [rel S_A]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    3
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_5
                            SET_OUTPUT
                            jmp         Ln_5

; ======================================================================================================================
Ln_5:                       mov         edi, 8
                            call        comm_stno
                            lea         rdi, [rel S_A]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            push        qword [rbp-24]
                            push        qword [rbp-32]
                            LOAD_INT    5
                            mov         rdx, [rbp-32]
                            mov         rcx, [rbp-24]
                            pop         rdi
                            pop         rsi
                            call        stmt_aref
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_6
                            SET_OUTPUT
                            jmp         Ln_6
Ln_6:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_A                  db 65, 0  ; "A"
S_ARRAY              db 65, 82, 82, 65, 89, 0  ; "ARRAY"
S_first              db 102, 105, 114, 115, 116, 0  ; "first"
S_third              db 116, 104, 105, 114, 100, 0  ; "third"
S_fifth              db 102, 105, 102, 116, 104, 0  ; "fifth"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_END                db 69, 78, 68, 0  ; "END"
