; Generated by scrip-cc -jvm
; Assemble: java -jar jasmin.jar <file>.j -d .
; Run:      java <classname>

.class public _94_data_define_access
.super java/lang/Object

; Runtime fields
.field static sno_stdout Ljava/io/PrintStream;
.field static sno_input_br Ljava/io/BufferedReader;
.field static sno_kw_TRIM I
.field static sno_kw_ANCHOR I
.field static sno_kw_STNO I
.field static sno_kw_STLIMIT I
.field static sno_kw_STCOUNT I
.field static sno_vars Ljava/util/HashMap;
.field static sno_arrays Ljava/util/HashMap;
.field static sno_data_types Ljava/util/HashMap;
.field static sno_mon_fd Ljava/io/OutputStream;
.field static sno_mon_go_fd Ljava/io/InputStream;
.field static sno_var_X Ljava/lang/String;

.method static <clinit>()V
    .limit stack 7
    .limit locals 0
    getstatic       java/lang/System/out Ljava/io/PrintStream;
    putstatic       _94_data_define_access/sno_stdout Ljava/io/PrintStream;
    iconst_0
    putstatic       _94_data_define_access/sno_kw_TRIM I
    iconst_0
    putstatic       _94_data_define_access/sno_kw_ANCHOR I
    iconst_0
    putstatic       _94_data_define_access/sno_kw_STNO I
    iconst_m1
    putstatic       _94_data_define_access/sno_kw_STLIMIT I
    iconst_0
    putstatic       _94_data_define_access/sno_kw_STCOUNT I
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    putstatic       _94_data_define_access/sno_vars Ljava/util/HashMap;
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    putstatic       _94_data_define_access/sno_arrays Ljava/util/HashMap;
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    putstatic       _94_data_define_access/sno_data_types Ljava/util/HashMap;
    ldc             ""
    putstatic       _94_data_define_access/sno_var_X Ljava/lang/String;
    getstatic       _94_data_define_access/sno_vars Ljava/util/HashMap;
    ldc             "X"
    ldc             ""
    invokevirtual   java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    return
.end method

.method static sno_mon_init()V
    .limit stack 6
    .limit locals 2
    ldc "MONITOR_READY_PIPE"
    invokestatic java/lang/System/getenv(Ljava/lang/String;)Ljava/lang/String;
    astore_0
    aload_0
    ifnull Lsmi_done
    aload_0
    invokevirtual java/lang/String/isEmpty()Z
    ifne Lsmi_done
    new java/io/FileOutputStream
    dup
    aload_0
    iconst_1
    invokespecial java/io/FileOutputStream/<init>(Ljava/lang/String;Z)V
    putstatic _94_data_define_access/sno_mon_fd Ljava/io/OutputStream;
    ldc "MONITOR_GO_PIPE"
    invokestatic java/lang/System/getenv(Ljava/lang/String;)Ljava/lang/String;
    astore_1
    aload_1
    ifnull Lsmi_done
    aload_1
    invokevirtual java/lang/String/isEmpty()Z
    ifne Lsmi_done
    new java/io/FileInputStream
    dup
    aload_1
    invokespecial java/io/FileInputStream/<init>(Ljava/lang/String;)V
    putstatic _94_data_define_access/sno_mon_go_fd Ljava/io/InputStream;
Lsmi_done:
    return
.end method

.method public static main([Ljava/lang/String;)V
    .limit stack 16
    .limit locals 32

    invokestatic _94_data_define_access/sno_mon_init()V
    getstatic _94_data_define_access/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _94_data_define_access/sno_kw_STNO I
    invokestatic _94_data_define_access/sno_stcount_tick()V
    ldc "complex(real,imag)"
    invokestatic _94_data_define_access/sno_data_define(Ljava/lang/String;)V
    ldc ""
    pop
    getstatic _94_data_define_access/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _94_data_define_access/sno_kw_STNO I
    invokestatic _94_data_define_access/sno_stcount_tick()V
    ldc "0"
    invokestatic _94_data_define_access/sno_array_new(Ljava/lang/String;)Ljava/lang/String;
    dup
    ldc "real"
    ldc "3"
    invokestatic _94_data_define_access/sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    dup
    ldc "imag"
    ldc "2"
    invokestatic _94_data_define_access/sno_to_double(Ljava/lang/String;)D
    dneg
    dstore 2
    dload 2
    d2l
    lstore 4
    lload 4
    l2d
    dload 2
    dcmpl
    ifne Lmnsf_0
    lload 4
    invokestatic java/lang/Long/toString(J)Ljava/lang/String;
    goto Lmnsd_0
Lmnsf_0:
    dload 2
    invokestatic java/lang/Double/toString(D)Ljava/lang/String;
Lmnsd_0:
    invokestatic _94_data_define_access/sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    dup
    ldc "__type__"
    ldc "complex"
    invokestatic _94_data_define_access/sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    dup
    ifnonnull Lvar_ok_0
    pop
    goto Lvar_fail_0
Lvar_ok_0:
    ldc "X"
    swap
    invokestatic _94_data_define_access/sno_var_put(Ljava/lang/String;Ljava/lang/String;)V
Lvar_fail_0:
    getstatic _94_data_define_access/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _94_data_define_access/sno_kw_STNO I
    invokestatic _94_data_define_access/sno_stcount_tick()V
    ldc "X"
    invokestatic _94_data_define_access/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "real"
    invokestatic _94_data_define_access/sno_data_get_field(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Lout_ok_0
    pop
    goto Lout_fail_0
Lout_ok_0:
    getstatic _94_data_define_access/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
Lout_fail_0:
    getstatic _94_data_define_access/sno_kw_STNO I
    iconst_1
    iadd
    putstatic _94_data_define_access/sno_kw_STNO I
    invokestatic _94_data_define_access/sno_stcount_tick()V
    ldc "X"
    invokestatic _94_data_define_access/sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    ldc "imag"
    invokestatic _94_data_define_access/sno_data_get_field(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    dup
    ifnonnull Lout_ok_1
    pop
    goto Lout_fail_1
Lout_ok_1:
    getstatic _94_data_define_access/sno_stdout Ljava/io/PrintStream;
    swap
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
Lout_fail_1:
; === END =============================================================
L_END:
    nop
; program end
    return
.end method
.method static sno_to_double(Ljava/lang/String;)D
    .limit stack 4
    .limit locals 1
    aload_0
    ifnull Lsno_pd_zero
    aload_0
    invokevirtual java/lang/String/trim()Ljava/lang/String;
    invokevirtual java/lang/String/isEmpty()Z
    ifne Lsno_pd_zero
    aload_0
    invokestatic java/lang/Double/parseDouble(Ljava/lang/String;)D
    dreturn
Lsno_pd_zero:
    dconst_0
    dreturn
.end method

.method static sno_str_eq(Ljava/lang/String;Ljava/lang/String;)Z
    .limit stack 4
    .limit locals 2
    aload_0
    ifnull Lstreq_false
    aload_1
    ifnull Lstreq_false
    aload_0
    aload_1
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ireturn
Lstreq_false:
    iconst_0
    ireturn
.end method

.method static sno_kw_get(Ljava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 3
    aload_0
    ldc "ALPHABET"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_alphabet
    new java/lang/StringBuilder
    dup
    invokespecial java/lang/StringBuilder/<init>()V
    astore_1
    iconst_0
    istore_2
Lkwg_alpha_loop:
    iload_2
    sipush 256
    if_icmpge Lkwg_alpha_done
    aload_1
    iload_2
    i2c
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    pop
    iinc 2 1
    goto Lkwg_alpha_loop
Lkwg_alpha_done:
    aload_1
    invokevirtual java/lang/StringBuilder/toString()Ljava/lang/String;
    areturn
Lkwg_not_alphabet:
    aload_0
    ldc "UCASE"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_ucase
    ldc "ABCDEFGHIJKLMNOPQRSTUVWXYZ"
    areturn
Lkwg_not_ucase:
    aload_0
    ldc "LCASE"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_lcase
    ldc "abcdefghijklmnopqrstuvwxyz"
    areturn
Lkwg_not_lcase:
    aload_0
    ldc "STNO"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_stno
    getstatic _94_data_define_access/sno_kw_STNO I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_stno:
    aload_0
    ldc "TRIM"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_trim
    getstatic _94_data_define_access/sno_kw_TRIM I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_trim:
    aload_0
    ldc "ANCHOR"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_anchor
    getstatic _94_data_define_access/sno_kw_ANCHOR I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_anchor:
    aload_0
    ldc "STLIMIT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_stlimit
    getstatic _94_data_define_access/sno_kw_STLIMIT I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_stlimit:
    aload_0
    ldc "STCOUNT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkwg_not_stcount
    getstatic _94_data_define_access/sno_kw_STCOUNT I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    areturn
Lkwg_not_stcount:
    ldc ""
    areturn
.end method

.method static sno_kw_set(Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 4
    .limit locals 2
    aload_0
    ldc "TRIM"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_trim
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _94_data_define_access/sno_kw_TRIM I
    return
Lkws_not_trim:
    aload_0
    ldc "ANCHOR"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_anchor
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _94_data_define_access/sno_kw_ANCHOR I
    return
Lkws_not_anchor:
    aload_0
    ldc "STNO"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_stno
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _94_data_define_access/sno_kw_STNO I
    return
Lkws_not_stno:
    aload_0
    ldc "STLIMIT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_stlimit
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _94_data_define_access/sno_kw_STLIMIT I
    return
Lkws_not_stlimit:
    aload_0
    ldc "STCOUNT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lkws_not_stcount
    aload_1
    invokestatic java/lang/Integer/parseInt(Ljava/lang/String;)I
    putstatic _94_data_define_access/sno_kw_STCOUNT I
    return
Lkws_not_stcount:
    return
.end method

.method static sno_var_put(Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 4
    .limit locals 2
    aload_0
    ldc "OUTPUT"
    invokevirtual java/lang/String/equalsIgnoreCase(Ljava/lang/String;)Z
    ifeq Lsvp_not_output
    getstatic _94_data_define_access/sno_stdout Ljava/io/PrintStream;
    aload_1
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    return
Lsvp_not_output:
    getstatic _94_data_define_access/sno_vars Ljava/util/HashMap;
    aload_0
    aload_1
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    aload_0
    aload_1
    invokestatic _94_data_define_access/sno_mon_var(Ljava/lang/String;Ljava/lang/String;)V
    return
.end method

.method static sno_mon_var(Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 6
    .limit locals 3
    getstatic _94_data_define_access/sno_mon_fd Ljava/io/OutputStream;
    ifnull Lsmv_done
    new java/lang/StringBuilder
    dup
    invokespecial java/lang/StringBuilder/<init>()V
    ldc "VALUE"
    invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
    bipush 30
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    aload_0
    invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
    bipush 31
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    aload_1
    invokevirtual java/lang/StringBuilder/append(Ljava/lang/String;)Ljava/lang/StringBuilder;
    bipush 30
    invokevirtual java/lang/StringBuilder/append(C)Ljava/lang/StringBuilder;
    invokevirtual java/lang/StringBuilder/toString()Ljava/lang/String;
    ldc "UTF-8"
    invokevirtual java/lang/String/getBytes(Ljava/lang/String;)[B
    astore_2
    getstatic _94_data_define_access/sno_mon_fd Ljava/io/OutputStream;
    aload_2
    invokevirtual java/io/OutputStream/write([B)V
    getstatic _94_data_define_access/sno_mon_go_fd Ljava/io/InputStream;
    ifnull Lsmv_done
    getstatic _94_data_define_access/sno_mon_go_fd Ljava/io/InputStream;
    invokevirtual java/io/InputStream/read()I
    istore_2
    iload_2
    bipush 71
    if_icmpeq Lsmv_done
    iconst_0
    invokestatic SnoRuntime/sno_exit(I)V
Lsmv_done:
    return
.end method

.method static sno_stcount_tick()V
    .limit stack 4
    .limit locals 0
    getstatic _94_data_define_access/sno_kw_STCOUNT I
    iconst_1
    iadd
    putstatic _94_data_define_access/sno_kw_STCOUNT I
    getstatic _94_data_define_access/sno_kw_STLIMIT I
    iflt Lstick_ok
    getstatic _94_data_define_access/sno_kw_STCOUNT I
    getstatic _94_data_define_access/sno_kw_STLIMIT I
    if_icmple Lstick_ok
    getstatic java/lang/System/err Ljava/io/PrintStream;
    ldc "Termination: statement limit"
    invokevirtual java/io/PrintStream/println(Ljava/lang/String;)V
    iconst_1
    invokestatic SnoRuntime/sno_exit(I)V
Lstick_ok:
    return
.end method

.method static sno_indr_get(Ljava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 1
    getstatic _94_data_define_access/sno_vars Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/lang/String
    dup
    ifnonnull Lsig_done_indr
    pop
    ldc ""
Lsig_done_indr:
    areturn
.end method

.method static sno_indr_set(Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 4
    .limit locals 2
    getstatic _94_data_define_access/sno_vars Ljava/util/HashMap;
    aload_0
    aload_1
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    return
.end method

.method static sno_array_new(Ljava/lang/String;)Ljava/lang/String;
    .limit stack 6
    .limit locals 2
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    astore_1
    aload_1
    invokestatic java/lang/System/identityHashCode(Ljava/lang/Object;)I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    dup
    getstatic _94_data_define_access/sno_arrays Ljava/util/HashMap;
    swap
    aload_1
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    areturn
.end method

.method static sno_array_new2(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    .limit stack 8
    .limit locals 6
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    astore_2
    aload_2
    invokestatic java/lang/System/identityHashCode(Ljava/lang/Object;)I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    astore_3
    getstatic _94_data_define_access/sno_arrays Ljava/util/HashMap;
    aload_3
    aload_2
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    aload_0
    invokestatic java/lang/Double/parseDouble(Ljava/lang/String;)D
    d2i
    istore 4
    aload_1
    invokevirtual java/lang/String/isEmpty()Z
    ifne La2_done
    iconst_1
    istore 5
La2_loop:
    iload 5
    iload 4
    if_icmpgt La2_done
    aload_2
    iload 5
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    aload_1
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    iinc 5 1
    goto La2_loop
La2_done:
    aload_3
    areturn
.end method

.method static sno_table_new()Ljava/lang/String;
    .limit stack 6
    .limit locals 2
    new java/util/HashMap
    dup
    invokespecial java/util/HashMap/<init>()V
    astore_0
    aload_0
    invokestatic java/lang/System/identityHashCode(Ljava/lang/Object;)I
    invokestatic java/lang/Integer/toString(I)Ljava/lang/String;
    dup
    getstatic _94_data_define_access/sno_arrays Ljava/util/HashMap;
    swap
    aload_0
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
    areturn
.end method

.method static sno_array_get(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 3
    getstatic _94_data_define_access/sno_arrays Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/util/HashMap
    astore_2
    aload_2
    ifnull Lag_null
    aload_2
    aload_1
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/lang/String
    areturn
Lag_null:
    aconst_null
    areturn
.end method

.method static sno_array_put(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
    .limit stack 4
    .limit locals 4
    getstatic _94_data_define_access/sno_arrays Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/util/HashMap
    astore_3
    aload_3
    ifnull Lap_done
    aload_3
    aload_1
    aload_2
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
Lap_done:
    return
.end method

.method static sno_data_define(Ljava/lang/String;)V
    .limit stack 6
    .limit locals 4
    aload_0
    ldc "("
    invokevirtual java/lang/String/indexOf(Ljava/lang/String;)I
    istore_1
    iload_1
    iflt Ldd_done
    aload_0
    iconst_0
    iload_1
    invokevirtual java/lang/String/substring(II)Ljava/lang/String;
    astore_2
    aload_0
    iload_1
    iconst_1
    iadd
    aload_0
    invokevirtual java/lang/String/length()I
    iconst_1
    isub
    invokevirtual java/lang/String/substring(II)Ljava/lang/String;
    astore_3
    getstatic _94_data_define_access/sno_data_types Ljava/util/HashMap;
    aload_2
    aload_3
    invokevirtual java/util/HashMap/put(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
    pop
Ldd_done:
    return
.end method

.method static sno_data_get_field(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 3
    getstatic _94_data_define_access/sno_arrays Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/util/HashMap
    astore_2
    aload_2
    ifnull Ldgf_null
    aload_2
    aload_1
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/lang/String
    dup
    ifnonnull Ldgf_done
    pop
Ldgf_null:
    ldc ""
Ldgf_done:
    areturn
.end method

.method static sno_data_get_type(Ljava/lang/String;)Ljava/lang/String;
    .limit stack 4
    .limit locals 2
    getstatic _94_data_define_access/sno_arrays Ljava/util/HashMap;
    aload_0
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/util/HashMap
    astore_1
    aload_1
    ifnull Ldgt_null
    aload_1
    ldc "__type__"
    invokevirtual java/util/HashMap/get(Ljava/lang/Object;)Ljava/lang/Object;
    checkcast java/lang/String
    dup
    ifnonnull Ldgt_done
    pop
Ldgt_null:
    ldc ""
Ldgt_done:
    areturn
.end method

