; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 2
                            call        comm_stno
                            CALL1_STR   S_DATA, S_complex_LP_real_CM_imag_RP

; ======================================================================================================================
Ln_0:                       mov         edi, 3
                            call        comm_stno
                            sub         rsp, 32
                            LOAD_INT    3
                            STORE_ARG32 0
                            CALL1_INT   S_neg, 2
                            STORE_ARG32 16
                            APPLY_FN_N  S_complex, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Ln_1
                            SET_VAR     S_X
                            jmp         Ln_1

; ======================================================================================================================
Ln_1:                       mov         edi, 4
                            call        comm_stno
                            CALL1_VAR   S_real, S_X
                            FAIL_BR     Ln_2
                            SET_OUTPUT
                            jmp         Ln_2

; ======================================================================================================================
Ln_2:                       mov         edi, 5
                            call        comm_stno
                            CALL1_VAR   S_imag, S_X
                            FAIL_BR     Ln_3
                            SET_OUTPUT
                            jmp         Ln_3
Ln_3:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_DATA               db 68, 65, 84, 65, 0  ; "DATA"
S_complex_LP_real_CM_imag_RP db 99, 111, 109, 112, 108, 101, 120, 40, 114, 101, 97, 108, 44, 105, 109, 97, 103, 41, 0  ; "complex(real,imag)"
S_X                  db 88, 0  ; "X"
S_complex            db 99, 111, 109, 112, 108, 101, 120, 0  ; "complex"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_real               db 114, 101, 97, 108, 0  ; "real"
S_imag               db 105, 109, 97, 103, 0  ; "imag"
S_END                db 69, 78, 68, 0  ; "END"
S_neg                db 110, 101, 103, 0  ; "neg"
