/*
 * emit_wasm.c — WebAssembly text-format emitter for scrip-cc
 *
 * Naming law: W(fmt,...) for output lines, WI(op,arg) for single instructions.
 *
 * Memory layout (matches sno_runtime.wat):
 *   [0 .. 32767]    output buffer
 *   [32768..49151]  string heap
 *   [49152..65535]  variable table (M-SW-A04)
 *
 * String representation: (offset: i32, len: i32) pair.
 * Integer representation: i64.
 * Output protocol: main() returns $sno_output_flush result (byte-count i32).
 *
 * Milestones:
 *   M-G2-SCAFFOLD-WASM  — stub (G-7 2026-03-28)
 *   M-SW-0              — -wasm driver flag (SW-1 2026-03-30)
 *   M-SW-1              — runtime header inlined, program skeleton (SW-1 2026-03-30)
 */

#include "scrip_cc.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define W(fmt, ...)  fprintf(wasm_out, fmt, ##__VA_ARGS__)

static FILE *wasm_out = NULL;

/* Runtime WAT is installed alongside the source tree */
static const char *runtime_wat_path(void) {
    /* Walk up from __FILE__ is fragile; use a path relative to build root.
       SESSION_SETUP.sh builds in /home/claude/one4all/src/ so this is stable. */
    return "/home/claude/one4all/src/runtime/wasm/sno_runtime.wat";
}

/*
 * emit_wasm_runtime_header — inline sno_runtime.wat verbatim.
 * The fragment contains (memory ...), globals, and all helper funcs.
 * Every .wat is self-contained; no external imports needed.
 */
static void emit_wasm_runtime_header(void) {
    FILE *rt = fopen(runtime_wat_path(), "r");
    if (!rt) {
        W("  ;; WARNING: runtime not found — stub memory only\n");
        W("  (memory (export \"memory\") 1)\n");
        W("  (global $out_pos (mut i32) (i32.const 0))\n");
        W("  (func $sno_output_flush (result i32) (global.get $out_pos))\n");
        return;
    }
    char line[1024];
    while (fgets(line, sizeof line, rt))
        W("%s", line);
    fclose(rt);
}

/* ── Public entry point ───────────────────────────────────────────────────── */

void emit_wasm(Program *prog, FILE *out, const char *filename) {
    (void)filename;
    (void)prog;   /* IR walk wired from M-SW-A01 */

    wasm_out = out;

    W(";; Generated by scrip-cc -wasm\n");
    W("(module\n");

    emit_wasm_runtime_header();

    W("\n  (func (export \"main\") (result i32)\n");
    /* IR emission: M-SW-A01 and later */
    W("    call $sno_output_flush\n");
    W("  )\n");
    W(")\n");
}
