; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_ispos_ret_γ           resq 1
P_ispos_ret_ω           resq 1
fn_ispos_save_x_t        resq 1
fn_ispos_save_x_p        resq 1
fn_ispos_arg_0_t         resq 1
fn_ispos_arg_0_p         resq 1
ucall0_sv_0_t            resq 1
ucall0_sv_0_p            resq 1
ucall0_rsv_g             resq 1
ucall0_rsv_o             resq 1
ucall1_sv_0_t            resq 1
ucall1_sv_0_p            resq 1
ucall1_rsv_g             resq 1
ucall1_rsv_o             resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 2
                            call        comm_stno
Ln_0:                       GOTO_ALWAYS L_ispos_end_0

;  ispos ===============================================================================================================
L_ispos_1:                  mov         edi, 3
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_x]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_INT    0
                            STORE_ARG32 16
                            APPLY_FN_N  S_GT, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_1
                            jmp         fn_ispos_γ     ; RETURN
Lf_1:                       jmp         fn_ispos_ω     ; FRETURN

Ln_1:
;  ispos_end ===========================================================================================================
L_ispos_end_0:              mov         edi, 4
                            call        comm_stno

; ======================================================================================================================
Ln_2:                       mov         edi, 5
                            call        comm_stno
                            sub         rsp, 8          ; align pad
                            GET_VAR     S_x
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        r12
                            push        qword [P_ispos_ret_ω]
                            push        qword [P_ispos_ret_γ]
                            LOAD_INT    5
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_ispos_arg_0_t], rax
                            mov         [fn_ispos_arg_0_p], rcx
                            mov         rdi, [rel box_ispos_data_size]
                            call        blk_alloc
                            mov         rdi, rax
                            lea         rsi, [rel box_ispos_data_template]
                            mov         rdx, [rel box_ispos_data_size]
                            call        memcpy
                            mov         r12, rax
                            lea         rax, [rel ucall0_ret_g]
                            mov         [P_ispos_ret_γ], rax
                            lea         rax, [rel ucall0_ret_o]
                            mov         [P_ispos_ret_ω], rax
                            call        stmt_save_subject
                            jmp         P_ispos_α
ucall0_ret_g:
                            pop         qword [P_ispos_ret_γ]
                            pop         qword [P_ispos_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_ispos_data_size]
                            call        blk_free
                            call        stmt_restore_subject
                            GET_VAR     S_ispos
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_x]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall0_has_val
                            LOAD_NULVCL32
                            jmp         ucall0_done
ucall0_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall0_done
ucall0_ret_o:
                            pop         qword [P_ispos_ret_γ]
                            pop         qword [P_ispos_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_ispos_data_size]
                            call        blk_free
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_x]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            call        stmt_restore_subject
                            LOAD_FAILDESCR32
ucall0_done:
                            FAIL_BR     Lf_3
                            jmp         L_A_2
Lf_3:                       jmp         L_B_3

Ln_3:
;  A ===================================================================================================================
L_A_2:                      mov         edi, 6
                            call        comm_stno
                            LOAD_STR    S_positive
                            FAIL_BR     Ln_4
                            SET_OUTPUT
                            jmp         Ln_4

; ======================================================================================================================
Ln_4:                       mov         edi, 7
                            call        comm_stno
                            jmp         L_NEXT_4

Ln_5:
;  B ===================================================================================================================
L_B_3:                      mov         edi, 8
                            call        comm_stno
                            LOAD_STR    S_wrong
                            FAIL_BR     Ln_6
                            SET_OUTPUT
                            jmp         Ln_6

Ln_6:
;  NEXT ================================================================================================================
L_NEXT_4:                   mov         edi, 9
                            call        comm_stno
                            sub         rsp, 8          ; align pad
                            GET_VAR     S_x
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        r12
                            push        qword [P_ispos_ret_ω]
                            push        qword [P_ispos_ret_γ]
                            CALL1_INT   S_neg, 3
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_ispos_arg_0_t], rax
                            mov         [fn_ispos_arg_0_p], rcx
                            mov         rdi, [rel box_ispos_data_size]
                            call        blk_alloc
                            mov         rdi, rax
                            lea         rsi, [rel box_ispos_data_template]
                            mov         rdx, [rel box_ispos_data_size]
                            call        memcpy
                            mov         r12, rax
                            lea         rax, [rel ucall1_ret_g]
                            mov         [P_ispos_ret_γ], rax
                            lea         rax, [rel ucall1_ret_o]
                            mov         [P_ispos_ret_ω], rax
                            call        stmt_save_subject
                            jmp         P_ispos_α
ucall1_ret_g:
                            pop         qword [P_ispos_ret_γ]
                            pop         qword [P_ispos_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_ispos_data_size]
                            call        blk_free
                            call        stmt_restore_subject
                            GET_VAR     S_ispos
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_x]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall1_has_val
                            LOAD_NULVCL32
                            jmp         ucall1_done
ucall1_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall1_done
ucall1_ret_o:
                            pop         qword [P_ispos_ret_γ]
                            pop         qword [P_ispos_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_ispos_data_size]
                            call        blk_free
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_x]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            call        stmt_restore_subject
                            LOAD_FAILDESCR32
ucall1_done:
                            FAIL_BR     Lf_7
                            jmp         L_C_5
Lf_7:                       jmp         L_D_6

Ln_7:
;  C ===================================================================================================================
L_C_5:                      mov         edi, 10
                            call        comm_stno
                            LOAD_STR    S_wrong
                            FAIL_BR     Ln_8
                            SET_OUTPUT
                            jmp         Ln_8

; ======================================================================================================================
Ln_8:                       mov         edi, 11
                            call        comm_stno
                            GOTO_ALWAYS L_SNO_END     ; END

Ln_9:
;  D ===================================================================================================================
L_D_6:                      mov         edi, 12
                            call        comm_stno
                            LOAD_STR    S_not_SP_positive
                            FAIL_BR     Ln_10
                            SET_OUTPUT
                            jmp         Ln_10
Ln_10:                      GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_ispos_α — user function α entry (1 param) [r12=DATA block]
;  ispos ===============================================================================================================
P_ispos_α:                  FN_α_INIT   ispos
                            mov         rsi, [fn_ispos_arg_0_t]
                            mov         rdx, [fn_ispos_arg_0_p]
                            FN_SET_PARAM S_x
                            LOAD_NULVCL
                            mov         [r12+16], rax
                            mov         [r12+24], rdx
                            mov         rsi, [r12+16]
                            mov         rdx, [r12+24]
                            FN_CLEAR_VAR S_ispos
                            jmp         L_ispos_1
;  γ/ω ---------------------------------------------------------------------------------------------------------------
fn_ispos_γ:                 FN_γ        P_ispos_ret_γ ; fn γ
fn_ispos_ω:                 FN_ω        P_ispos_ret_ω ; fn ω
P_ispos_β:                  jmp         [P_ispos_ret_ω] ; fn β — backtrack = fail

section .text
;  STUB LABELS =========================================================================================================

section .rodata
global  box_ispos_reloc_count, box_ispos_reloc_table
; --- box ispos ---
box_ispos_reloc_count: dq 0
box_ispos_reloc_table:
; (entries added by M-T2-INVOKE)

;  BOX RELOCATION TABLES ===============================================================================================

global  box_ispos_data_template, box_ispos_data_size
section .data
;  BOX DATA TEMPLATES ==================================================================================================
                            align       8
box_ispos_data_size: dq 64
box_ispos_data_template:
dq 0  ; [r12+0] = P_ispos_ret_γ
dq 0  ; [r12+8] = P_ispos_ret_ω
dq 0  ; [r12+16] = fn_ispos_tmp1_t
dq 0  ; [r12+24] = fn_ispos_tmp1_p
dq 0  ; [r12+32] = fn_ispos_tmp2_t
dq 0  ; [r12+40] = fn_ispos_tmp2_p
dq 0  ; [r12+48] = fn_ispos_tmp3_t
dq 0  ; [r12+56] = fn_ispos_tmp3_p


section .data
S_DEFINE             db 68, 69, 70, 73, 78, 69, 0  ; "DEFINE"
S_ispos_LP_x_RP      db 105, 115, 112, 111, 115, 40, 120, 41, 0  ; "ispos(x)"
S_ispos              db 105, 115, 112, 111, 115, 0  ; "ispos"
S_GT                 db 71, 84, 0  ; "GT"
S_x                  db 120, 0  ; "x"
S_ispos_end          db 105, 115, 112, 111, 115, 95, 101, 110, 100, 0  ; "ispos_end"
S_A                  db 65, 0  ; "A"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_positive           db 112, 111, 115, 105, 116, 105, 118, 101, 0  ; "positive"
S_B                  db 66, 0  ; "B"
S_wrong              db 119, 114, 111, 110, 103, 0  ; "wrong"
S_NEXT               db 78, 69, 88, 84, 0  ; "NEXT"
S_C                  db 67, 0  ; "C"
S_D                  db 68, 0  ; "D"
S_not_SP_positive    db 110, 111, 116, 32, 112, 111, 115, 105, 116, 105, 118, 101, 0  ; "not positive"
S_END                db 69, 78, 68, 0  ; "END"
S_neg                db 110, 101, 103, 0  ; "neg"
