; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_upcase_ret_γ          resq 1
P_upcase_ret_ω          resq 1
fn_upcase_save_s_t       resq 1
fn_upcase_save_s_p       resq 1
fn_upcase_arg_0_t        resq 1
fn_upcase_arg_0_p        resq 1
ucall0_sv_0_t            resq 1
ucall0_sv_0_p            resq 1
ucall0_rsv_g             resq 1
ucall0_rsv_o             resq 1
ucall1_sv_0_t            resq 1
ucall1_sv_0_p            resq 1
ucall1_rsv_g             resq 1
ucall1_rsv_o             resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 2
                            call        comm_stno
Ln_0:                       GOTO_ALWAYS L_upcase_end_0

;  upcase ==============================================================================================================
L_upcase_1:                 mov         edi, 3
                            call        comm_stno
                            sub         rsp, 48
                            lea         rdi, [rel S_s]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            lea         rdi, [rel S_LCASE]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 16
                            lea         rdi, [rel S_UCASE]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 32
                            APPLY_FN_N  S_REPLACE, 3
                            add         rsp, 48
                            STORE_RESULT
                            FAIL_BR     Lf_1
                            SET_VAR     S_upcase
                            jmp         fn_upcase_γ     ; RETURN
Lf_1:                       jmp         fn_upcase_γ     ; RETURN

Ln_1:
;  upcase_end ==========================================================================================================
L_upcase_end_0:             mov         edi, 4
                            call        comm_stno

; ======================================================================================================================
Ln_2:                       mov         edi, 5
                            call        comm_stno
                            sub         rsp, 8          ; align pad
                            GET_VAR     S_s
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        r12
                            push        qword [P_upcase_ret_ω]
                            push        qword [P_upcase_ret_γ]
                            LOAD_STR    S_hello
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_upcase_arg_0_t], rax
                            mov         [fn_upcase_arg_0_p], rcx
                            mov         rdi, [rel box_upcase_data_size]
                            call        blk_alloc
                            mov         rdi, rax
                            lea         rsi, [rel box_upcase_data_template]
                            mov         rdx, [rel box_upcase_data_size]
                            call        memcpy
                            mov         r12, rax
                            lea         rax, [rel ucall0_ret_g]
                            mov         [P_upcase_ret_γ], rax
                            lea         rax, [rel ucall0_ret_o]
                            mov         [P_upcase_ret_ω], rax
                            call        stmt_save_subject
                            jmp         P_upcase_α
ucall0_ret_g:
                            pop         qword [P_upcase_ret_γ]
                            pop         qword [P_upcase_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_upcase_data_size]
                            call        blk_free
                            call        stmt_restore_subject
                            GET_VAR     S_upcase
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_s]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall0_has_val
                            LOAD_NULVCL32
                            jmp         ucall0_done
ucall0_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall0_done
ucall0_ret_o:
                            pop         qword [P_upcase_ret_γ]
                            pop         qword [P_upcase_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_upcase_data_size]
                            call        blk_free
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_s]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            call        stmt_restore_subject
                            LOAD_FAILDESCR32
ucall0_done:
                            FAIL_BR     Ln_3
                            SET_OUTPUT
                            jmp         Ln_3

; ======================================================================================================================
Ln_3:                       mov         edi, 6
                            call        comm_stno
                            sub         rsp, 8          ; align pad
                            GET_VAR     S_s
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        r12
                            push        qword [P_upcase_ret_ω]
                            push        qword [P_upcase_ret_γ]
                            LOAD_STR    S_world
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_upcase_arg_0_t], rax
                            mov         [fn_upcase_arg_0_p], rcx
                            mov         rdi, [rel box_upcase_data_size]
                            call        blk_alloc
                            mov         rdi, rax
                            lea         rsi, [rel box_upcase_data_template]
                            mov         rdx, [rel box_upcase_data_size]
                            call        memcpy
                            mov         r12, rax
                            lea         rax, [rel ucall1_ret_g]
                            mov         [P_upcase_ret_γ], rax
                            lea         rax, [rel ucall1_ret_o]
                            mov         [P_upcase_ret_ω], rax
                            call        stmt_save_subject
                            jmp         P_upcase_α
ucall1_ret_g:
                            pop         qword [P_upcase_ret_γ]
                            pop         qword [P_upcase_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_upcase_data_size]
                            call        blk_free
                            call        stmt_restore_subject
                            GET_VAR     S_upcase
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_s]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall1_has_val
                            LOAD_NULVCL32
                            jmp         ucall1_done
ucall1_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall1_done
ucall1_ret_o:
                            pop         qword [P_upcase_ret_γ]
                            pop         qword [P_upcase_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_upcase_data_size]
                            call        blk_free
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_s]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            call        stmt_restore_subject
                            LOAD_FAILDESCR32
ucall1_done:
                            FAIL_BR     Ln_4
                            SET_OUTPUT
                            jmp         Ln_4
Ln_4:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_upcase_α — user function α entry (1 param) [r12=DATA block]
;  upcase ==============================================================================================================
P_upcase_α:                 FN_α_INIT   upcase
                            mov         rsi, [fn_upcase_arg_0_t]
                            mov         rdx, [fn_upcase_arg_0_p]
                            FN_SET_PARAM S_s
                            LOAD_NULVCL
                            mov         [r12+16], rax
                            mov         [r12+24], rdx
                            mov         rsi, [r12+16]
                            mov         rdx, [r12+24]
                            FN_CLEAR_VAR S_upcase
                            jmp         L_upcase_1
;  γ/ω ---------------------------------------------------------------------------------------------------------------
fn_upcase_γ:                FN_γ        P_upcase_ret_γ ; fn γ
fn_upcase_ω:                FN_ω        P_upcase_ret_ω ; fn ω
P_upcase_β:                 jmp         [P_upcase_ret_ω] ; fn β — backtrack = fail

section .text
;  STUB LABELS =========================================================================================================

section .rodata
global  box_upcase_reloc_count, box_upcase_reloc_table
; --- box upcase ---
box_upcase_reloc_count: dq 0
box_upcase_reloc_table:
; (entries added by M-T2-INVOKE)

;  BOX RELOCATION TABLES ===============================================================================================

global  box_upcase_data_template, box_upcase_data_size
section .data
;  BOX DATA TEMPLATES ==================================================================================================
                            align       8
box_upcase_data_size: dq 64
box_upcase_data_template:
dq 0  ; [r12+0] = P_upcase_ret_γ
dq 0  ; [r12+8] = P_upcase_ret_ω
dq 0  ; [r12+16] = fn_upcase_tmp1_t
dq 0  ; [r12+24] = fn_upcase_tmp1_p
dq 0  ; [r12+32] = fn_upcase_tmp2_t
dq 0  ; [r12+40] = fn_upcase_tmp2_p
dq 0  ; [r12+48] = fn_upcase_tmp3_t
dq 0  ; [r12+56] = fn_upcase_tmp3_p


section .data
S_DEFINE             db 68, 69, 70, 73, 78, 69, 0  ; "DEFINE"
S_upcase_LP_s_RP     db 117, 112, 99, 97, 115, 101, 40, 115, 41, 0  ; "upcase(s)"
S_upcase             db 117, 112, 99, 97, 115, 101, 0  ; "upcase"
S_REPLACE            db 82, 69, 80, 76, 65, 67, 69, 0  ; "REPLACE"
S_UCASE              db 85, 67, 65, 83, 69, 0  ; "UCASE"
S_LCASE              db 76, 67, 65, 83, 69, 0  ; "LCASE"
S_s                  db 115, 0  ; "s"
S_upcase_end         db 117, 112, 99, 97, 115, 101, 95, 101, 110, 100, 0  ; "upcase_end"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_hello              db 104, 101, 108, 108, 111, 0  ; "hello"
S_world              db 119, 111, 114, 108, 100, 0  ; "world"
S_END                db 69, 78, 68, 0  ; "END"
