; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_bumpit_ret_γ          resq 1
P_bumpit_ret_ω          resq 1
fn_bumpit_save_v_t       resq 1
fn_bumpit_save_v_p       resq 1
fn_bumpit_arg_0_t        resq 1
fn_bumpit_arg_0_p        resq 1
ucall0_sv_0_t            resq 1
ucall0_sv_0_p            resq 1
ucall0_rsv_g             resq 1
ucall0_rsv_o             resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 2
                            call        comm_stno
Ln_0:                       GOTO_ALWAYS L_bumpend_0

;  bumpit ==============================================================================================================
L_bumpit_1:                 mov         edi, 3
                            call        comm_stno
                            CONC2_VI    S_add, S_v, 1
                            FAIL_BR     Lf_1
                            SET_VAR     S_bumpit
                            jmp         fn_bumpit_γ     ; RETURN
Lf_1:                       jmp         fn_bumpit_γ     ; RETURN

Ln_1:
;  bumpend =============================================================================================================
L_bumpend_0:                mov         edi, 4
                            call        comm_stno

; ======================================================================================================================
Ln_2:                       mov         edi, 5
                            call        comm_stno
                            sub         rsp, 8          ; align pad
                            GET_VAR     S_v
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        r12
                            push        qword [P_bumpit_ret_ω]
                            push        qword [P_bumpit_ret_γ]
                            LOAD_INT    41
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_bumpit_arg_0_t], rax
                            mov         [fn_bumpit_arg_0_p], rcx
                            mov         rdi, [rel box_bumpit_data_size]
                            call        blk_alloc
                            mov         rdi, rax
                            lea         rsi, [rel box_bumpit_data_template]
                            mov         rdx, [rel box_bumpit_data_size]
                            call        memcpy
                            mov         r12, rax
                            lea         rax, [rel ucall0_ret_g]
                            mov         [P_bumpit_ret_γ], rax
                            lea         rax, [rel ucall0_ret_o]
                            mov         [P_bumpit_ret_ω], rax
                            call        stmt_save_subject
                            jmp         P_bumpit_α
ucall0_ret_g:
                            pop         qword [P_bumpit_ret_γ]
                            pop         qword [P_bumpit_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_bumpit_data_size]
                            call        blk_free
                            call        stmt_restore_subject
                            GET_VAR     S_bumpit
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_v]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall0_has_val
                            LOAD_NULVCL32
                            jmp         ucall0_done
ucall0_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall0_done
ucall0_ret_o:
                            pop         qword [P_bumpit_ret_γ]
                            pop         qword [P_bumpit_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_bumpit_data_size]
                            call        blk_free
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_v]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            call        stmt_restore_subject
                            LOAD_FAILDESCR32
ucall0_done:
                            FAIL_BR     Ln_3
                            SET_OUTPUT
                            jmp         Ln_3
Ln_3:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_bumpit_α — user function α entry (1 param) [r12=DATA block]
;  bumpit ==============================================================================================================
P_bumpit_α:                 FN_α_INIT   bumpit
                            mov         rsi, [fn_bumpit_arg_0_t]
                            mov         rdx, [fn_bumpit_arg_0_p]
                            FN_SET_PARAM S_v
                            LOAD_NULVCL
                            mov         [r12+16], rax
                            mov         [r12+24], rdx
                            mov         rsi, [r12+16]
                            mov         rdx, [r12+24]
                            FN_CLEAR_VAR S_bumpit
                            jmp         L_bumpit_1
;  γ/ω ---------------------------------------------------------------------------------------------------------------
fn_bumpit_γ:                FN_γ        P_bumpit_ret_γ ; fn γ
fn_bumpit_ω:                FN_ω        P_bumpit_ret_ω ; fn ω
P_bumpit_β:                 jmp         [P_bumpit_ret_ω] ; fn β — backtrack = fail

section .text
;  STUB LABELS =========================================================================================================

section .rodata
global  box_bumpit_reloc_count, box_bumpit_reloc_table
; --- box bumpit ---
box_bumpit_reloc_count: dq 0
box_bumpit_reloc_table:
; (entries added by M-T2-INVOKE)

;  BOX RELOCATION TABLES ===============================================================================================

global  box_bumpit_data_template, box_bumpit_data_size
section .data
;  BOX DATA TEMPLATES ==================================================================================================
                            align       8
box_bumpit_data_size: dq 64
box_bumpit_data_template:
dq 0  ; [r12+0] = P_bumpit_ret_γ
dq 0  ; [r12+8] = P_bumpit_ret_ω
dq 0  ; [r12+16] = fn_bumpit_tmp1_t
dq 0  ; [r12+24] = fn_bumpit_tmp1_p
dq 0  ; [r12+32] = fn_bumpit_tmp2_t
dq 0  ; [r12+40] = fn_bumpit_tmp2_p
dq 0  ; [r12+48] = fn_bumpit_tmp3_t
dq 0  ; [r12+56] = fn_bumpit_tmp3_p


section .data
S_DEFINE             db 68, 69, 70, 73, 78, 69, 0  ; "DEFINE"
S_bumpit             db 98, 117, 109, 112, 105, 116, 0  ; "bumpit"
S_bumpit_LP_v_RP     db 98, 117, 109, 112, 105, 116, 40, 118, 41, 0  ; "bumpit(v)"
S_v                  db 118, 0  ; "v"
S_bumpend            db 98, 117, 109, 112, 101, 110, 100, 0  ; "bumpend"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_END                db 69, 78, 68, 0  ; "END"
S_add                db 97, 100, 100, 0  ; "add"
