; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
scan_start_2             resq 1
dol_entry_V              resq 1
rpat1_t                  resq 1
rpat1_p                  resq 1
rpat1_s                  resq 1
cap_V_buf                resb 256
cap_V_len                resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 2
                            call        comm_stno
                            sub         rsp, 32
                            LOAD_STR    S_a
                            STORE_ARG32 0
                            ALT2        S_ALT, S_b, S_c
                            STORE_ARG32 16
                            APPLY_FN_N  S_ALT, 2
                            add         rsp, 32
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_0
                            SET_VAR     S_P
                            jmp         Ln_0

; ======================================================================================================================
Ln_0:                       mov         edi, 3
                            call        comm_stno
                            ASSIGN_STR  S_X, S_b, Ln_1
                            jmp         Ln_1

; ======================================================================================================================
Ln_1:                       mov         edi, 4
                            call        comm_stno
                            GET_VAR     S_X
                            SUBJ_FROM16
                            test        eax, eax
                            jnz         P_2_ω
                            mov         qword [scan_start_2], 0
scan_retry_2:
                            mov         rax, [scan_start_2]
                            mov         [cursor], rax
                            jmp         P_2_α


P_2_α: ; DOL(V $  V)
                            DOL_SAVE    dol_entry_V, cursor, dol0_child_α ; DOL α — save entry cursor
P_2_β:                      jmp         dol0_child_β ; DOL β

; E_VART P → CALL_PAT (runtime DT_P/DT_S dispatch)
dol0_child_α:               lea         rdi, [rel S_P]
                            call        stmt_get
                            mov         [rpat1_t], rax
                            mov         [rpat1_p], rdx
                            mov         rax, [cursor]
                            mov         [rpat1_s], rax
                            mov         rdi, [rpat1_t]
                            mov         rsi, [rpat1_p]
                            call        stmt_match_descr
                            test        eax, eax
                            jz          dol0_ω
                            jmp         dol0_γ
dol0_child_β:               mov         rax, [rpat1_s]
                            mov         [cursor], rax
                            jmp         dol0_ω
dol0_γ:                     DOL_CAPTURE dol_entry_V, cursor, cap_V_buf, cap_V_len, subject_data, P_2_γ ; DOL γ — capture span
dol0_ω:                     jmp         P_2_ω ; DOL ω — child failed

P_2_γ:                      mov         rax, [cursor]
                            mov         [scan_start_2], rax
                            SET_CAPTURE S_V, cap_V_buf, cap_V_len
                            jmp         L_YES_0
P_2_ω:                      cmp         qword [rel kw_anchor], 0
                            jne         L_NO_1
                            mov         rax, [scan_start_2]
                            inc         rax
                            cmp         rax, [subject_len_val]
                            jg          L_NO_1
                            mov         [scan_start_2], rax
                            jmp         scan_retry_2
                            jmp         L_NO_1

Ln_2:
;  YES =================================================================================================================
L_YES_0:                    mov         edi, 5
                            call        comm_stno
                            lea         rdi, [rel S_V]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_3
                            SET_OUTPUT
                            jmp         Ln_3

; ======================================================================================================================
Ln_3:                       mov         edi, 6
                            call        comm_stno
                            GOTO_ALWAYS L_SNO_END     ; END

Ln_4:
;  NO ==================================================================================================================
L_NO_1:                     mov         edi, 7
                            call        comm_stno
                            LOAD_STR    S_no_SP_match
                            FAIL_BR     Ln_5
                            SET_OUTPUT
                            jmp         Ln_5
Ln_5:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_P                  db 80, 0  ; "P"
S_c                  db 99, 0  ; "c"
S_b                  db 98, 0  ; "b"
S_a                  db 97, 0  ; "a"
S_X                  db 88, 0  ; "X"
S_V                  db 86, 0  ; "V"
S_YES                db 89, 69, 83, 0  ; "YES"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_NO                 db 78, 79, 0  ; "NO"
S_no_SP_match        db 110, 111, 32, 109, 97, 116, 99, 104, 0  ; "no match"
S_END                db 69, 78, 68, 0  ; "END"
S_ALT                db 65, 76, 84, 0  ; "ALT"
