; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
scan_start_2             resq 1
dol_entry_V              resq 1
dol0_child_α_saved      resq 1
cap_V_buf                resb 256
cap_V_len                resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 2
                            call        comm_stno
                            ASSIGN_STR  S_PAT, S_hello, Ln_0
                            jmp         Ln_0

; ======================================================================================================================
Ln_0:                       mov         edi, 3
                            call        comm_stno
                            ASSIGN_STR  S_X, S_say_SP_hello_SP_world, Ln_1
                            jmp         Ln_1

; ======================================================================================================================
Ln_1:                       mov         edi, 4
                            call        comm_stno
                            GET_VAR     S_X
                            SUBJ_FROM16
                            test        eax, eax
                            jnz         P_2_ω
                            mov         qword [scan_start_2], 0
scan_retry_2:
                            mov         rax, [scan_start_2]
                            mov         [cursor], rax
                            jmp         P_2_α


P_2_α: ; DOL(V $  V)
                            DOL_SAVE    dol_entry_V, cursor, dol0_child_α ; DOL α — save entry cursor
P_2_β:                      jmp         dol0_child_β ; DOL β

; E_INDR *PAT → inline LIT 'hello'
dol0_child_α:               LIT_α       lit_str_1, 5, dol0_child_α_saved, cursor, subject_data, subject_len_val, dol0_γ, dol0_ω ; LIT α
dol0_child_β:               LIT_β       dol0_child_α_saved, cursor, dol0_ω ; LIT β
dol0_γ:                     DOL_CAPTURE dol_entry_V, cursor, cap_V_buf, cap_V_len, subject_data, P_2_γ ; DOL γ — capture span
dol0_ω:                     jmp         P_2_ω ; DOL ω — child failed

P_2_γ:                      mov         rax, [cursor]
                            mov         [scan_start_2], rax
                            SET_CAPTURE S_V, cap_V_buf, cap_V_len
                            jmp         L_YES_0
P_2_ω:                      cmp         qword [rel kw_anchor], 0
                            jne         Ln_2
                            mov         rax, [scan_start_2]
                            inc         rax
                            cmp         rax, [subject_len_val]
                            jg          Ln_2
                            mov         [scan_start_2], rax
                            jmp         scan_retry_2
                            jmp         Ln_2

; ======================================================================================================================
Ln_2:                       mov         edi, 5
                            call        comm_stno
                            LOAD_STR    S_fail
                            FAIL_BR     Ln_3
                            SET_OUTPUT
                            jmp         Ln_3

; ======================================================================================================================
Ln_3:                       mov         edi, 6
                            call        comm_stno
                            GOTO_ALWAYS L_SNO_END     ; END

Ln_4:
;  YES =================================================================================================================
L_YES_0:                    mov         edi, 7
                            call        comm_stno
                            lea         rdi, [rel S_V]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_5
                            SET_OUTPUT
                            jmp         Ln_5
Ln_5:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .data
lit_str_1            db 104, 101, 108, 108, 111

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_PAT                db 80, 65, 84, 0  ; "PAT"
S_hello              db 104, 101, 108, 108, 111, 0  ; "hello"
S_X                  db 88, 0  ; "X"
S_say_SP_hello_SP_world db 115, 97, 121, 32, 104, 101, 108, 108, 111, 32, 119, 111, 114, 108, 100, 0  ; "say hello world"
S_V                  db 86, 0  ; "V"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_fail               db 102, 97, 105, 108, 0  ; "fail"
S_YES                db 89, 69, 83, 0  ; "YES"
S_END                db 69, 78, 68, 0  ; "END"
