; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
scan_start_1             resq 1
seq_l0_α_saved          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 2
                            call        comm_stno
                            ASSIGN_STR  S_X, S_abc, Ln_0
                            jmp         Ln_0

; ======================================================================================================================
Ln_0:                       mov         edi, 3
                            call        comm_stno
                            GET_VAR     S_X
                            SUBJ_FROM16
                            test        eax, eax
                            jnz         P_1_ω
                            mov         qword [scan_start_1], 0
scan_retry_1:
                            mov         rax, [scan_start_1]
                            mov         [cursor], rax
                            jmp         P_1_α

P_1_α:                      jmp         seq_l0_α ; SEQ
P_1_β:                      jmp         seq_r0_β
seq_l0_α:                   LIT_α       lit_str_1, 3, seq_l0_α_saved, cursor, subject_data, subject_len_val, seq_r0_α, P_1_ω ; LIT α
seq_l0_β:                   LIT_β       seq_l0_α_saved, cursor, P_1_ω ; LIT β

; FAIL  α=seq_r0_α
seq_r0_α:
seq_r0_β:                   jmp         seq_l0_β

P_1_γ:                      mov         rax, [cursor]
                            mov         [scan_start_1], rax
                            jmp         L_YES_0
P_1_ω:                      cmp         qword [rel kw_anchor], 0
                            jne         L_NO_1
                            mov         rax, [scan_start_1]
                            inc         rax
                            cmp         rax, [subject_len_val]
                            jg          L_NO_1
                            mov         [scan_start_1], rax
                            jmp         scan_retry_1
                            jmp         L_NO_1

Ln_1:
;  YES =================================================================================================================
L_YES_0:                    mov         edi, 4
                            call        comm_stno
                            LOAD_STR    S_should_SP_not_SP_reach
                            FAIL_BR     Ln_2
                            SET_OUTPUT
                            jmp         Ln_2

; ======================================================================================================================
Ln_2:                       mov         edi, 5
                            call        comm_stno
                            GOTO_ALWAYS L_SNO_END     ; END

Ln_3:
;  NO ==================================================================================================================
L_NO_1:                     mov         edi, 6
                            call        comm_stno
                            LOAD_STR    S_correctly_SP_failed
                            FAIL_BR     Ln_4
                            SET_OUTPUT
                            jmp         Ln_4
Ln_4:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .data
lit_str_1            db 97, 98, 99

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_X                  db 88, 0  ; "X"
S_abc                db 97, 98, 99, 0  ; "abc"
S_FAIL               db 70, 65, 73, 76, 0  ; "FAIL"
S_YES                db 89, 69, 83, 0  ; "YES"
S_OUTPUT             db 79, 85, 84, 80, 85, 84, 0  ; "OUTPUT"
S_should_SP_not_SP_reach db 115, 104, 111, 117, 108, 100, 32, 110, 111, 116, 32, 114, 101, 97, 99, 104, 0  ; "should not reach"
S_NO                 db 78, 79, 0  ; "NO"
S_correctly_SP_failed db 99, 111, 114, 114, 101, 99, 116, 108, 121, 32, 102, 97, 105, 108, 101, 100, 0  ; "correctly failed"
S_END                db 69, 78, 68, 0  ; "END"
