; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 4
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 32
                            LOAD_REAL   F_1
                            STORE_ARG32 0
                            LOAD_REAL   F_2
                            STORE_ARG32 16
                            APPLY_FN_N  S_add, 2
                            add         rsp, 32
                            STORE_RESULT
                            STORE_ARG32 0
                            LOAD_REAL   F_3
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_0
                            jmp         Ln_0
Lf_0:                       jmp         L_e001_0

; ======================================================================================================================
Ln_0:                       mov         edi, 5
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_412_SL_001_CL_SP_2_DT_0_PL_3_DT_0
                            FAIL_BR     Lf_1
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_1:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_1:
;  e001 ================================================================================================================
L_e001_0:                   mov         edi, 6
                            call        comm_stno

; ======================================================================================================================
Ln_2:                       mov         edi, 7
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 32
                            LOAD_REAL   F_2
                            STORE_ARG32 0
                            LOAD_REAL   F_4
                            STORE_ARG32 16
                            APPLY_FN_N  S_sub, 2
                            add         rsp, 32
                            STORE_RESULT
                            STORE_ARG32 0
                            LOAD_REAL   F_1
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_3
                            jmp         Ln_3
Lf_3:                       jmp         L_e002_1

; ======================================================================================================================
Ln_3:                       mov         edi, 8
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_412_SL_002_CL_SP_3_DT_0_MI_1_DT_0
                            FAIL_BR     Lf_4
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_4:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_4:
;  e002 ================================================================================================================
L_e002_1:                   mov         edi, 9
                            call        comm_stno

; ======================================================================================================================
Ln_5:                       mov         edi, 10
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 32
                            LOAD_REAL   F_2
                            STORE_ARG32 0
                            LOAD_REAL   F_1
                            STORE_ARG32 16
                            APPLY_FN_N  S_mul, 2
                            add         rsp, 32
                            STORE_RESULT
                            STORE_ARG32 0
                            LOAD_REAL   F_5
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_6
                            jmp         Ln_6
Lf_6:                       jmp         L_e003_2

; ======================================================================================================================
Ln_6:                       mov         edi, 11
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_412_SL_003_CL_SP_3_DT_0_ST_2_DT_0
                            FAIL_BR     Lf_7
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_7:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_7:
;  e003 ================================================================================================================
L_e003_2:                   mov         edi, 12
                            call        comm_stno

; ======================================================================================================================
Ln_8:                       mov         edi, 13
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 32
                            LOAD_REAL   F_2
                            STORE_ARG32 0
                            LOAD_REAL   F_1
                            STORE_ARG32 16
                            APPLY_FN_N  S_DIVIDE_fn, 2
                            add         rsp, 32
                            STORE_RESULT
                            STORE_ARG32 0
                            LOAD_REAL   F_6
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_9
                            jmp         Ln_9
Lf_9:                       jmp         L_e004_3

; ======================================================================================================================
Ln_9:                       mov         edi, 14
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_412_SL_004_CL_SP_3_DT_0_SL_2_DT_0
                            FAIL_BR     Lf_10
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_10:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_10:
;  e004 ================================================================================================================
L_e004_3:                   mov         edi, 15
                            call        comm_stno

; ======================================================================================================================
Ln_11:                      mov         edi, 18
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 32
                            LOAD_REAL   F_2
                            STORE_ARG32 0
                            LOAD_INT    3
                            STORE_ARG32 16
                            APPLY_FN_N  S_POWER_fn, 2
                            add         rsp, 32
                            STORE_RESULT
                            STORE_ARG32 0
                            LOAD_REAL   F_7
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_12
                            jmp         Ln_12
Lf_12:                      jmp         L_e005_4

; ======================================================================================================================
Ln_12:                      mov         edi, 19
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_412_SL_005_CL_SP_3_DT_0_ST_ST_3
                            FAIL_BR     Lf_13
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_13:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_13:
;  e005 ================================================================================================================
L_e005_4:                   mov         edi, 20
                            call        comm_stno

; ======================================================================================================================
Ln_14:                      mov         edi, 23
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 16
                            LOAD_REAL   F_4
                            STORE_ARG32 0
                            APPLY_FN_N  S_neg, 1
                            add         rsp, 16
                            STORE_RESULT
                            STORE_ARG32 0
                            sub         rsp, 32
                            LOAD_REAL   F_8
                            STORE_ARG32 0
                            LOAD_REAL   F_4
                            STORE_ARG32 16
                            APPLY_FN_N  S_sub, 2
                            add         rsp, 32
                            STORE_RESULT
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_15
                            jmp         Ln_15
Lf_15:                      jmp         L_e006_5

; ======================================================================================================================
Ln_15:                      mov         edi, 24
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_412_SL_006_CL_SP_unary_SP_minus_SP_on_SP_real
                            FAIL_BR     Lf_16
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_16:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_16:
;  e006 ================================================================================================================
L_e006_5:                   mov         edi, 25
                            call        comm_stno

; ======================================================================================================================
Ln_17:                      mov         edi, 27
                            call        comm_stno
                            LOAD_STR    S_PASS_SP_412_arith_real_SP_LP_6_SL_6_RP
                            FAIL_BR     Ln_18
                            SET_OUTPUT
                            jmp         Ln_18
Ln_18:                      GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_differ             db 100, 105, 102, 102, 101, 114, 0  ; "differ"
S_output             db 111, 117, 116, 112, 117, 116, 0  ; "output"
S_FAIL_SP_412_SL_001_CL_SP_2_DT_0_PL_3_DT_0 db 70, 65, 73, 76, 32, 52, 49, 50, 47, 48, 48, 49, 58, 32, 50, 46, 48, 43, 51, 46, 48, 0  ; "FAIL 412/001: 2.0+3.0"
S_e001               db 101, 48, 48, 49, 0  ; "e001"
S_FAIL_SP_412_SL_002_CL_SP_3_DT_0_MI_1_DT_0 db 70, 65, 73, 76, 32, 52, 49, 50, 47, 48, 48, 50, 58, 32, 51, 46, 48, 45, 49, 46, 48, 0  ; "FAIL 412/002: 3.0-1.0"
S_e002               db 101, 48, 48, 50, 0  ; "e002"
S_FAIL_SP_412_SL_003_CL_SP_3_DT_0_ST_2_DT_0 db 70, 65, 73, 76, 32, 52, 49, 50, 47, 48, 48, 51, 58, 32, 51, 46, 48, 42, 50, 46, 48, 0  ; "FAIL 412/003: 3.0*2.0"
S_e003               db 101, 48, 48, 51, 0  ; "e003"
S_FAIL_SP_412_SL_004_CL_SP_3_DT_0_SL_2_DT_0 db 70, 65, 73, 76, 32, 52, 49, 50, 47, 48, 48, 52, 58, 32, 51, 46, 48, 47, 50, 46, 48, 0  ; "FAIL 412/004: 3.0/2.0"
S_e004               db 101, 48, 48, 52, 0  ; "e004"
S_FAIL_SP_412_SL_005_CL_SP_3_DT_0_ST_ST_3 db 70, 65, 73, 76, 32, 52, 49, 50, 47, 48, 48, 53, 58, 32, 51, 46, 48, 42, 42, 51, 0  ; "FAIL 412/005: 3.0**3"
S_e005               db 101, 48, 48, 53, 0  ; "e005"
S_FAIL_SP_412_SL_006_CL_SP_unary_SP_minus_SP_on_SP_real db 70, 65, 73, 76, 32, 52, 49, 50, 47, 48, 48, 54, 58, 32, 117, 110, 97, 114, 121, 32, 109, 105, 110, 117, 115, 32, 111, 110, 32, 114, 101, 97, 108, 0  ; "FAIL 412/006: unary minus on real"
S_e006               db 101, 48, 48, 54, 0  ; "e006"
S_PASS_SP_412_arith_real_SP_LP_6_SL_6_RP db 80, 65, 83, 83, 32, 52, 49, 50, 95, 97, 114, 105, 116, 104, 95, 114, 101, 97, 108, 32, 40, 54, 47, 54, 41, 0  ; "PASS 412_arith_real (6/6)"
S_end                db 101, 110, 100, 0  ; "end"
S_add                db 97, 100, 100, 0  ; "add"
S_sub                db 115, 117, 98, 0  ; "sub"
S_mul                db 109, 117, 108, 0  ; "mul"
S_DIVIDE_fn          db 68, 73, 86, 73, 68, 69, 95, 102, 110, 0  ; "DIVIDE_fn"
S_POWER_fn           db 80, 79, 87, 69, 82, 95, 102, 110, 0  ; "POWER_fn"
S_neg                db 110, 101, 103, 0  ; "neg"
F_1                  dq 0x4000000000000000  ; 2
F_2                  dq 0x4008000000000000  ; 3
F_3                  dq 0x4014000000000000  ; 5
F_4                  dq 0x3ff0000000000000  ; 1
F_5                  dq 0x4018000000000000  ; 6
F_6                  dq 0x3ff8000000000000  ; 1.5
F_7                  dq 0x403b000000000000  ; 27
F_8                  dq 0x0000000000000000  ; 0
