; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 4
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 32
                            LOAD_INT    10
                            STORE_ARG32 0
                            LOAD_INT    3
                            STORE_ARG32 16
                            APPLY_FN_N  S_remdr, 2
                            add         rsp, 32
                            STORE_RESULT
                            STORE_ARG32 0
                            LOAD_INT    1
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_0
                            jmp         Ln_0
Lf_0:                       jmp         L_e001_0

; ======================================================================================================================
Ln_0:                       mov         edi, 5
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_414_SL_001_CL_SP_remdr_LP_10_CM_3_RP
                            FAIL_BR     Lf_1
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_1:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_1:
;  e001 ================================================================================================================
L_e001_0:                   mov         edi, 6
                            call        comm_stno

; ======================================================================================================================
Ln_2:                       mov         edi, 8
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 32
                            LOAD_INT    11
                            STORE_ARG32 0
                            LOAD_INT    10
                            STORE_ARG32 16
                            APPLY_FN_N  S_remdr, 2
                            add         rsp, 32
                            STORE_RESULT
                            STORE_ARG32 0
                            LOAD_INT    1
                            STORE_ARG32 16
                            APPLY_FN_N  S_differ, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_3
                            jmp         Ln_3
Lf_3:                       jmp         L_e002_1

; ======================================================================================================================
Ln_3:                       mov         edi, 9
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_414_SL_002_CL_SP_remdr_LP_11_CM_10_RP
                            FAIL_BR     Lf_4
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_4:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_4:
;  e002 ================================================================================================================
L_e002_1:                   mov         edi, 10
                            call        comm_stno

; ======================================================================================================================
Ln_5:                       mov         edi, 12
                            call        comm_stno
                            LOAD_STR    S_PASS_SP_414_remdr_SP_LP_2_SL_2_RP
                            FAIL_BR     Ln_6
                            SET_OUTPUT
                            jmp         Ln_6
Ln_6:                       GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text
;  NAMED PATTERN BODIES ================================================================================================

section .text
;  STUB LABELS =========================================================================================================

section .rodata
; (no named pattern boxes in this program)
;  BOX RELOCATION TABLES ===============================================================================================

section .data
S_differ             db 100, 105, 102, 102, 101, 114, 0  ; "differ"
S_remdr              db 114, 101, 109, 100, 114, 0  ; "remdr"
S_output             db 111, 117, 116, 112, 117, 116, 0  ; "output"
S_FAIL_SP_414_SL_001_CL_SP_remdr_LP_10_CM_3_RP db 70, 65, 73, 76, 32, 52, 49, 52, 47, 48, 48, 49, 58, 32, 114, 101, 109, 100, 114, 40, 49, 48, 44, 51, 41, 0  ; "FAIL 414/001: remdr(10,3)"
S_e001               db 101, 48, 48, 49, 0  ; "e001"
S_FAIL_SP_414_SL_002_CL_SP_remdr_LP_11_CM_10_RP db 70, 65, 73, 76, 32, 52, 49, 52, 47, 48, 48, 50, 58, 32, 114, 101, 109, 100, 114, 40, 49, 49, 44, 49, 48, 41, 0  ; "FAIL 414/002: remdr(11,10)"
S_e002               db 101, 48, 48, 50, 0  ; "e002"
S_PASS_SP_414_remdr_SP_LP_2_SL_2_RP db 80, 65, 83, 83, 32, 52, 49, 52, 95, 114, 101, 109, 100, 114, 32, 40, 50, 47, 50, 41, 0  ; "PASS 414_remdr (2/2)"
S_end                db 101, 110, 100, 0  ; "end"
