/*
 * test_snocone_parse_i.c — GOAL-SNOCONE-LANG-SPACE LS-4.i acceptance test
 *
 * Sub-step LS-4.i.1: `goto LABEL;` and `LABEL:` prefix.            (tests 1–15)
 * Sub-step LS-4.i.2: `break;` `break LABEL;` `continue;` `continue LABEL;`.
 *                                                                  (tests 16–31)
 * Sub-step LS-4.i.3: `switch (e) { case v1: ... case v2: ... default: ... }`.
 *                                                                  (tests 32–45)
 * Sub-step LS-4.i.4: alt-eval `(a, b, c)` → AST_VLIST + `()` → AST_NUL.
 *                                                                  (tests 46–58)
 * Sub-step LS-4.i.5: `struct NAME { f1, f2, ... }` → DATA('NAME(f1,f2,...)').
 *                                                                  (tests 59–69)
 *
 * LS-4.i.1 lowering shapes:
 *
 *   goto NAME ;        ->   :(NAME)        (bare goto-uncond stmt; no subject)
 *
 *   NAME : stmt        ->   NAME           (label pad: subject=NULL,
 *                          <stmts of stmt>  go=NULL, label=NAME)
 *                          + the inner stmt's stmts immediately following.
 *                          Per SNOBOL4 semantics, a label on a label-only
 *                          pad chains to the next non-empty stmt — so
 *                          jumping to NAME lands on the inner stmt.
 *
 * LS-4.i.2 lowering shapes (loop frames are pushed at while/do/for head and
 * popped at finalize; each frame carries a cont_label and end_label, plus
 * any user labels that immediately preceded the head):
 *
 *   break ;            ->   :(end_label_of_innermost_frame)
 *   break LABEL ;      ->   :(end_label_of_frame_tagged_by_user_LABEL)
 *   continue ;         ->   :(cont_label_of_innermost_LOOP_frame)
 *   continue LABEL ;   ->   :(cont_label_of_LOOP_frame_tagged_by_user_LABEL)
 *
 * `while`'s cont_label IS the synthetic `_Ltop_NNNN` (the back-edge target),
 * always emitted.  `do/while` and `for` use a separate `_Lcont_NNNN` pad,
 * lazy-emitted by sc_finalize_* only when at least one `continue` inside the
 * body referenced it (frame's `cont_used` flag).  This keeps the IR shape of
 * non-continue do/for byte-identical to the LS-4.f / LS-4.g lowering — every
 * pre-existing parse-{f,g} test stays green without modification.
 *
 * Out-of-context `break;` / `continue;` and unresolved-label cases call
 * sc_error(); snocone_parse_program returns NULL with state.nerrors > 0.
 *
 * Label declarations and goto targets are user names verbatim.  No
 * synthetic prefixing or mangling — `top` stays `top`.  Synthetic
 * labels generated by control-flow lowering (`_Lend_NNNN` etc.) carry
 * a leading underscore that user labels cannot, so collisions are
 * impossible by construction.
 *
 * Side-channel test — the LS-4.i parser is not yet wired into scrip's
 * production driver path (that happens at LS-4.j).
 *
 * AUTHORS: Lon Jones Cherryholmes · Claude Sonnet
 * Commit identity: LCherryholmes / lcherryh@yahoo.com  (RULES.md)
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define IR_DEFINE_NAMES
#include "scrip_cc.h"

Program *snocone_parse_program(const char *src, const char *filename);

/* ---- harness ---- */
static int g_pass = 0, g_fail = 0;

#define ASSERT(cond, fmt, ...) do { \
    if (cond) { g_pass++; } \
    else { fprintf(stderr, "FAIL %s:%d: " fmt "\n", __func__, __LINE__, ##__VA_ARGS__); g_fail++; } \
} while(0)

/* Walk the linked-list and collect a STMT_t* array (caller must free). */
static STMT_t **collect_stmts(Program *prog, int *out_n) {
    int n = 0;
    for (STMT_t *s = prog->head; s; s = s->next) n++;
    STMT_t **arr = calloc(n, sizeof *arr);
    int i = 0;
    for (STMT_t *s = prog->head; s; s = s->next) arr[i++] = s;
    *out_n = n;
    return arr;
}

/* True if stmt is a bare label-only landing pad (no subject, no goto). */
static int is_label_pad(STMT_t *s) { return s->label && !s->subject && !s->go; }
/* True if stmt is a goto-only statement (no subject). */
static int is_goto_uncond(STMT_t *s) { return s->go && s->go->uncond && !s->subject; }
/* True if stmt is a bare expression (subject, no goto). */
static int is_bare_expr(STMT_t *s) { return s->subject && !s->go; }
/* True if stmt is an assignment (subject + replacement, has_eq). */
static int is_assignment(STMT_t *s) { return s->subject && s->replacement && s->has_eq; }

/* =========================================================================
 * Test 1 — bare goto
 *   goto top;
 *   Expected:
 *     stmt[0] :(top)             (goto-uncond, no subject)
 * ========================================================================= */
static void test_goto_bare(void) {
    Program *prog = snocone_parse_program("goto top;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) {
        ASSERT(is_goto_uncond(stmts[0]), "stmt[0] should be goto-uncond");
        ASSERT(stmts[0]->go && stmts[0]->go->uncond &&
               strcmp(stmts[0]->go->uncond, "top") == 0,
               "goto target should be \"top\", got %s",
               stmts[0]->go && stmts[0]->go->uncond ? stmts[0]->go->uncond : "(null)");
        ASSERT(stmts[0]->subject == NULL, "goto stmt should have no subject");
        ASSERT(stmts[0]->label == NULL, "goto stmt should have no label");
    }
    free(stmts);
}

/* =========================================================================
 * Test 2 — goto inside a sequence
 *   x = 1; goto fin; y = 2;
 *   Expected:
 *     stmt[0] x = 1
 *     stmt[1] :(fin)
 *     stmt[2] y = 2
 * ========================================================================= */
static void test_goto_in_sequence(void) {
    Program *prog = snocone_parse_program("x = 1; goto fin; y = 2;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) ASSERT(is_assignment(stmts[0]), "stmt[0] should be assignment");
    if (n >= 2) {
        ASSERT(is_goto_uncond(stmts[1]), "stmt[1] should be goto");
        ASSERT(stmts[1]->go && stmts[1]->go->uncond &&
               strcmp(stmts[1]->go->uncond, "fin") == 0,
               "goto target should be \"fin\"");
    }
    if (n >= 3) ASSERT(is_assignment(stmts[2]), "stmt[2] should be assignment");
    free(stmts);
}

/* =========================================================================
 * Test 3 — bare label before assignment
 *   top: x = 1;
 *   Expected:
 *     stmt[0] top                (label pad — chains to stmt[1] semantically)
 *     stmt[1] x = 1
 * ========================================================================= */
static void test_label_before_assign(void) {
    Program *prog = snocone_parse_program("top: x = 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 2, "expected 2 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "top") == 0,
               "stmt[0] label should be \"top\", got %s",
               stmts[0]->label ? stmts[0]->label : "(null)");
    }
    if (n >= 2) ASSERT(is_assignment(stmts[1]), "stmt[1] should be assignment");
    free(stmts);
}

/* =========================================================================
 * Test 4 — label + goto round-trip
 *   top: x = 1; goto top;
 *   Expected:
 *     stmt[0] top
 *     stmt[1] x = 1
 *     stmt[2] :(top)
 * ========================================================================= */
static void test_label_and_goto_loop(void) {
    Program *prog = snocone_parse_program("top: x = 1; goto top;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "top") == 0,
               "stmt[0] label should be \"top\"");
    }
    if (n >= 2) ASSERT(is_assignment(stmts[1]), "stmt[1] should be assignment");
    if (n >= 3) {
        ASSERT(is_goto_uncond(stmts[2]), "stmt[2] should be goto-uncond");
        ASSERT(stmts[2]->go && stmts[2]->go->uncond &&
               strcmp(stmts[2]->go->uncond, "top") == 0,
               "goto target should be \"top\"");
    }
    free(stmts);
}

/* =========================================================================
 * Test 5 — label before block
 *   header: { x = 1; y = 2; }
 *   Expected:
 *     stmt[0] header              (label pad)
 *     stmt[1] x = 1
 *     stmt[2] y = 2
 * ========================================================================= */
static void test_label_before_block(void) {
    Program *prog = snocone_parse_program("header: { x = 1; y = 2; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "header") == 0,
               "stmt[0] label should be \"header\"");
    }
    free(stmts);
}

/* =========================================================================
 * Test 6 — label before if-stmt
 *   skip_it: if (DIFFER(x)) { y = 1; }
 *   Expected:
 *     stmt[0] skip_it             (user label pad)
 *     stmt[1] DIFFER(x)  :F(_Lend_0001)
 *     stmt[2] y = 1
 *     stmt[3] _Lend_0001          (synthetic if-end label)
 * ========================================================================= */
static void test_label_before_if(void) {
    Program *prog = snocone_parse_program(
        "skip_it: if (DIFFER(x)) { y = 1; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 4, "expected 4 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "skip_it") == 0,
               "stmt[0] label should be \"skip_it\"");
    }
    if (n >= 2) {
        /* cond stmt with onfailure target */
        ASSERT(stmts[1]->subject != NULL, "stmt[1] should have subject");
        ASSERT(stmts[1]->go && stmts[1]->go->onfailure,
               "stmt[1] should have onfailure goto");
    }
    free(stmts);
}

/* =========================================================================
 * Test 7 — label before while-stmt (interaction with synthetic _Ltop)
 *   user_top: while (DIFFER(x)) { x = x; }
 *   Expected:
 *     stmt[0] user_top                  (USER label pad — first)
 *     stmt[1] _Ltop_0001                (synthetic loop top — second)
 *     stmt[2] DIFFER(x)  :F(_Lend_0002)
 *     stmt[3] x = x
 *     stmt[4] :(_Ltop_0001)             (back-edge to synthetic top)
 *     stmt[5] _Lend_0002                (synthetic loop end pad)
 *
 *   The user label `user_top` sits BEFORE the synthetic `_Ltop_NNNN`
 *   pad — so `goto user_top;` from elsewhere lands on the
 *   synthetic top via SNOBOL4's label-chaining (label-only pads
 *   chain forward to the next non-empty stmt, which is the
 *   cond stmt — same effective entry as the synthetic top).
 * ========================================================================= */
static void test_label_before_while(void) {
    Program *prog = snocone_parse_program(
        "user_top: while (DIFFER(x)) { x = x; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 6, "expected 6 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be user label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "user_top") == 0,
               "stmt[0] label should be \"user_top\", got %s",
               stmts[0]->label ? stmts[0]->label : "(null)");
    }
    if (n >= 2) {
        ASSERT(is_label_pad(stmts[1]), "stmt[1] should be synthetic _Ltop pad");
        ASSERT(stmts[1]->label && strncmp(stmts[1]->label, "_Ltop_", 6) == 0,
               "stmt[1] label should start with _Ltop_, got %s",
               stmts[1]->label ? stmts[1]->label : "(null)");
    }
    free(stmts);
}

/* =========================================================================
 * Test 8 — multiple goto targets / no collision
 *   x = 1; goto a; goto b; goto c;
 *   Expected: stmt[0..3] subject/goto sequence with three distinct uncond targets.
 * ========================================================================= */
static void test_multiple_goto_targets(void) {
    Program *prog = snocone_parse_program("x = 1; goto a; goto b; goto c;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 4, "expected 4 stmts, got %d", n);
    if (n >= 4) {
        ASSERT(is_assignment(stmts[0]), "stmt[0] should be assignment");
        ASSERT(is_goto_uncond(stmts[1]) && stmts[1]->go &&
               strcmp(stmts[1]->go->uncond, "a") == 0, "stmt[1] should be :(a)");
        ASSERT(is_goto_uncond(stmts[2]) && stmts[2]->go &&
               strcmp(stmts[2]->go->uncond, "b") == 0, "stmt[2] should be :(b)");
        ASSERT(is_goto_uncond(stmts[3]) && stmts[3]->go &&
               strcmp(stmts[3]->go->uncond, "c") == 0, "stmt[3] should be :(c)");
    }
    free(stmts);
}

/* =========================================================================
 * Test 9 — multiple labels at consecutive positions
 *   first: second: x = 1;
 *   Expected:
 *     stmt[0] first
 *     stmt[1] second
 *     stmt[2] x = 1
 *
 *   Stacked labels via the recursive `label_decl matched_stmt` rule.
 *   In SPITBOL terms both labels chain forward to the assignment.
 * ========================================================================= */
static void test_stacked_labels(void) {
    Program *prog = snocone_parse_program("first: second: x = 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "first") == 0,
               "stmt[0] label should be \"first\"");
    }
    if (n >= 2) {
        ASSERT(is_label_pad(stmts[1]), "stmt[1] should be label pad");
        ASSERT(stmts[1]->label && strcmp(stmts[1]->label, "second") == 0,
               "stmt[1] label should be \"second\"");
    }
    if (n >= 3) ASSERT(is_assignment(stmts[2]), "stmt[2] should be assignment");
    free(stmts);
}

/* =========================================================================
 * Test 10 — label before empty stmt
 *   pad: ;
 *   Expected: just stmt[0] = label pad (the trailing `;` is empty stmt,
 *             which appends nothing).
 * ========================================================================= */
static void test_label_before_empty_stmt(void) {
    Program *prog = snocone_parse_program("pad: ;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) {
        ASSERT(is_label_pad(stmts[0]), "stmt[0] should be label pad");
        ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "pad") == 0,
               "stmt[0] label should be \"pad\"");
    }
    free(stmts);
}

/* =========================================================================
 * Test 11 — label inside a function body
 *   function F() { again: x = 1; goto again; }
 *   Expected:
 *     stmt[0] DEFINE('F()')
 *     stmt[1] :(F_end)
 *     stmt[2] F           (entry-point label)
 *     stmt[3] again       (user label)
 *     stmt[4] x = 1
 *     stmt[5] :(again)
 *     stmt[6] F_end
 * ========================================================================= */
static void test_label_inside_function(void) {
    Program *prog = snocone_parse_program(
        "function F() { again: x = 1; goto again; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 7, "expected 7 stmts, got %d", n);
    if (n >= 1) ASSERT(is_bare_expr(stmts[0]), "stmt[0] should be DEFINE bare-expr");
    if (n >= 2) ASSERT(is_goto_uncond(stmts[1]), "stmt[1] should be skip-goto");
    if (n >= 3) {
        ASSERT(is_label_pad(stmts[2]), "stmt[2] should be entry label F");
        ASSERT(stmts[2]->label && strcmp(stmts[2]->label, "F") == 0,
               "stmt[2] label should be \"F\"");
    }
    if (n >= 4) {
        ASSERT(is_label_pad(stmts[3]), "stmt[3] should be user label again");
        ASSERT(stmts[3]->label && strcmp(stmts[3]->label, "again") == 0,
               "stmt[3] label should be \"again\"");
    }
    if (n >= 5) ASSERT(is_assignment(stmts[4]), "stmt[4] should be assignment");
    if (n >= 6) {
        ASSERT(is_goto_uncond(stmts[5]), "stmt[5] should be goto");
        ASSERT(stmts[5]->go && stmts[5]->go->uncond &&
               strcmp(stmts[5]->go->uncond, "again") == 0,
               "stmt[5] target should be \"again\"");
    }
    if (n >= 7) {
        ASSERT(is_label_pad(stmts[6]), "stmt[6] should be F_end pad");
        ASSERT(stmts[6]->label && strcmp(stmts[6]->label, "F_end") == 0,
               "stmt[6] label should be \"F_end\"");
    }
    free(stmts);
}

/* =========================================================================
 * Test 12 — pre-existing stmts before label preserved
 *   x = 0; user: y = 1;
 *   Expected:
 *     stmt[0] x = 0
 *     stmt[1] user            (label pad)
 *     stmt[2] y = 1
 * ========================================================================= */
static void test_label_with_preceding_stmts(void) {
    Program *prog = snocone_parse_program("x = 0; user: y = 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) ASSERT(is_assignment(stmts[0]), "stmt[0] should be x=0");
    if (n >= 2) {
        ASSERT(is_label_pad(stmts[1]), "stmt[1] should be label pad");
        ASSERT(stmts[1]->label && strcmp(stmts[1]->label, "user") == 0,
               "stmt[1] label should be \"user\"");
    }
    if (n >= 3) ASSERT(is_assignment(stmts[2]), "stmt[2] should be y=1");
    free(stmts);
}

/* =========================================================================
 * Test 13 — labels with whitespace variations
 *   "name :stmt" and "name: stmt" and "name :stmt" and "name :   stmt"
 *   should all produce the same shape — colon is just a token, not
 *   whitespace-sensitive at this level.
 * ========================================================================= */
static void test_label_whitespace_variants(void) {
    const char *variants[] = {
        "L: x = 1;",
        "L : x = 1;",
        "L  :  x = 1;",
        "L :x = 1;",
    };
    for (size_t i = 0; i < sizeof variants / sizeof variants[0]; i++) {
        Program *prog = snocone_parse_program(variants[i], "test");
        ASSERT(prog != NULL, "variant %zu parse failed: %s", i, variants[i]);
        if (!prog) continue;
        int n; STMT_t **stmts = collect_stmts(prog, &n);
        ASSERT(n == 2, "variant %zu expected 2 stmts, got %d", i, n);
        if (n >= 1) {
            ASSERT(is_label_pad(stmts[0]), "variant %zu stmt[0] should be label pad", i);
            ASSERT(stmts[0]->label && strcmp(stmts[0]->label, "L") == 0,
                   "variant %zu stmt[0] label should be \"L\"", i);
        }
        free(stmts);
    }
}

/* =========================================================================
 * Test 14 — goto whitespace variations
 * ========================================================================= */
static void test_goto_whitespace_variants(void) {
    const char *variants[] = {
        "goto top;",
        "goto  top ;",
        "goto\ttop;",
    };
    for (size_t i = 0; i < sizeof variants / sizeof variants[0]; i++) {
        Program *prog = snocone_parse_program(variants[i], "test");
        ASSERT(prog != NULL, "variant %zu parse failed: %s", i, variants[i]);
        if (!prog) continue;
        int n; STMT_t **stmts = collect_stmts(prog, &n);
        ASSERT(n == 1, "variant %zu expected 1 stmt, got %d", i, n);
        if (n >= 1) {
            ASSERT(is_goto_uncond(stmts[0]), "variant %zu stmt[0] should be goto", i);
            ASSERT(stmts[0]->go && stmts[0]->go->uncond &&
                   strcmp(stmts[0]->go->uncond, "top") == 0,
                   "variant %zu target should be \"top\"", i);
        }
        free(stmts);
    }
}

/* =========================================================================
 * Test 15 — label inside while body
 *   while (DIFFER(x)) { inner: x = x; }
 *   Inner label should appear inside the loop body, after the loop's
 *   cond stmt, before the body assignment, before the back-edge goto.
 * ========================================================================= */
static void test_label_inside_while(void) {
    Program *prog = snocone_parse_program(
        "while (DIFFER(x)) { inner: x = x; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /*  stmt[0] _Ltop pad
     *  stmt[1] cond :F(_Lend)
     *  stmt[2] inner pad           (user label)
     *  stmt[3] x = x
     *  stmt[4] :(_Ltop)
     *  stmt[5] _Lend pad
     */
    ASSERT(n == 6, "expected 6 stmts, got %d", n);
    if (n >= 3) {
        ASSERT(is_label_pad(stmts[2]), "stmt[2] should be user label \"inner\"");
        ASSERT(stmts[2]->label && strcmp(stmts[2]->label, "inner") == 0,
               "stmt[2] label should be \"inner\", got %s",
               stmts[2]->label ? stmts[2]->label : "(null)");
    }
    free(stmts);
}

/* =========================================================================
 * LS-4.i.2 helpers — count gotos targeting a given label name; check label
 * presence; locate the goto-uncond stmt with a given target.
 * ========================================================================= */
static int count_gotos_to(STMT_t **stmts, int n, const char *target) {
    int c = 0;
    for (int i = 0; i < n; i++) {
        if (stmts[i]->go && stmts[i]->go->uncond &&
            strcmp(stmts[i]->go->uncond, target) == 0) c++;
    }
    return c;
}
static int count_labels_with_prefix(STMT_t **stmts, int n, const char *prefix) {
    int c = 0;
    size_t plen = strlen(prefix);
    for (int i = 0; i < n; i++) {
        if (stmts[i]->label && strncmp(stmts[i]->label, prefix, plen) == 0) c++;
    }
    return c;
}
static const char *find_label_with_prefix(STMT_t **stmts, int n, const char *prefix) {
    size_t plen = strlen(prefix);
    for (int i = 0; i < n; i++) {
        if (stmts[i]->label && strncmp(stmts[i]->label, prefix, plen) == 0)
            return stmts[i]->label;
    }
    return NULL;
}

/* =========================================================================
 * Test 16 — bare break in while
 *   while (DIFFER(x)) { break; }
 *   While allocates _Ltop_0001 (cont) + _Lend_0002 (break target).
 *   Body's break; lowers to :(_Lend_0002).
 *   Expected stmt sequence:
 *     [0] _Ltop_0001 pad
 *     [1] DIFFER(x) :F(_Lend_0002)
 *     [2] :(_Lend_0002)         (the break)
 *     [3] :(_Ltop_0001)         (back-edge)
 *     [4] _Lend_0002 pad
 * ========================================================================= */
static void test_break_bare_in_while(void) {
    Program *prog = snocone_parse_program("while (DIFFER(x)) { break; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 5, "expected 5 stmts, got %d", n);
    /* exactly one goto :(_Lend_0002), the break */
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 1,
           "expected exactly one break goto to _Lend_0002");
    /* exactly one goto :(_Ltop_0001), the back-edge */
    ASSERT(count_gotos_to(stmts, n, "_Ltop_0001") == 1,
           "expected exactly one back-edge goto to _Ltop_0001");
    free(stmts);
}

/* =========================================================================
 * Test 17 — bare continue in while
 *   while (DIFFER(x)) { continue; }
 *   For while, the cont_label IS the back-edge label _Ltop_0001.  So
 *   `continue;` lowers to :(_Ltop_0001) — same target as the natural
 *   back-edge.  We expect TWO gotos to _Ltop_0001 (continue + back-edge).
 * ========================================================================= */
static void test_continue_bare_in_while(void) {
    Program *prog = snocone_parse_program("while (DIFFER(x)) { continue; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_gotos_to(stmts, n, "_Ltop_0001") == 2,
           "expected 2 gotos to _Ltop_0001 (continue + back-edge), got %d",
           count_gotos_to(stmts, n, "_Ltop_0001"));
    /* No spurious _Lcont pad — while reuses _Ltop as cont target. */
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcont") == 0,
           "while-loop continue must not emit a separate _Lcont pad");
    free(stmts);
}

/* =========================================================================
 * Test 18 — break + continue inside do/while
 *   do { break; continue; } while (DIFFER(x));
 *   do/while uses a separate _Lcont_NNNN pad spliced just before the cond.
 *   `break;` -> :(_Lend_NNNN), `continue;` -> :(_Lcont_NNNN).
 * ========================================================================= */
static void test_break_continue_in_dowhile(void) {
    Program *prog = snocone_parse_program(
        "do { break; continue; } while (DIFFER(x));", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* exactly one Lcont pad lazy-emitted because cont_used=1 */
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcont") == 1,
           "do/while+continue must emit exactly one _Lcont pad, got %d",
           count_labels_with_prefix(stmts, n, "_Lcont"));
    /* find the actual label name and assert a goto to it */
    const char *lcont = find_label_with_prefix(stmts, n, "_Lcont");
    const char *lend  = find_label_with_prefix(stmts, n, "_Lend");
    ASSERT(lcont != NULL, "should have a _Lcont label");
    ASSERT(lend != NULL,  "should have a _Lend label");
    if (lcont) ASSERT(count_gotos_to(stmts, n, lcont) == 1,
                      "expected one goto to %s (the continue)", lcont);
    if (lend)  ASSERT(count_gotos_to(stmts, n, lend) == 1,
                      "expected one goto to %s (the break)", lend);
    free(stmts);
}

/* =========================================================================
 * Test 19 — break + continue inside for-loop
 *   for (i = 0; LT(i, 10); i = i + 1) { break; continue; }
 *   for-loop uses a separate _Lcont_NNNN pad spliced just before the step.
 *   `break;` -> :(_Lend_NNNN), `continue;` -> :(_Lcont_NNNN).
 * ========================================================================= */
static void test_break_continue_in_for(void) {
    Program *prog = snocone_parse_program(
        "for (i = 0; LT(i, 10); i = i + 1) { break; continue; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* exactly one Lcont pad lazy-emitted */
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcont") == 1,
           "for+continue must emit exactly one _Lcont pad, got %d",
           count_labels_with_prefix(stmts, n, "_Lcont"));
    const char *lcont = find_label_with_prefix(stmts, n, "_Lcont");
    const char *lend  = find_label_with_prefix(stmts, n, "_Lend");
    ASSERT(lcont != NULL, "should have a _Lcont label");
    ASSERT(lend != NULL,  "should have a _Lend label");
    if (lcont) ASSERT(count_gotos_to(stmts, n, lcont) == 1,
                      "expected one goto to %s (the continue)", lcont);
    if (lend)  ASSERT(count_gotos_to(stmts, n, lend) == 1,
                      "expected one goto to %s (the break)", lend);
    free(stmts);
}

/* =========================================================================
 * Test 20 — for-loop WITHOUT continue: lazy-emit suppressed
 *   for (i = 0; LT(i, 10); i = i + 1) { x = x + i; }
 *   No continue in body -> frame's cont_used flag stays 0 -> finalize
 *   does NOT splice a _Lcont pad.  The IR shape must be byte-identical
 *   to the LS-4.g for-loop lowering (parse-g 95/95 stays green).
 * ========================================================================= */
static void test_for_no_continue_lazy_suppressed(void) {
    Program *prog = snocone_parse_program(
        "for (i = 0; LT(i, 10); i = i + 1) { x = x + i; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcont") == 0,
           "for without continue must NOT emit a _Lcont pad (lazy-emit), got %d",
           count_labels_with_prefix(stmts, n, "_Lcont"));
    free(stmts);
}

/* =========================================================================
 * Test 21 — do/while WITHOUT continue: lazy-emit suppressed
 *   do { x = x + 1; } while (DIFFER(x));
 *   Same lazy-emit invariant as Test 20, for do/while.
 * ========================================================================= */
static void test_dowhile_no_continue_lazy_suppressed(void) {
    Program *prog = snocone_parse_program(
        "do { x = x + 1; } while (DIFFER(x));", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcont") == 0,
           "do/while without continue must NOT emit a _Lcont pad (lazy-emit), got %d",
           count_labels_with_prefix(stmts, n, "_Lcont"));
    free(stmts);
}

/* =========================================================================
 * Test 22 — for-loop WITH continue: lazy-emit triggered
 *   for (i = 0; LT(i, 10); i = i + 1) { continue; }
 *   continue in body sets frame's cont_used=1 -> finalize splices
 *   _Lcont_NNNN pad just before the step stmt.
 * ========================================================================= */
static void test_for_with_continue_lazy_emitted(void) {
    Program *prog = snocone_parse_program(
        "for (i = 0; LT(i, 10); i = i + 1) { continue; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcont") == 1,
           "for+continue must emit exactly one _Lcont pad, got %d",
           count_labels_with_prefix(stmts, n, "_Lcont"));
    free(stmts);
}

/* =========================================================================
 * Test 23 — do/while WITH continue: lazy-emit triggered
 *   do { continue; } while (DIFFER(x));
 *   Same as Test 22, for do/while.
 * ========================================================================= */
static void test_dowhile_with_continue_lazy_emitted(void) {
    Program *prog = snocone_parse_program(
        "do { continue; } while (DIFFER(x));", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcont") == 1,
           "do/while+continue must emit exactly one _Lcont pad, got %d",
           count_labels_with_prefix(stmts, n, "_Lcont"));
    free(stmts);
}

/* =========================================================================
 * Test 24 — labeled break across nested while loops
 *   outer: while (DIFFER(x)) { while (DIFFER(y)) { break outer; } }
 *   `break outer` must target the OUTER loop's _Lend (not inner's).
 *   Outer is allocated first: _Ltop_0001 / _Lend_0002.
 *   Inner second: _Ltop_0003 / _Lend_0004.
 *   `break outer` -> :(_Lend_0002), not :(_Lend_0004).
 * ========================================================================= */
static void test_labeled_break_nested_loops(void) {
    Program *prog = snocone_parse_program(
        "outer: while (DIFFER(x)) { while (DIFFER(y)) { break outer; } }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* outer label sits at the very front (label-decl emits before head). */
    ASSERT(n >= 1 && stmts[0]->label && strcmp(stmts[0]->label, "outer") == 0,
           "stmt[0] should be user label 'outer', got %s",
           (n >= 1 && stmts[0]->label) ? stmts[0]->label : "(null)");
    /* The break-outer goto targets the OUTER's end label.  Outer is allocated
     * first -> _Lend_0002.  Inner -> _Lend_0004.  We assert exactly one goto
     * to _Lend_0002 (the break) and zero gotos to _Lend_0004 (no break in
     * inner) — and the inner's natural fall-out goto is :(_Lend_0002) NO,
     * actually inner's back-edge is :(_Ltop_0003).  Plain inner _Lend_0004 is
     * a pad with one cond :F to it.  The ONLY goto to _Lend_0002 is the break. */
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 1,
           "expected exactly 1 goto to _Lend_0002 (break outer), got %d",
           count_gotos_to(stmts, n, "_Lend_0002"));
    /* Both end labels exist. */
    int lend_count = count_labels_with_prefix(stmts, n, "_Lend");
    ASSERT(lend_count == 2, "expected 2 _Lend pads (one per loop), got %d", lend_count);
    free(stmts);
}

/* =========================================================================
 * Test 25 — labeled continue across nested while loops
 *   outer: while (DIFFER(x)) { while (DIFFER(y)) { continue outer; } }
 *   `continue outer` -> :(_Ltop_0001) (outer's cont_label = its back-edge).
 *   Inner has no continue, so no _Lcont pad emitted (while uses _Ltop as
 *   cont target — separate _Lcont pads only for do/while/for).
 *   _Ltop_0001 should be the target of TWO gotos: outer back-edge + the
 *   continue.  Inner _Ltop_0003 is targeted by exactly one goto: inner
 *   back-edge.
 * ========================================================================= */
static void test_labeled_continue_nested_loops(void) {
    Program *prog = snocone_parse_program(
        "outer: while (DIFFER(x)) { while (DIFFER(y)) { continue outer; } }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_gotos_to(stmts, n, "_Ltop_0001") == 2,
           "expected 2 gotos to outer _Ltop_0001 (back-edge + continue), got %d",
           count_gotos_to(stmts, n, "_Ltop_0001"));
    ASSERT(count_gotos_to(stmts, n, "_Ltop_0003") == 1,
           "expected 1 goto to inner _Ltop_0003 (back-edge only), got %d",
           count_gotos_to(stmts, n, "_Ltop_0003"));
    /* No separate _Lcont pad — both loops are while. */
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcont") == 0,
           "while loops must not emit _Lcont pads");
    free(stmts);
}

/* =========================================================================
 * Test 26 — stacked user labels on a single loop, break by FIRST label
 *   a: b: while (DIFFER(x)) { break a; }
 *   Both `a` and `b` are pushed onto the same loop frame's user_labels[].
 *   `break a` -> :(_Lend_0002).
 * ========================================================================= */
static void test_stacked_labels_break_first(void) {
    Program *prog = snocone_parse_program(
        "a: b: while (DIFFER(x)) { break a; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* user labels stay attached as label-pads at the head — first 'a' then 'b' */
    ASSERT(n >= 2 && stmts[0]->label && strcmp(stmts[0]->label, "a") == 0,
           "stmt[0] should be label pad 'a'");
    ASSERT(n >= 2 && stmts[1]->label && strcmp(stmts[1]->label, "b") == 0,
           "stmt[1] should be label pad 'b'");
    /* break a; -> goto :(_Lend_0002) */
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 1,
           "expected 1 goto to _Lend_0002 (break a), got %d",
           count_gotos_to(stmts, n, "_Lend_0002"));
    free(stmts);
}

/* =========================================================================
 * Test 27 — stacked user labels, break by SECOND label (same loop)
 *   a: b: while (DIFFER(x)) { break b; }
 *   `break b` resolves to the SAME loop frame as `break a` (both labels
 *   attach to the same frame's user_labels[]).  Same _Lend_0002 target.
 * ========================================================================= */
static void test_stacked_labels_break_second(void) {
    Program *prog = snocone_parse_program(
        "a: b: while (DIFFER(x)) { break b; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 1,
           "expected 1 goto to _Lend_0002 (break b targets same loop as break a)");
    free(stmts);
}

/* =========================================================================
 * Test 28 — label-on-non-loop-stmt disambiguation
 *   a: x = 1; while (DIFFER(y)) { z = 1; }
 *   Label `a` attaches to the assignment (label-eager-emit puts an `a` pad
 *   stmt before the assignment); the subsequent `while` head sees an EMPTY
 *   pending-user-labels list because `sc_append_stmt` cleared it on the
 *   assignment commit.  Therefore the loop frame has zero user_labels —
 *   `break a;` from inside the loop body would be a parse error (Test 29
 *   covers that).
 *
 *   Here we just verify the IR shape:
 *     [0] a pad (label only)
 *     [1] x = 1 (assignment — no label, has_eq)
 *     [2..] _Ltop / cond / body / back-edge / _Lend
 *   So the ONLY user-named label pad in the IR is `a`, and it sits BEFORE
 *   the synthetic _Ltop pad.
 * ========================================================================= */
static void test_label_on_non_loop_stmt_disambiguation(void) {
    Program *prog = snocone_parse_program(
        "a: x = 1; while (DIFFER(y)) { z = 1; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* stmt[0] is `a` label pad */
    ASSERT(n >= 1, "should have at least 1 stmt");
    ASSERT(n >= 1 && is_label_pad(stmts[0]), "stmt[0] should be label pad");
    ASSERT(n >= 1 && stmts[0]->label && strcmp(stmts[0]->label, "a") == 0,
           "stmt[0] label should be 'a'");
    /* stmt[1] is the assignment x = 1 — no label */
    ASSERT(n >= 2 && is_assignment(stmts[1]) && stmts[1]->label == NULL,
           "stmt[1] should be unlabeled assignment");
    /* The synthetic _Ltop pad must NOT carry the user label 'a' */
    const char *ltop = find_label_with_prefix(stmts, n, "_Ltop_");
    ASSERT(ltop != NULL, "should have a _Ltop pad");
    /* No user label is on the _Ltop stmt itself — that is, the _Ltop pad
     * is a SEPARATE stmt from the 'a' pad.  Verified by stmt[0]->label
     * being 'a' (not _Ltop).  All good. */
    free(stmts);
}

/* =========================================================================
 * Test 29 — labeled break to non-loop-tagged label is a parse error
 *   a: x = 1; while (DIFFER(y)) { break a; }
 *   `a` is attached to the bare assignment, not to the loop.  `break a;`
 *   inside the loop body therefore finds NO loop frame tagged `a` and
 *   sc_error fires.  Parse must fail (NULL return).
 * ========================================================================= */
static void test_break_label_attached_to_non_loop_error(void) {
    Program *prog = snocone_parse_program(
        "a: x = 1; while (DIFFER(y)) { break a; }", "test");
    ASSERT(prog == NULL, "parse must fail: 'a' is attached to bare stmt, not loop");
}

/* =========================================================================
 * Test 30 — break outside any loop: parse error
 *   break;
 * ========================================================================= */
static void test_break_outside_loop_error(void) {
    Program *prog = snocone_parse_program("break;", "test");
    ASSERT(prog == NULL, "bare break; at top level must fail");
}

/* =========================================================================
 * Test 31 — continue outside any loop: parse error
 *   continue;
 * ========================================================================= */
static void test_continue_outside_loop_error(void) {
    Program *prog = snocone_parse_program("continue;", "test");
    ASSERT(prog == NULL, "bare continue; at top level must fail");
}

/* =========================================================================
 * LS-4.i.3 — switch / case / default tests (32–45)
 *
 * Lowering shape (per Q6 — modern no-fall-through, implicit break at end
 * of each case body except the last):
 *
 *   switch (e) { case v1: A; case v2: B; default: D; }
 *
 *     tmp = e
 *     IDENT(tmp, v1)        :S(_Lcase_NNNN)
 *     IDENT(tmp, v2)        :S(_Lcase_NNNN)
 *                           :(_Ldefault_NNNN)        <- catch-all goto
 *     _Lcase_NNNN  A        :(_Lend_NNNN)            <- implicit break
 *     _Lcase_NNNN  B        :(_Lend_NNNN)            <- implicit break
 *     _Ldefault_NNNN D                                <- last clause: no goto
 *     _Lend_NNNN
 *
 * Stacked case labels (`case 1: case 2: stmts;`) suppress the implicit
 * break between adjacent labels — both labels chain forward to the
 * shared body via SNOBOL4 label-pad chaining semantics.
 *
 * Label numbering for `switch (x) { case 1: ... }` with one case:
 *   _Lswitch_t_0001  (the synthetic tmp variable name — uses label_seq too)
 *   _Lend_0002       (break target)
 *   _Ldefault_0003   (default jump; allocated unconditionally even if no default)
 *   _Lcase_0004      (first case label — allocated as bodies parse)
 *
 * Caveat: `_Ldefault_0003` is allocated up front in sc_switch_head_new
 * even when no `default:` clause appears in the source.  In that path
 * the dispatch's catch-all goto targets `_Lend` directly (not _Ldefault),
 * and no _Ldefault label-pad is ever emitted.  The allocated label
 * string is owned by SwitchHead and freed in finalize.
 * ========================================================================= */

/* Helper: count uncond gotos that target a specific label. */
/* (count_gotos_to is already defined above.) */

/* Helper: count `IDENT(tmp_name, value) :S(target)` dispatch stmts in IR.
 * Identifies dispatch stmts by checking `subject->kind == AST_FNC` with
 * `subject->sval == "IDENT"` and presence of an onsuccess goto. */
static int count_dispatch_stmts(STMT_t **stmts, int n) {
    int c = 0;
    for (int i = 0; i < n; i++) {
        if (stmts[i]->subject &&
            stmts[i]->subject->kind == AST_FNC &&
            stmts[i]->subject->sval &&
            strcmp(stmts[i]->subject->sval, "IDENT") == 0 &&
            stmts[i]->go && stmts[i]->go->onsuccess) c++;
    }
    return c;
}

/* =========================================================================
 * Test 32 — empty switch body
 *   switch (x) { }
 *   Expected:
 *     tmp = x          (assignment)
 *     :(_Lend_0002)    (catch-all goto — no cases)
 *     _Lend_0002 pad
 *   3 stmts total.  No dispatch entries.
 * ========================================================================= */
static void test_switch_empty_body(void) {
    Program *prog = snocone_parse_program("switch (x) { }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts (tmp-assign, catch-all goto, _Lend pad), got %d", n);
    if (n >= 1) ASSERT(is_assignment(stmts[0]), "stmt[0] should be tmp = x");
    ASSERT(count_dispatch_stmts(stmts, n) == 0, "no dispatch stmts in empty switch");
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 1,
           "catch-all goto :(_Lend_0002) should be present");
    /* Find the _Lend pad — should be there. */
    ASSERT(find_label_with_prefix(stmts, n, "_Lend_") != NULL,
           "_Lend pad should be at end");
    free(stmts);
}

/* =========================================================================
 * Test 33 — single case, no default
 *   switch (x) { case 1: y = 1; }
 *   Expected: 6 stmts:
 *     [0] tmp = x
 *     [1] IDENT(tmp,1) :S(_Lcase_0004)
 *     [2] :(_Lend_0002)            <- catch-all (no default)
 *     [3] _Lcase_0004 pad
 *     [4] y = 1
 *     [5] _Lend_0002 pad
 * ========================================================================= */
static void test_switch_single_case(void) {
    Program *prog = snocone_parse_program("switch (x) { case 1: y = 1; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 6, "expected 6 stmts, got %d", n);
    ASSERT(count_dispatch_stmts(stmts, n) == 1, "expected 1 dispatch stmt");
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 1,
           "catch-all goto should target _Lend_0002");
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcase") == 1,
           "expected 1 _Lcase label pad");
    ASSERT(count_labels_with_prefix(stmts, n, "_Ldefault") == 0,
           "no _Ldefault pad emitted (no default clause)");
    free(stmts);
}

/* =========================================================================
 * Test 34 — two cases, no default
 *   switch (x) { case 1: y = 1; case 2: y = 2; }
 *   Body of case 1 ends with implicit `:(_Lend_0002)`;
 *   body of case 2 falls through to _Lend (last clause — no implicit break).
 * ========================================================================= */
static void test_switch_two_cases_no_default(void) {
    Program *prog = snocone_parse_program(
        "switch (x) { case 1: y = 1; case 2: y = 2; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_dispatch_stmts(stmts, n) == 2, "expected 2 dispatch stmts");
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcase") == 2,
           "expected 2 _Lcase label pads");
    /* _Lend_0002 receives: 1 catch-all goto + 1 implicit-break (after case 1).
     * Case 2 is the LAST clause so no implicit break — falls through naturally. */
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 2,
           "_Lend_0002 should receive 2 gotos (catch-all + 1 implicit break), got %d",
           count_gotos_to(stmts, n, "_Lend_0002"));
    free(stmts);
}

/* =========================================================================
 * Test 35 — two cases with default at end
 *   switch (x) { case 1: y = 1; case 2: y = 2; default: y = 99; }
 *   Catch-all goto targets _Ldefault_0003 (not _Lend_0002).
 *   Implicit break after case 1 AND case 2 (default is last; default body
 *   itself falls through to _Lend with no implicit break).
 * ========================================================================= */
static void test_switch_two_cases_with_default(void) {
    Program *prog = snocone_parse_program(
        "switch (x) { case 1: y = 1; case 2: y = 2; default: y = 99; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_dispatch_stmts(stmts, n) == 2,
           "expected 2 IDENT dispatch stmts (default has no probe)");
    ASSERT(count_gotos_to(stmts, n, "_Ldefault_0003") == 1,
           "catch-all goto should target _Ldefault_0003 since default present");
    /* Implicit breaks after case 1 + case 2 = 2 gotos to _Lend; default last → no break. */
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 2,
           "_Lend_0002 should receive 2 implicit-break gotos (case 1 + case 2 bodies)");
    ASSERT(count_labels_with_prefix(stmts, n, "_Ldefault") == 1,
           "expected 1 _Ldefault label pad");
    free(stmts);
}

/* =========================================================================
 * Test 36 — default first (allowed; default clause anywhere in body)
 *   switch (x) { default: y = 99; case 1: y = 1; }
 *   default body needs an implicit `:(_Lend)` because case 1 follows;
 *   case 1 is the LAST clause so its body falls through naturally.
 * ========================================================================= */
static void test_switch_default_first(void) {
    Program *prog = snocone_parse_program(
        "switch (x) { default: y = 99; case 1: y = 1; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_dispatch_stmts(stmts, n) == 1, "expected 1 IDENT dispatch (one case)");
    ASSERT(count_gotos_to(stmts, n, "_Ldefault_0003") == 1,
           "catch-all should still target _Ldefault");
    /* default body's implicit-break goto to _Lend_0002 = 1 goto */
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 1,
           "_Lend should receive 1 implicit-break goto (after default body)");
    free(stmts);
}

/* =========================================================================
 * Test 37 — stacked case labels (no body between)
 *   switch (x) { case 1: case 2: y = 'oneortwo'; }
 *   Both _Lcase pads emitted back-to-back; NO implicit `:(_Lend)` between
 *   them (suppressed because last_case_label_tail == code->tail when the
 *   second case head fires — no body appended in between).
 * ========================================================================= */
static void test_switch_stacked_case_labels(void) {
    Program *prog = snocone_parse_program(
        "switch (x) { case 1: case 2: y = 'oneortwo'; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_dispatch_stmts(stmts, n) == 2, "expected 2 dispatch stmts");
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcase") == 2,
           "expected 2 _Lcase pads");
    /* Critical: only ONE goto to _Lend exists — the catch-all.  No implicit
     * break between case 1 and case 2 (empty body between them) and no
     * implicit break after the shared body (case 2 is last clause). */
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 1,
           "stacked labels with no body between must NOT emit implicit break — "
           "expected 1 goto to _Lend (catch-all only), got %d",
           count_gotos_to(stmts, n, "_Lend_0002"));
    free(stmts);
}

/* =========================================================================
 * Test 38 — explicit break inside switch case
 *   switch (x) { case 1: y = 1; break; case 2: y = 2; }
 *   The user's `break;` resolves the switch's LoopFrame (is_loop=0) and
 *   emits an extra `:(_Lend_0002)` — added on top of the implicit break
 *   that already happens at the start of case 2's label.
 * ========================================================================= */
static void test_switch_explicit_break_in_case(void) {
    Program *prog = snocone_parse_program(
        "switch (x) { case 1: y = 1; break; case 2: y = 2; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* _Lend gets: 1 catch-all + 1 implicit break (after case 1's body, before
     * case 2 label) + 1 explicit user break = 3 gotos total. */
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 3,
           "expected 3 gotos to _Lend_0002 (catch-all + implicit + explicit), got %d",
           count_gotos_to(stmts, n, "_Lend_0002"));
    free(stmts);
}

/* =========================================================================
 * Test 39 — continue inside switch is a parse error
 *   switch (x) { case 1: continue; }
 *   `continue;` requires a loop frame.  sc_loop_find_innermost(want_loop=1)
 *   skips the switch's is_loop=0 frame and finds nothing → sc_error fires.
 * ========================================================================= */
static void test_switch_continue_is_error(void) {
    Program *prog = snocone_parse_program(
        "switch (x) { case 1: continue; }", "test");
    ASSERT(prog == NULL, "continue inside switch (no enclosing loop) must fail");
}

/* =========================================================================
 * Test 40 — multiple defaults is a parse error
 *   switch (x) { default: y = 1; default: y = 2; }
 * ========================================================================= */
static void test_switch_multiple_defaults_error(void) {
    Program *prog = snocone_parse_program(
        "switch (x) { default: y = 1; default: y = 2; }", "test");
    ASSERT(prog == NULL, "duplicate default label must fail");
}

/* =========================================================================
 * Test 41 — nested switches
 *   switch (x) { case 1: switch (y) { case 2: z = 1; } }
 *   Inner and outer switches each have their own _Lend / _Lcase / tmp
 *   labels.  No collision; cur_switch save/restore preserves outer.
 * ========================================================================= */
static void test_switch_nested(void) {
    Program *prog = snocone_parse_program(
        "switch (x) { case 1: switch (y) { case 2: z = 1; } }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(count_dispatch_stmts(stmts, n) == 2, "expected 2 dispatch stmts (one each)");
    /* Two distinct _Lend pads (one per switch).  Outer = _Lend_0002, inner
     * = _Lend_0006 (allocated after outer's _Ldefault_0003 and _Lcase_0004). */
    ASSERT(count_labels_with_prefix(stmts, n, "_Lend") == 2,
           "expected 2 _Lend pads (nested switches), got %d",
           count_labels_with_prefix(stmts, n, "_Lend"));
    ASSERT(count_labels_with_prefix(stmts, n, "_Lcase") == 2,
           "expected 2 _Lcase pads");
    free(stmts);
}

/* =========================================================================
 * Test 42 — break LABEL out of switch nested in loop (LS-4.i.2 forward-compat)
 *   outer: while (DIFFER(x)) { switch (x) { case 1: break outer; } }
 *   The `break outer` must target the outer LOOP's _Lend, NOT the switch's.
 *   Verifies LS-4.i.2's sc_loop_find_by_user_label correctly walks across
 *   the switch's LoopFrame to find the labeled loop frame above it.
 * ========================================================================= */
static void test_switch_break_outer_label_in_loop(void) {
    Program *prog = snocone_parse_program(
        "outer: while (DIFFER(x)) { switch (x) { case 1: break outer; } }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* Outer while: _Ltop_0001, _Lend_0002.  Switch: _Lswitch_t_0003,
     * _Lend_0004, _Ldefault_0005, _Lcase_0006.  `break outer` must hit
     * _Lend_0002 (outer while's end), not _Lend_0004 (switch's end). */
    ASSERT(count_gotos_to(stmts, n, "_Lend_0002") == 1,
           "break outer should produce 1 goto to outer's _Lend_0002, got %d",
           count_gotos_to(stmts, n, "_Lend_0002"));
    free(stmts);
}

/* =========================================================================
 * Test 43 — switch in if-then position (matched_stmt nesting)
 *   if (DIFFER(x)) switch (x) { case 1: y = 1; }
 *   Verifies switch_head + body parses correctly inside an if's then-arm.
 * ========================================================================= */
static void test_switch_inside_if(void) {
    Program *prog = snocone_parse_program(
        "if (DIFFER(x)) switch (x) { case 1: y = 1; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* Outer if: cond stmt :F(_Lend_if), body, _Lend_if pad.
     * Body = entire switch lowering. */
    ASSERT(count_dispatch_stmts(stmts, n) == 1, "expected 1 IDENT dispatch in switch");
    /* Two _Lend pads — one for if, one for switch. */
    ASSERT(count_labels_with_prefix(stmts, n, "_Lend") == 2,
           "expected 2 _Lend pads (if + switch), got %d",
           count_labels_with_prefix(stmts, n, "_Lend"));
    free(stmts);
}

/* =========================================================================
 * Test 44 — switch with user label
 *   tag: switch (x) { case 1: y = 1; }
 *   The user label `tag` attaches to the tmp-assign (sc_append_stmt clears
 *   pending — same disambiguation as `a: x = 1; while(...)` in LS-4.i.2).
 *   So `break tag;` from inside would NOT find the switch frame.
 *   Verified separately; here we just confirm parse succeeds and `tag`
 *   pad is at the front.
 * ========================================================================= */
static void test_switch_with_user_label(void) {
    Program *prog = snocone_parse_program(
        "tag: switch (x) { case 1: y = 1; }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n >= 1 && stmts[0]->label && strcmp(stmts[0]->label, "tag") == 0,
           "stmt[0] should be 'tag' label pad, got %s",
           (n >= 1 && stmts[0]->label) ? stmts[0]->label : "(null)");
    /* The switch's tmp-assign comes after, NOT carrying tag — that confirms
     * the LS-4.i.2 pending-clear behavior is consistent: switch isn't a loop,
     * but it goes through sc_append_stmt for the tmp-assign which clears
     * pending. */
    free(stmts);
}

/* =========================================================================
 * Test 45 — case label inside if's then-arm (regression guard)
 *   `case 1: stmt;` outside any switch must be a parse error — even
 *   inside a non-switch construct.  Without proper grammar restriction,
 *   case_or_default_label could "leak" into other contexts.
 * ========================================================================= */
static void test_case_outside_switch_error(void) {
    /* No way to trigger case outside switch in our grammar — case_or_default_label
     * only appears under switch_body.  But verify: a top-level `case 1:`
     * is a parse error. */
    Program *prog = snocone_parse_program("case 1: y = 1;", "test");
    ASSERT(prog == NULL, "case outside switch must be a parse error");
}

/* =========================================================================
 * LS-4.i.4 — alt-eval `(a, b, c)` → AST_VLIST  (tests 46–58)
 *
 * Goal-file lowering shape:
 *
 *   (e1, e2, ..., en)   ->   AST_VLIST(e1, e2, ..., en)
 *                            n-ary node, one child per comma-separated expr.
 *                            Goal-directed value-context disjunction —
 *                            evaluate left-to-right, value of first
 *                            non-failing child is value of whole; if all
 *                            fail, whole fails.
 *
 *   ()                  ->   AST_NUL  (empty parens, mirrors snobol4.y:196)
 *   (e)                 ->   <e>    (single-expr grouping unchanged —
 *                                    LR(1) lookahead at T_RPAREN
 *                                    distinguishes from VLIST's T_COMMA)
 *
 * Distinct from AST_ALT (pattern alternation, lazy at match time) — IR
 * comment at src/ir/ir.h:83-87 is explicit on this.  AST_VLIST is the
 * canonical replacement for Andrew Koenig's `||` operator (goal file
 * Q2) and the SPITBOL Manual Ch.15 footnote primitive.
 * ========================================================================= */

/* True if expr is an AST_VLIST with the given child count. */
static int is_vlist(AST_t *e, int n) {
    return e && e->kind == AST_VLIST && e->nchildren == n;
}

/* True if expr is the literal AST_NUL kind (empty-parens result). */
static int is_nul(AST_t *e) {
    return e && e->kind == AST_NUL;
}

/* True if expr is a bare variable reference with the given name. */
static int is_var_named(AST_t *e, const char *name) {
    return e && e->kind == AST_VAR && e->sval && strcmp(e->sval, name) == 0;
}

/* =========================================================================
 * Test 46 — headline 3-arity alt-eval
 *   x = (a, b, c);
 *   Expected:
 *     stmt[0] assignment: x = AST_VLIST(VAR a, VAR b, VAR c)
 * ========================================================================= */
static void test_vlist_three_args(void) {
    Program *prog = snocone_parse_program("x = (a, b, c);", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) {
        ASSERT(is_assignment(stmts[0]), "stmt[0] should be assignment");
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(is_vlist(rhs, 3), "RHS should be AST_VLIST with 3 children, kind=%d nch=%d",
               rhs ? rhs->kind : -1, rhs ? rhs->nchildren : -1);
        if (is_vlist(rhs, 3)) {
            ASSERT(is_var_named(rhs->children[0], "a"), "child[0] should be VAR a");
            ASSERT(is_var_named(rhs->children[1], "b"), "child[1] should be VAR b");
            ASSERT(is_var_named(rhs->children[2], "c"), "child[2] should be VAR c");
        }
    }
    free(stmts);
}

/* =========================================================================
 * Test 47 — minimum 2-arity alt-eval
 *   x = (a, b);
 * ========================================================================= */
static void test_vlist_two_args(void) {
    Program *prog = snocone_parse_program("x = (a, b);", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    if (n >= 1) {
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(is_vlist(rhs, 2), "RHS should be AST_VLIST with 2 children");
        if (is_vlist(rhs, 2)) {
            ASSERT(is_var_named(rhs->children[0], "a"), "child[0] should be VAR a");
            ASSERT(is_var_named(rhs->children[1], "b"), "child[1] should be VAR b");
        }
    }
    free(stmts);
}

/* =========================================================================
 * Test 48 — single-expr grouping unchanged (regression guard)
 *   x = (a);
 *   The single-expr paren rule must STILL fire — RHS is bare VAR a, NOT
 *   a 1-arity AST_VLIST.  This exercises the LR(1) lookahead path (T_RPAREN
 *   after expr0 reduces to plain grouping).
 * ========================================================================= */
static void test_paren_grouping_unchanged(void) {
    Program *prog = snocone_parse_program("x = (a);", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    if (n >= 1) {
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(is_var_named(rhs, "a"),
               "RHS of x = (a) should be bare VAR a — not AST_VLIST. kind=%d",
               rhs ? rhs->kind : -1);
    }
    free(stmts);
}

/* =========================================================================
 * Test 49 — empty parens → AST_NUL
 *   x = ();
 *   Mirrors snobol4.y:196.  AST_NUL is the canonical null/empty expression.
 * ========================================================================= */
static void test_empty_parens(void) {
    Program *prog = snocone_parse_program("x = ();", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    if (n >= 1) {
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(is_nul(rhs), "RHS of x = () should be AST_NUL, kind=%d",
               rhs ? rhs->kind : -1);
    }
    free(stmts);
}

/* =========================================================================
 * Test 50 — SPITBOL Manual Ch.15 footnote example
 *   A = (LT(I,J) I, GT(I,J) J, "Same");
 *   The canonical alt-eval example.  RHS is AST_VLIST(3) where each child
 *   is a complex sub-expression: child[0] is concat of LT call and I,
 *   child[1] is concat of GT call and J, child[2] is the string "Same".
 *
 *   Note the FSM lexer's W{OP}W envelope — `LT(I,J) I` lexes the gap
 *   between `)` and `I` as T_CONCAT, so that child becomes AST_SEQ(call, I).
 * ========================================================================= */
static void test_vlist_spitbol_manual_example(void) {
    Program *prog = snocone_parse_program(
        "A = (LT(I,J) I, GT(I,J) J, \"Same\");", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    if (n >= 1) {
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(is_vlist(rhs, 3), "RHS should be AST_VLIST(3), kind=%d nch=%d",
               rhs ? rhs->kind : -1, rhs ? rhs->nchildren : -1);
        if (is_vlist(rhs, 3)) {
            /* child[0]: LT(I,J) I — a concat: AST_SEQ(AST_FNC LT, AST_VAR I) */
            AST_t *c0 = rhs->children[0];
            ASSERT(c0->kind == AST_SEQ && c0->nchildren == 2,
                   "child[0] should be AST_SEQ(2), kind=%d nch=%d",
                   c0->kind, c0->nchildren);
            if (c0->kind == AST_SEQ && c0->nchildren == 2) {
                ASSERT(c0->children[0]->kind == AST_FNC,
                       "child[0].child[0] should be AST_FNC (LT call)");
                ASSERT(is_var_named(c0->children[1], "I"),
                       "child[0].child[1] should be VAR I");
            }
            /* child[2]: "Same" — string literal */
            AST_t *c2 = rhs->children[2];
            ASSERT(c2->kind == AST_QLIT && c2->sval &&
                   strcmp(c2->sval, "Same") == 0,
                   "child[2] should be QLIT \"Same\", kind=%d sval=%s",
                   c2->kind, c2->sval ? c2->sval : "(null)");
        }
    }
    free(stmts);
}

/* =========================================================================
 * Test 51 — nested VLIST
 *   x = ((a, b), c);
 *   Outer is AST_VLIST(2): children = [AST_VLIST(2, a, b), VAR c].
 *   Demonstrates that a VLIST is itself an expr0, so it can sit inside
 *   another VLIST without flattening.  (AST_VLIST is NOT a left-recursive
 *   fold like AST_SEQ/AST_ALT — each paren-pair builds its own node.)
 * ========================================================================= */
static void test_vlist_nested(void) {
    Program *prog = snocone_parse_program("x = ((a, b), c);", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    if (n >= 1) {
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(is_vlist(rhs, 2), "outer RHS should be AST_VLIST(2), nch=%d",
               rhs ? rhs->nchildren : -1);
        if (is_vlist(rhs, 2)) {
            ASSERT(is_vlist(rhs->children[0], 2),
                   "child[0] should be inner AST_VLIST(2)");
            ASSERT(is_var_named(rhs->children[1], "c"),
                   "child[1] should be VAR c");
        }
    }
    free(stmts);
}

/* =========================================================================
 * Test 52 — VLIST as if-condition
 *   if ((a, b)) y = 1;
 *   Per goal Q2: alt-eval is the canonical replacement for `||` in
 *   conditions.  The cond expr is AST_VLIST(2); LS-4.f's emit-and-splice
 *   architecture lowers it to `<vlist> :F(_Lend_NNNN)` with the assignment
 *   in between.  We verify the cond stmt has AST_VLIST as its subject.
 * ========================================================================= */
static void test_vlist_as_if_condition(void) {
    Program *prog = snocone_parse_program("if ((a, b)) y = 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* Expected shape (from LS-4.f):
     *   stmt[0]  cond:F(_Lend)        — subject is VLIST, has F-branch
     *   stmt[1]  y = 1                — body assignment
     *   stmt[2]  _Lend_NNNN           — end label pad
     */
    ASSERT(n == 3, "expected 3 stmts (cond, body, _Lend), got %d", n);
    if (n >= 1) {
        AST_t *cond = stmts[0]->subject;
        ASSERT(is_vlist(cond, 2),
               "stmt[0] subject should be AST_VLIST(2), kind=%d nch=%d",
               cond ? cond->kind : -1, cond ? cond->nchildren : -1);
        ASSERT(stmts[0]->go != NULL,
               "stmt[0] should have an :F goto branch");
    }
    if (n >= 2) {
        ASSERT(is_assignment(stmts[1]), "stmt[1] should be the y = 1 body");
    }
    if (n >= 3) {
        ASSERT(is_label_pad(stmts[2]),
               "stmt[2] should be the _Lend label pad");
    }
    free(stmts);
}

/* =========================================================================
 * Test 53 — VLIST inside arithmetic
 *   x = (a, b) + 1;
 *   VLIST yields a value, so it can be an operand of any binary operator.
 *   RHS is AST_ADD(AST_VLIST(2, a, b), 1).
 * ========================================================================= */
static void test_vlist_in_arithmetic(void) {
    Program *prog = snocone_parse_program("x = (a, b) + 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    if (n >= 1) {
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(rhs && rhs->kind == AST_ADD && rhs->nchildren == 2,
               "RHS should be AST_ADD(2), kind=%d", rhs ? rhs->kind : -1);
        if (rhs && rhs->kind == AST_ADD && rhs->nchildren == 2) {
            ASSERT(is_vlist(rhs->children[0], 2),
                   "ADD's left operand should be AST_VLIST(2)");
            ASSERT(rhs->children[1]->kind == AST_ILIT &&
                   rhs->children[1]->ival == 1,
                   "ADD's right operand should be ILIT 1");
        }
    }
    free(stmts);
}

/* =========================================================================
 * Test 54 — VLIST distinct from AST_ALT (pattern alternation)
 *   x = (a | b, c);
 *   Inside parens, `,` separates VLIST children; `|` (within one child)
 *   is pattern alternation and folds into AST_ALT.  Result: outer is
 *   AST_VLIST(2) where child[0] is AST_ALT(a, b) and child[1] is VAR c.
 *   This proves the IR distinction documented at src/ir/ir.h:82-87.
 * ========================================================================= */
static void test_vlist_distinct_from_ealt(void) {
    Program *prog = snocone_parse_program("x = (a | b, c);", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    if (n >= 1) {
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(is_vlist(rhs, 2), "RHS should be AST_VLIST(2), kind=%d nch=%d",
               rhs ? rhs->kind : -1, rhs ? rhs->nchildren : -1);
        if (is_vlist(rhs, 2)) {
            AST_t *c0 = rhs->children[0];
            ASSERT(c0->kind == AST_ALT && c0->nchildren == 2,
                   "child[0] should be AST_ALT(2), kind=%d nch=%d",
                   c0->kind, c0->nchildren);
            ASSERT(is_var_named(rhs->children[1], "c"),
                   "child[1] should be VAR c");
        }
    }
    free(stmts);
}

/* =========================================================================
 * Test 55 — call (AST_FNC) is NOT VLIST (regression guard)
 *   x = f(a, b);
 *   The T_CALL T_LPAREN exprlist T_RPAREN rule (zero-space-after-IDENT)
 *   wins over the new T_LPAREN expr0 T_COMMA exprlist_ne T_RPAREN rule
 *   because the lexer emits T_CALL for `f(`, not T_IDENT then T_LPAREN.
 *   RHS is AST_FNC("f", a, b), not AST_VLIST.
 * ========================================================================= */
static void test_call_not_vlist(void) {
    Program *prog = snocone_parse_program("x = f(a, b);", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    if (n >= 1) {
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(rhs && rhs->kind == AST_FNC,
               "RHS should be AST_FNC (call), kind=%d", rhs ? rhs->kind : -1);
        ASSERT(rhs && rhs->sval && strcmp(rhs->sval, "f") == 0,
               "AST_FNC sval should be \"f\"");
        ASSERT(rhs && rhs->nchildren == 2,
               "AST_FNC should have 2 children");
    }
    free(stmts);
}

/* =========================================================================
 * Test 56 — VLIST as bare expression statement
 *   (a, b);
 *   A bare expression statement (per goal "Bare expressions, statements,
 *   failure" section) is just expr0 + ';'.  Failure is silent; success
 *   has no further consequence.  Verifies VLIST works at top-level
 *   stmt position.
 * ========================================================================= */
static void test_vlist_bare_statement(void) {
    Program *prog = snocone_parse_program("(a, b);", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) {
        ASSERT(is_bare_expr(stmts[0]),
               "stmt[0] should be bare expression (subject, no goto)");
        ASSERT(is_vlist(stmts[0]->subject, 2),
               "subject should be AST_VLIST(2), kind=%d",
               stmts[0]->subject ? stmts[0]->subject->kind : -1);
    }
    free(stmts);
}

/* =========================================================================
 * Test 57 — VLIST inside while-condition
 *   while ((a, b)) y = 1;
 *   Same shape as Test 52 but for while: cond is AST_VLIST(2), drives the
 *   loop's :F-on-fail exit.  Per LS-4.f lowering: _Ltop, cond:F(_Lend),
 *   <body>, :(_Ltop), _Lend.
 * ========================================================================= */
static void test_vlist_as_while_condition(void) {
    Program *prog = snocone_parse_program("while ((a, b)) y = 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* Expected: _Ltop, cond:F(_Lend), body, :(_Ltop), _Lend */
    ASSERT(n == 5, "expected 5 stmts, got %d", n);
    if (n >= 2) {
        AST_t *cond = stmts[1]->subject;
        ASSERT(is_vlist(cond, 2),
               "stmt[1] subject should be AST_VLIST(2), kind=%d nch=%d",
               cond ? cond->kind : -1, cond ? cond->nchildren : -1);
        ASSERT(stmts[1]->go != NULL,
               "stmt[1] should have an :F goto branch");
    }
    free(stmts);
}

/* =========================================================================
 * Test 58 — VLIST with all-literal children
 *   x = (1, 2, "three");
 *   A no-VAR alt-eval — every child is a literal.  All three succeed
 *   trivially under SPITBOL semantics, so this evaluates to 1, but at
 *   parse-time we just verify the VLIST shape.
 * ========================================================================= */
static void test_vlist_literals(void) {
    Program *prog = snocone_parse_program("x = (1, 2, \"three\");", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    if (n >= 1) {
        AST_t *rhs = stmts[0]->replacement;
        ASSERT(is_vlist(rhs, 3), "RHS should be AST_VLIST(3)");
        if (is_vlist(rhs, 3)) {
            ASSERT(rhs->children[0]->kind == AST_ILIT &&
                   rhs->children[0]->ival == 1,
                   "child[0] should be ILIT 1");
            ASSERT(rhs->children[1]->kind == AST_ILIT &&
                   rhs->children[1]->ival == 2,
                   "child[1] should be ILIT 2");
            ASSERT(rhs->children[2]->kind == AST_QLIT &&
                   rhs->children[2]->sval &&
                   strcmp(rhs->children[2]->sval, "three") == 0,
                   "child[2] should be QLIT \"three\"");
        }
    }
    free(stmts);
}

/* =========================================================================
 * LS-4.i.5 — `struct NAME { f1, f2, ... }` record declarations
 *
 * Lowering shape (single bare-expression statement, no goto, no label):
 *
 *     subject = AST_FNC("DATA", AST_QLIT("NAME(f1,f2,...)"))
 *
 * Empty-fields case: `struct NAME { }` → `DATA('NAME()')`.
 *
 * Andrew's `.sc` line 162 introduces struct on top of the SPITBOL
 * bootstrap; underlying primitive is SPITBOL `DATA('NAME(...)')` which
 * installs a constructor + per-field accessors in one call.  The
 * accessors double as L-values (e.g. `next(x) = newval`).
 *
 * Real-world corpus shapes verified (corpus/programs/include-sc/):
 *   stack.sc      `struct link { next, value }`
 *   tree.sc       `struct tree { t, v, n, c }`
 *   counter.sc    `struct link_counter { next, value }`
 *                 `struct link_tag { next, value }`     (back-to-back)
 *
 * No trailing semicolon — matches Andrew's surface and all corpus uses.
 * ========================================================================= */

/* Helper: True if stmt is a bare DATA('SPEC') call — i.e. subject is
 * AST_FNC named "DATA" with one AST_QLIT child whose sval matches `expected`. */
static int is_struct_data_call(STMT_t *s, const char *expected_spec) {
    if (!s || !is_bare_expr(s)) return 0;
    AST_t *e = s->subject;
    if (!e || e->kind != AST_FNC) return 0;
    if (!e->sval || strcmp(e->sval, "DATA") != 0) return 0;
    if (e->nchildren != 1) return 0;
    AST_t *q = e->children[0];
    if (!q || q->kind != AST_QLIT) return 0;
    if (!q->sval) return 0;
    return strcmp(q->sval, expected_spec) == 0;
}

/* =========================================================================
 * Test 59 — headline: `struct link { next, value }` (Andrew's stack.sc shape)
 *   Expected:
 *     stmt[0]   bare-expr  DATA('link(next,value)')
 * ========================================================================= */
static void test_struct_two_fields_headline(void) {
    Program *prog = snocone_parse_program("struct link { next, value }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) {
        ASSERT(is_struct_data_call(stmts[0], "link(next,value)"),
               "stmt[0] should be DATA('link(next,value)')");
    }
    free(stmts);
}

/* =========================================================================
 * Test 60 — single-field struct
 *   `struct one { only }` → DATA('one(only)')
 * ========================================================================= */
static void test_struct_single_field(void) {
    Program *prog = snocone_parse_program("struct one { only }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) ASSERT(is_struct_data_call(stmts[0], "one(only)"),
                       "stmt[0] should be DATA('one(only)')");
    free(stmts);
}

/* =========================================================================
 * Test 61 — empty struct `{ }`
 *   `struct empty { }` → DATA('empty()')
 *   SPITBOL accepts a zero-field record; rare but legal.
 * ========================================================================= */
static void test_struct_empty_fields(void) {
    Program *prog = snocone_parse_program("struct empty { }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) ASSERT(is_struct_data_call(stmts[0], "empty()"),
                       "stmt[0] should be DATA('empty()')");
    free(stmts);
}

/* =========================================================================
 * Test 62 — four-field real-world shape (Andrew's tree.sc verbatim)
 *   `struct tree { t, v, n, c }` → DATA('tree(t,v,n,c)')
 *   Verifies struct_field_list left-recursive accumulation handles
 *   N>2 cases.
 * ========================================================================= */
static void test_struct_four_fields(void) {
    Program *prog = snocone_parse_program("struct tree { t, v, n, c }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) ASSERT(is_struct_data_call(stmts[0], "tree(t,v,n,c)"),
                       "stmt[0] should be DATA('tree(t,v,n,c)')");
    free(stmts);
}

/* =========================================================================
 * Test 63 — splice integrity: struct between assignments
 *   `x = 1; struct s { a, b, c } y = 2;`
 *   Expected: 3 stmts in order — assign, struct, assign.  Confirms
 *   sc_emit_struct doesn't disturb the linked-list around it.
 * ========================================================================= */
static void test_struct_in_sequence(void) {
    Program *prog = snocone_parse_program(
        "x = 1; struct s { a, b, c } y = 2;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 3, "expected 3 stmts, got %d", n);
    if (n >= 1) ASSERT(is_assignment(stmts[0]),
                       "stmt[0] should be assignment x = 1");
    if (n >= 2) ASSERT(is_struct_data_call(stmts[1], "s(a,b,c)"),
                       "stmt[1] should be DATA('s(a,b,c)')");
    if (n >= 3) ASSERT(is_assignment(stmts[2]),
                       "stmt[2] should be assignment y = 2");
    free(stmts);
}

/* =========================================================================
 * Test 64 — back-to-back structs (Andrew's counter.sc shape verbatim)
 *   `struct link_counter { next, value } struct link_tag { next, value }`
 *   Two adjacent struct decls.  No semicolons between them — matches the
 *   actual corpus file.  Each lowers to its own DATA() call.
 * ========================================================================= */
static void test_struct_back_to_back(void) {
    Program *prog = snocone_parse_program(
        "struct link_counter { next, value } struct link_tag { next, value }",
        "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 2, "expected 2 stmts, got %d", n);
    if (n >= 1) ASSERT(is_struct_data_call(stmts[0], "link_counter(next,value)"),
                       "stmt[0] should be DATA('link_counter(next,value)')");
    if (n >= 2) ASSERT(is_struct_data_call(stmts[1], "link_tag(next,value)"),
                       "stmt[1] should be DATA('link_tag(next,value)')");
    free(stmts);
}

/* =========================================================================
 * Test 65 — name with underscore preserved verbatim
 *   `struct my_record { a, b }` → DATA('my_record(a,b)') — confirms the
 *   case-sensitive, bytes-preserved lexer rule (RULES.md) carries through.
 * ========================================================================= */
static void test_struct_name_with_underscore(void) {
    Program *prog = snocone_parse_program("struct my_record { a, b }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) ASSERT(is_struct_data_call(stmts[0], "my_record(a,b)"),
                       "stmt[0] should be DATA('my_record(a,b)')");
    free(stmts);
}

/* =========================================================================
 * Test 66 — mixed-case identifiers preserved (case-sensitive name space)
 *   `struct Cons { Car, Cdr }` — capitals, mixed case.  Per RULES.md,
 *   no folding anywhere; the QLIT spec must contain the bytes verbatim.
 * ========================================================================= */
static void test_struct_mixed_case(void) {
    Program *prog = snocone_parse_program("struct Cons { Car, Cdr }", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 1, "expected 1 stmt, got %d", n);
    if (n >= 1) ASSERT(is_struct_data_call(stmts[0], "Cons(Car,Cdr)"),
                       "stmt[0] should be DATA('Cons(Car,Cdr)')");
    free(stmts);
}

/* =========================================================================
 * Test 67 — struct followed by use of the constructor
 *   `struct cons { car, cdr } x = cons(1, 2);`
 *   The struct decl precedes a call to the now-defined cons() ctor.
 *   At parse time we don't run anything — just verify both stmts emit
 *   in order with the right shapes.  The IR is what gets handed to the
 *   runtime, where DATA() actually installs the function bindings.
 * ========================================================================= */
static void test_struct_followed_by_use(void) {
    Program *prog = snocone_parse_program(
        "struct cons { car, cdr } x = cons(1, 2);", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    ASSERT(n == 2, "expected 2 stmts, got %d", n);
    if (n >= 1) ASSERT(is_struct_data_call(stmts[0], "cons(car,cdr)"),
                       "stmt[0] should be DATA('cons(car,cdr)')");
    if (n >= 2) {
        ASSERT(is_assignment(stmts[1]),
               "stmt[1] should be assignment x = cons(1, 2)");
        if (is_assignment(stmts[1])) {
            AST_t *rhs = stmts[1]->replacement;
            ASSERT(rhs && rhs->kind == AST_FNC && rhs->sval &&
                   strcmp(rhs->sval, "cons") == 0,
                   "RHS should be AST_FNC(\"cons\", ...)");
            ASSERT(rhs && rhs->nchildren == 2,
                   "cons call should have 2 args");
        }
    }
    free(stmts);
}

/* =========================================================================
 * Test 68 — regression: struct does NOT consume a trailing semicolon
 *   `struct s { a, b } ; x = 1;`
 *   The explicit `;` after `}` must parse as an empty stmt (T_SEMICOLON
 *   alone in simple_stmt's catchall).  Three stmts total: struct,
 *   empty-stmt, assign.  The empty stmt is the T_SEMICOLON-only rule
 *   in simple_stmt, which produces no Program::head entry — so we
 *   actually expect 2 stmts (the empty one is a no-op at parse time).
 * ========================================================================= */
static void test_struct_with_explicit_trailing_semi(void) {
    Program *prog = snocone_parse_program(
        "struct s { a, b } ; x = 1;", "test");
    ASSERT(prog != NULL, "parse failed");
    if (!prog) return;

    int n; STMT_t **stmts = collect_stmts(prog, &n);
    /* T_SEMICOLON-alone rule produces no stmt — see simple_stmt's
     * "empty stmt" rule (T_SEMICOLON alone) in snocone_parse.y.  So the
     * sequence collapses to 2 stmts: struct, then assign. */
    ASSERT(n == 2, "expected 2 stmts, got %d", n);
    if (n >= 1) ASSERT(is_struct_data_call(stmts[0], "s(a,b)"),
                       "stmt[0] should be DATA('s(a,b)')");
    if (n >= 2) ASSERT(is_assignment(stmts[1]),
                       "stmt[1] should be assignment x = 1");
    free(stmts);
}

/* =========================================================================
 * Test 69 — error: struct without a name is a syntax error
 *   `struct { a, b }` — no identifier.  T_STRUCT must be followed by
 *   T_IDENT; the empty form is rejected by the grammar.
 * ========================================================================= */
static void test_struct_no_name_error(void) {
    Program *prog = snocone_parse_program("struct { a, b }", "test");
    ASSERT(prog == NULL, "parse should have failed (no struct name)");
    if (prog) {
        /* If it somehow parsed, the IR shape is meaningless — leak. */
    }
}

int main(void) {
    /* LS-4.i.1 — goto/label */
    test_goto_bare();
    test_goto_in_sequence();
    test_label_before_assign();
    test_label_and_goto_loop();
    test_label_before_block();
    test_label_before_if();
    test_label_before_while();
    test_multiple_goto_targets();
    test_stacked_labels();
    test_label_before_empty_stmt();
    test_label_inside_function();
    test_label_with_preceding_stmts();
    test_label_whitespace_variants();
    test_goto_whitespace_variants();
    test_label_inside_while();
    /* LS-4.i.2 — break/continue */
    test_break_bare_in_while();
    test_continue_bare_in_while();
    test_break_continue_in_dowhile();
    test_break_continue_in_for();
    test_for_no_continue_lazy_suppressed();
    test_dowhile_no_continue_lazy_suppressed();
    test_for_with_continue_lazy_emitted();
    test_dowhile_with_continue_lazy_emitted();
    test_labeled_break_nested_loops();
    test_labeled_continue_nested_loops();
    test_stacked_labels_break_first();
    test_stacked_labels_break_second();
    test_label_on_non_loop_stmt_disambiguation();
    test_break_label_attached_to_non_loop_error();
    test_break_outside_loop_error();
    test_continue_outside_loop_error();
    /* LS-4.i.3 — switch/case/default */
    test_switch_empty_body();
    test_switch_single_case();
    test_switch_two_cases_no_default();
    test_switch_two_cases_with_default();
    test_switch_default_first();
    test_switch_stacked_case_labels();
    test_switch_explicit_break_in_case();
    test_switch_continue_is_error();
    test_switch_multiple_defaults_error();
    test_switch_nested();
    test_switch_break_outer_label_in_loop();
    test_switch_inside_if();
    test_switch_with_user_label();
    test_case_outside_switch_error();
    /* LS-4.i.4 — alt-eval (a, b, c) → AST_VLIST */
    test_vlist_three_args();
    test_vlist_two_args();
    test_paren_grouping_unchanged();
    test_empty_parens();
    test_vlist_spitbol_manual_example();
    test_vlist_nested();
    test_vlist_as_if_condition();
    test_vlist_in_arithmetic();
    test_vlist_distinct_from_ealt();
    test_call_not_vlist();
    test_vlist_bare_statement();
    test_vlist_as_while_condition();
    test_vlist_literals();
    /* LS-4.i.5 — struct NAME { f1, f2, ... } → DATA('NAME(f1,f2,...)') */
    test_struct_two_fields_headline();
    test_struct_single_field();
    test_struct_empty_fields();
    test_struct_four_fields();
    test_struct_in_sequence();
    test_struct_back_to_back();
    test_struct_name_with_underscore();
    test_struct_mixed_case();
    test_struct_followed_by_use();
    test_struct_with_explicit_trailing_semi();
    test_struct_no_name_error();
    printf("=== Results: %d passed, %d failed ===\n", g_pass, g_fail);
    return g_fail == 0 ? 0 : 1;
}
