; generated by scrip-cc -asm (program mode)
; link: gcc -no-pie out.s stmt_rt.o snobol4.o mock_includes.o
;             snobol4_pattern.o engine.o -lgc -lm -o prog
%include "snobol4_asm.mac"
global  main
extern  stmt_init, stmt_strval, stmt_intval
extern  stmt_realval, stmt_set_null, stmt_set_indirect, stmt_get_indirect, stmt_nreturn_deref
extern  stmt_get, stmt_set, stmt_output, stmt_input
extern  stmt_concat, stmt_is_fail, stmt_finish
extern  stmt_realval, stmt_set_null, stmt_set_indirect
extern  stmt_apply, stmt_goto_dispatch
extern  stmt_setup_subject, stmt_apply_replacement
extern  stmt_apply_replacement_splice
extern  stmt_set_capture, stmt_match_var, stmt_match_descr
extern  stmt_pos_var, stmt_rpos_var
extern  stmt_save_subject, stmt_restore_subject
extern  stmt_span_var, stmt_break_var
extern  stmt_breakx_var, stmt_breakx_lit
extern  stmt_any_var, stmt_notany_var, stmt_any_ptr
extern  stmt_break_ptr, stmt_span_ptr
extern  stmt_at_capture
extern  kw_anchor
extern  stmt_aref, stmt_aset, stmt_field_set
extern  stmt_aref2, stmt_aset2
extern  comm_stno
extern  blk_alloc, blk_free, memcpy  ; per-invocation DATA block runtime
extern  pat_ref  ; B-287: deferred *VAR pattern ref (XDSAR)
global  cursor, subject_data, subject_len_val

section .note.GNU-stack noalloc noexec nowrite progbits
section .bss
cursor                   resq 1
subject_len_val          resq 1
P_fact_ret_γ            resq 1
P_fact_ret_ω            resq 1
fn_fact_save_n_t         resq 1
fn_fact_save_n_p         resq 1
fn_fact_arg_0_t          resq 1
fn_fact_arg_0_p          resq 1
P_fact2_ret_γ           resq 1
P_fact2_ret_ω           resq 1
fn_fact2_save_n_t        resq 1
fn_fact2_save_n_p        resq 1
fn_fact2_arg_0_t         resq 1
fn_fact2_arg_0_p         resq 1
ucall0_sv_0_t            resq 1
ucall0_sv_0_p            resq 1
ucall0_rsv_g             resq 1
ucall0_rsv_o             resq 1
ucall1_sv_0_t            resq 1
ucall1_sv_0_p            resq 1
ucall1_rsv_g             resq 1
ucall1_rsv_o             resq 1
ucall2_sv_0_t            resq 1
ucall2_sv_0_p            resq 1
ucall2_rsv_g             resq 1
ucall2_rsv_o             resq 1
ucall3_sv_0_t            resq 1
ucall3_sv_0_p            resq 1
ucall3_rsv_g             resq 1
ucall3_rsv_o             resq 1
conc_tmp0_rax            resq 1
conc_tmp0_rdx            resq 1
subject_data             resb 65536


section .text
main:
;  PROGRAM BODY ========================================================================================================
                            PROG_INIT

; ======================================================================================================================
                            mov         edi, 4
                            call        comm_stno
Ln_0:                       GOTO_ALWAYS L_fact_end_0

;  fact ================================================================================================================
L_fact_1:                   mov         edi, 5
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_n]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_INT    1
                            STORE_ARG32 16
                            APPLY_FN_N  S_eq, 2
                            add         rsp, 32
                            STORE_RESULT
                            push        rdx
                            push        rax
                            LOAD_INT    1
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_1
                            SET_VAR     S_fact
                            jmp         fn_fact_γ     ; return

; ======================================================================================================================
Ln_1:                       mov         edi, 6
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_n]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            sub         rsp, 8          ; align pad
                            GET_VAR     S_n
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        r12
                            push        qword [P_fact_ret_ω]
                            push        qword [P_fact_ret_γ]
                            CONC2_VI    S_sub, S_n, 1
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_fact_arg_0_t], rax
                            mov         [fn_fact_arg_0_p], rcx
                            mov         rdi, [rel box_fact_data_size]
                            call        blk_alloc
                            mov         rdi, rax
                            lea         rsi, [rel box_fact_data_template]
                            mov         rdx, [rel box_fact_data_size]
                            call        memcpy
                            mov         r12, rax
                            lea         rax, [rel ucall0_ret_g]
                            mov         [P_fact_ret_γ], rax
                            lea         rax, [rel ucall0_ret_o]
                            mov         [P_fact_ret_ω], rax
                            call        stmt_save_subject
                            jmp         P_fact_α
ucall0_ret_g:
                            pop         qword [P_fact_ret_γ]
                            pop         qword [P_fact_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_fact_data_size]
                            call        blk_free
                            call        stmt_restore_subject
                            GET_VAR     S_fact
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_n]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall0_has_val
                            LOAD_NULVCL32
                            jmp         ucall0_done
ucall0_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall0_done
ucall0_ret_o:
                            pop         qword [P_fact_ret_γ]
                            pop         qword [P_fact_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_fact_data_size]
                            call        blk_free
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_n]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            call        stmt_restore_subject
                            LOAD_FAILDESCR32
ucall0_done:
                            STORE_ARG32 16
                            APPLY_FN_N  S_mul, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_2
                            SET_VAR     S_fact
                            jmp         fn_fact_γ     ; return
Lf_2:                       jmp         fn_fact_γ     ; return

Ln_2:
;  fact_end ============================================================================================================
L_fact_end_0:               mov         edi, 7
                            call        comm_stno

; ======================================================================================================================
Ln_3:                       mov         edi, 9
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 8          ; align pad
                            GET_VAR     S_n
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        r12
                            push        qword [P_fact_ret_ω]
                            push        qword [P_fact_ret_γ]
                            LOAD_INT    5
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_fact_arg_0_t], rax
                            mov         [fn_fact_arg_0_p], rcx
                            mov         rdi, [rel box_fact_data_size]
                            call        blk_alloc
                            mov         rdi, rax
                            lea         rsi, [rel box_fact_data_template]
                            mov         rdx, [rel box_fact_data_size]
                            call        memcpy
                            mov         r12, rax
                            lea         rax, [rel ucall1_ret_g]
                            mov         [P_fact_ret_γ], rax
                            lea         rax, [rel ucall1_ret_o]
                            mov         [P_fact_ret_ω], rax
                            call        stmt_save_subject
                            jmp         P_fact_α
ucall1_ret_g:
                            pop         qword [P_fact_ret_γ]
                            pop         qword [P_fact_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_fact_data_size]
                            call        blk_free
                            call        stmt_restore_subject
                            GET_VAR     S_fact
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_n]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall1_has_val
                            LOAD_NULVCL32
                            jmp         ucall1_done
ucall1_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall1_done
ucall1_ret_o:
                            pop         qword [P_fact_ret_γ]
                            pop         qword [P_fact_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_fact_data_size]
                            call        blk_free
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_n]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            call        stmt_restore_subject
                            LOAD_FAILDESCR32
ucall1_done:
                            STORE_ARG32 0
                            LOAD_INT    120
                            STORE_ARG32 16
                            APPLY_FN_N  S_ne, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_4
                            jmp         Ln_4
Lf_4:                       jmp         L_e001_2

; ======================================================================================================================
Ln_4:                       mov         edi, 10
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1010_SL_001_CL_SP_fact_LP_5_RP_EQ_120
                            FAIL_BR     Lf_5
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_5:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_5:
;  e001 ================================================================================================================
L_e001_2:                   mov         edi, 11
                            call        comm_stno

; ======================================================================================================================
Ln_6:                       mov         edi, 14
                            call        comm_stno
                            sub         rsp, 16
                            sub         rsp, 32
                            mov         qword [rbp-32], 9
                            lea         rax, [rel S_facto]
                            mov         [rbp-24], rax
                            STORE_ARG32 0
                            LOAD_STR    S_fact
                            STORE_ARG32 16
                            APPLY_FN_N  S_opsyn, 2
                            add         rsp, 32
                            STORE_RESULT
                            STORE_ARG32 0
                            APPLY_FN_N  S_differ, 1
                            add         rsp, 16
                            STORE_RESULT
                            FAIL_BR     Lf_7
                            jmp         Ln_7
Lf_7:                       jmp         L_e002_3

; ======================================================================================================================
Ln_7:                       mov         edi, 15
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1010_SL_002_CL_SP_opsyn_SP_alias
                            FAIL_BR     Lf_8
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_8:                       GOTO_ALWAYS L_SNO_END     ; end

Ln_8:
;  e002 ================================================================================================================
L_e002_3:                   mov         edi, 16
                            call        comm_stno

; ======================================================================================================================
Ln_9:                       mov         edi, 17
                            call        comm_stno
                            sub         rsp, 32
                            CALL1_INT   S_facto, 4
                            STORE_ARG32 0
                            LOAD_INT    24
                            STORE_ARG32 16
                            APPLY_FN_N  S_ne, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_10
                            jmp         Ln_10
Lf_10:                      jmp         L_e003_4

; ======================================================================================================================
Ln_10:                      mov         edi, 18
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1010_SL_003_CL_SP_facto_LP_4_RP_EQ_24_SP_via_SP_alias
                            FAIL_BR     Lf_11
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_11:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_11:
;  e003 ================================================================================================================
L_e003_4:                   mov         edi, 19
                            call        comm_stno

; ======================================================================================================================
Ln_12:                      mov         edi, 22
                            call        comm_stno
Ln_13:                      GOTO_ALWAYS L_fact2_end_5

;  fact2_entry =========================================================================================================
L_fact2_entry_6:            mov         edi, 23
                            call        comm_stno

; ======================================================================================================================
Ln_14:                      mov         edi, 24
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_n]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            LOAD_INT    1
                            STORE_ARG32 16
                            APPLY_FN_N  S_eq, 2
                            add         rsp, 32
                            STORE_RESULT
                            push        rdx
                            push        rax
                            LOAD_INT    1
                            mov         rcx, rdx
                            mov         rdx, rax
                            pop         rdi
                            pop         rsi
                            call        stmt_concat
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            FAIL_BR     Ln_15
                            SET_VAR     S_fact2
                            GOTO_ALWAYS L_SNO_END     ; return

; ======================================================================================================================
Ln_15:                      mov         edi, 25
                            call        comm_stno
                            sub         rsp, 32
                            lea         rdi, [rel S_n]
                            call        stmt_get
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            STORE_ARG32 0
                            sub         rsp, 8          ; align pad
                            GET_VAR     S_n
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        r12
                            push        qword [P_fact2_ret_ω]
                            push        qword [P_fact2_ret_γ]
                            CONC2_VI    S_sub, S_n, 1
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_fact2_arg_0_t], rax
                            mov         [fn_fact2_arg_0_p], rcx
                            mov         rdi, [rel box_fact2_data_size]
                            call        blk_alloc
                            mov         rdi, rax
                            lea         rsi, [rel box_fact2_data_template]
                            mov         rdx, [rel box_fact2_data_size]
                            call        memcpy
                            mov         r12, rax
                            lea         rax, [rel ucall2_ret_g]
                            mov         [P_fact2_ret_γ], rax
                            lea         rax, [rel ucall2_ret_o]
                            mov         [P_fact2_ret_ω], rax
                            call        stmt_save_subject
                            jmp         P_fact2_α
ucall2_ret_g:
                            pop         qword [P_fact2_ret_γ]
                            pop         qword [P_fact2_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_fact2_data_size]
                            call        blk_free
                            call        stmt_restore_subject
                            GET_VAR     S_fact2
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_n]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall2_has_val
                            LOAD_NULVCL32
                            jmp         ucall2_done
ucall2_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall2_done
ucall2_ret_o:
                            pop         qword [P_fact2_ret_γ]
                            pop         qword [P_fact2_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_fact2_data_size]
                            call        blk_free
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_n]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            call        stmt_restore_subject
                            LOAD_FAILDESCR32
ucall2_done:
                            STORE_ARG32 16
                            APPLY_FN_N  S_mul, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_16
                            SET_VAR     S_fact2
                            GOTO_ALWAYS L_SNO_END     ; return
Lf_16:                      GOTO_ALWAYS L_SNO_END     ; return

Ln_16:
;  fact2_end ===========================================================================================================
L_fact2_end_5:              mov         edi, 26
                            call        comm_stno

; ======================================================================================================================
Ln_17:                      mov         edi, 27
                            call        comm_stno
                            sub         rsp, 32
                            sub         rsp, 8          ; align pad
                            GET_VAR     S_n
                            push        qword [rbp-8]
                            push        qword [rbp-16]
                            push        r12
                            push        qword [P_fact2_ret_ω]
                            push        qword [P_fact2_ret_γ]
                            LOAD_INT    6
                            mov         rax, [rbp-32]
                            mov         rcx, [rbp-24]
                            mov         [fn_fact2_arg_0_t], rax
                            mov         [fn_fact2_arg_0_p], rcx
                            mov         rdi, [rel box_fact2_data_size]
                            call        blk_alloc
                            mov         rdi, rax
                            lea         rsi, [rel box_fact2_data_template]
                            mov         rdx, [rel box_fact2_data_size]
                            call        memcpy
                            mov         r12, rax
                            lea         rax, [rel ucall3_ret_g]
                            mov         [P_fact2_ret_γ], rax
                            lea         rax, [rel ucall3_ret_o]
                            mov         [P_fact2_ret_ω], rax
                            call        stmt_save_subject
                            jmp         P_fact2_α
ucall3_ret_g:
                            pop         qword [P_fact2_ret_γ]
                            pop         qword [P_fact2_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_fact2_data_size]
                            call        blk_free
                            call        stmt_restore_subject
                            GET_VAR     S_fact2
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_n]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            call        stmt_is_fail
                            test        eax, eax
                            jz          ucall3_has_val
                            LOAD_NULVCL32
                            jmp         ucall3_done
ucall3_has_val:
                            mov         rax, [rbp-16]
                            mov         rdx, [rbp-8]
                            mov         [rbp-32], rax
                            mov         [rbp-24], rdx
                            jmp         ucall3_done
ucall3_ret_o:
                            pop         qword [P_fact2_ret_γ]
                            pop         qword [P_fact2_ret_ω]
                            pop         rdi
                            mov         rsi, [rel box_fact2_data_size]
                            call        blk_free
                            pop         rsi
                            pop         rdx
                            lea         rdi, [rel S_n]
                            call        stmt_set
                            add         rsp, 8          ; remove align pad
                            call        stmt_restore_subject
                            LOAD_FAILDESCR32
ucall3_done:
                            STORE_ARG32 0
                            LOAD_INT    720
                            STORE_ARG32 16
                            APPLY_FN_N  S_ne, 2
                            add         rsp, 32
                            STORE_RESULT
                            FAIL_BR     Lf_18
                            jmp         Ln_18
Lf_18:                      jmp         L_e004_7

; ======================================================================================================================
Ln_18:                      mov         edi, 28
                            call        comm_stno
                            LOAD_STR    S_FAIL_SP_1010_SL_004_CL_SP_fact2_LP_6_RP_EQ_720_SP_alt_SP_entry
                            FAIL_BR     Lf_19
                            SET_OUTPUT
                            GOTO_ALWAYS L_SNO_END     ; end
Lf_19:                      GOTO_ALWAYS L_SNO_END     ; end

Ln_19:
;  e004 ================================================================================================================
L_e004_7:                   mov         edi, 29
                            call        comm_stno

; ======================================================================================================================
Ln_20:                      mov         edi, 31
                            call        comm_stno
                            LOAD_STR    S_PASS_SP_1010_func_recursion_SP_LP_4_SL_4_RP
                            FAIL_BR     Ln_21
                            SET_OUTPUT
                            jmp         Ln_21
Ln_21:                      GOTO_ALWAYS L_SNO_END

L_SNO_END:
;  END =================================================================================================================
                            PROG_END

section .text

;  NAMED PATTERN BODIES ================================================================================================

; P_fact_α — user function α entry (1 param) [r12=DATA block]
;  fact ================================================================================================================
P_fact_α:                   FN_α_INIT   fact
                            mov         rsi, [fn_fact_arg_0_t]
                            mov         rdx, [fn_fact_arg_0_p]
                            FN_SET_PARAM S_n
                            LOAD_NULVCL
                            mov         [r12+16], rax
                            mov         [r12+24], rdx
                            mov         rsi, [r12+16]
                            mov         rdx, [r12+24]
                            FN_CLEAR_VAR S_fact
                            jmp         L_fact_1
;  γ/ω ---------------------------------------------------------------------------------------------------------------
fn_fact_γ:                  FN_γ        P_fact_ret_γ ; fn γ
fn_fact_ω:                  FN_ω        P_fact_ret_ω ; fn ω
P_fact_β:                   jmp         [P_fact_ret_ω] ; fn β — backtrack = fail

; P_fact2_α — user function α entry (1 param) [r12=DATA block]
;  fact2 ===============================================================================================================
P_fact2_α:                  FN_α_INIT   fact2
                            mov         rsi, [fn_fact2_arg_0_t]
                            mov         rdx, [fn_fact2_arg_0_p]
                            FN_SET_PARAM S_n
                            LOAD_NULVCL
                            mov         [r12+16], rax
                            mov         [r12+24], rdx
                            mov         rsi, [r12+16]
                            mov         rdx, [r12+24]
                            FN_CLEAR_VAR S_fact2
                            jmp         L_fact2_8
;  γ/ω ---------------------------------------------------------------------------------------------------------------
fn_fact2_γ:                 FN_γ        P_fact2_ret_γ ; fn γ
fn_fact2_ω:                 FN_ω        P_fact2_ret_ω ; fn ω
P_fact2_β:                  jmp         [P_fact2_ret_ω] ; fn β — backtrack = fail

section .text
L_fact2_8:  ; STUB → _SNO_END (dangling or computed goto)
;  STUB LABELS =========================================================================================================
                            GOTO_ALWAYS L_SNO_END

section .rodata
global  box_fact_reloc_count, box_fact_reloc_table
global  box_fact2_reloc_count, box_fact2_reloc_table
; --- box fact ---
box_fact_reloc_count: dq 0
box_fact_reloc_table:
; (entries added by M-T2-INVOKE)

; --- box fact2 ---
box_fact2_reloc_count: dq 0
box_fact2_reloc_table:
; (entries added by M-T2-INVOKE)

;  BOX RELOCATION TABLES ===============================================================================================

global  box_fact_data_template, box_fact_data_size
section .data
;  BOX DATA TEMPLATES ==================================================================================================
                            align       8
box_fact_data_size: dq 64
box_fact_data_template:
dq 0  ; [r12+0] = P_fact_ret_γ
dq 0  ; [r12+8] = P_fact_ret_ω
dq 0  ; [r12+16] = fn_fact_tmp1_t
dq 0  ; [r12+24] = fn_fact_tmp1_p
dq 0  ; [r12+32] = fn_fact_tmp2_t
dq 0  ; [r12+40] = fn_fact_tmp2_p
dq 0  ; [r12+48] = fn_fact_tmp3_t
dq 0  ; [r12+56] = fn_fact_tmp3_p

global  box_fact2_data_template, box_fact2_data_size
section .data
                            align       8
box_fact2_data_size: dq 64
box_fact2_data_template:
dq 0  ; [r12+0] = P_fact2_ret_γ
dq 0  ; [r12+8] = P_fact2_ret_ω
dq 0  ; [r12+16] = fn_fact2_tmp1_t
dq 0  ; [r12+24] = fn_fact2_tmp1_p
dq 0  ; [r12+32] = fn_fact2_tmp2_t
dq 0  ; [r12+40] = fn_fact2_tmp2_p
dq 0  ; [r12+48] = fn_fact2_tmp3_t
dq 0  ; [r12+56] = fn_fact2_tmp3_p


section .data
S_define             db 100, 101, 102, 105, 110, 101, 0  ; "define"
S_fact_LP_n_RP       db 102, 97, 99, 116, 40, 110, 41, 0  ; "fact(n)"
S_fact               db 102, 97, 99, 116, 0  ; "fact"
S_eq                 db 101, 113, 0  ; "eq"
S_n                  db 110, 0  ; "n"
S_fact_end           db 102, 97, 99, 116, 95, 101, 110, 100, 0  ; "fact_end"
S_ne                 db 110, 101, 0  ; "ne"
S_output             db 111, 117, 116, 112, 117, 116, 0  ; "output"
S_FAIL_SP_1010_SL_001_CL_SP_fact_LP_5_RP_EQ_120 db 70, 65, 73, 76, 32, 49, 48, 49, 48, 47, 48, 48, 49, 58, 32, 102, 97, 99, 116, 40, 53, 41, 61, 49, 50, 48, 0  ; "FAIL 1010/001: fact(5)=120"
S_e001               db 101, 48, 48, 49, 0  ; "e001"
S_differ             db 100, 105, 102, 102, 101, 114, 0  ; "differ"
S_opsyn              db 111, 112, 115, 121, 110, 0  ; "opsyn"
S_facto              db 102, 97, 99, 116, 111, 0  ; "facto"
S_FAIL_SP_1010_SL_002_CL_SP_opsyn_SP_alias db 70, 65, 73, 76, 32, 49, 48, 49, 48, 47, 48, 48, 50, 58, 32, 111, 112, 115, 121, 110, 32, 97, 108, 105, 97, 115, 0  ; "FAIL 1010/002: opsyn alias"
S_e002               db 101, 48, 48, 50, 0  ; "e002"
S_FAIL_SP_1010_SL_003_CL_SP_facto_LP_4_RP_EQ_24_SP_via_SP_alias db 70, 65, 73, 76, 32, 49, 48, 49, 48, 47, 48, 48, 51, 58, 32, 102, 97, 99, 116, 111, 40, 52, 41, 61, 50, 52, 32, 118, 105, 97, 32, 97, 108, 105, 97, 115, 0  ; "FAIL 1010/003: facto(4)=24 via alias"
S_e003               db 101, 48, 48, 51, 0  ; "e003"
S_fact2_entry        db 102, 97, 99, 116, 50, 95, 101, 110, 116, 114, 121, 0  ; "fact2_entry"
S_fact2_LP_n_RP      db 102, 97, 99, 116, 50, 40, 110, 41, 0  ; "fact2(n)"
S_fact2              db 102, 97, 99, 116, 50, 0  ; "fact2"
S_fact2_end          db 102, 97, 99, 116, 50, 95, 101, 110, 100, 0  ; "fact2_end"
S_FAIL_SP_1010_SL_004_CL_SP_fact2_LP_6_RP_EQ_720_SP_alt_SP_entry db 70, 65, 73, 76, 32, 49, 48, 49, 48, 47, 48, 48, 52, 58, 32, 102, 97, 99, 116, 50, 40, 54, 41, 61, 55, 50, 48, 32, 97, 108, 116, 32, 101, 110, 116, 114, 121, 0  ; "FAIL 1010/004: fact2(6)=720 alt entry"
S_e004               db 101, 48, 48, 52, 0  ; "e004"
S_PASS_SP_1010_func_recursion_SP_LP_4_SL_4_RP db 80, 65, 83, 83, 32, 49, 48, 49, 48, 95, 102, 117, 110, 99, 95, 114, 101, 99, 117, 114, 115, 105, 111, 110, 32, 40, 52, 47, 52, 41, 0  ; "PASS 1010_func_recursion (4/4)"
S_end                db 101, 110, 100, 0  ; "end"
S_mul                db 109, 117, 108, 0  ; "mul"
S_sub                db 115, 117, 98, 0  ; "sub"
